export type EnglishUnit = {
  id: string;
  title: string;
  shortTitle: string;
};

export type EnglishVocabCard = {
  id: string;
  unit: string;
  en: string;
  ja: string;
  note?: string;
};

export type EnglishQuestion = {
  id: string;
  unit: string;
  group: string;
  format: "input" | "choice" | "order" | "translation";
  prompt: string;
  answer: string;
  accepted?: string[];
  options?: string[];
  tokens?: string[];
  explanation?: string;
  passageId?: string;
};

export type EnglishPassage = {
  id: string;
  unit: string;
  title: string;
  titleJa: string;
  paragraphs: Array<{ en: string; ja: string }>;
};

export const ENGLISH_UNITS: EnglishUnit[] = [
  { id: "ch15", title: "Chapter 15｜新しい生命体を作り出す企業", shortTitle: "Ch.15 新しい生命体を作り出す企業" },
  { id: "ch16", title: "Chapter 16｜スパコンで天気予報①", shortTitle: "Ch.16 スパコンで天気予報①" },
  { id: "ch18", title: "Chapter 18｜高齢化社会に強力な助っ人", shortTitle: "Ch.18 高齢化社会に強力な助っ人" },
  { id: "ch19", title: "Chapter 19｜食品偽装を見破るソフト", shortTitle: "Ch.19 食品偽装を見破るソフト" },
];

type RawVocab = [unit: string, en: string, ja: string, note?: string];

const RAW_VOCAB: RawVocab[] = [
  ["exam-sample", "lean against", "～にもたれかかる"],
  ["exam-sample", "load", "積み込む"],
  ["exam-sample", "across from", "～の向かい側に"],
  ["exam-sample", "gather", "集まる／集める"],
  ["exam-sample", "in a line", "一列に"],
  ["exam-sample", "reach for", "～を取ろうと手を伸ばす"],
  ["exam-sample", "occupied", "使用中の／ふさがっている"],
  ["exam-sample", "clerk", "店員、事務員"],
  ["exam-sample", "passenger", "乗客"],
  ["exam-sample", "pedestrian", "歩行者"],
  ["exam-sample", "annual", "年1回の、毎年の"],
  ["exam-sample", "audience", "聴衆、観客"],
  ["exam-sample", "bankrupt", "破産した"],
  ["exam-sample", "capability", "能力"],
  ["exam-sample", "strategy", "戦略"],
  ["exam-sample", "temporary", "一時的な"],
  ["exam-sample", "guarantee", "保証する／保証"],

  ["ch15", "life-form / organism", "生命体、生物"],
  ["ch15", "laboratory", "実験室"],
  ["ch15", "cell", "細胞"],
  ["ch15", "DNA sequence", "DNA配列"],
  ["ch15", "petrochemicals", "石油化学製品"],
  ["ch15", "type out", "キーボードで打ち込む"],
  ["ch15", "robotic arm", "ロボットアーム"],
  ["ch15", "mix together", "混ぜ合わせる"],
  ["ch15", "compound", "化合物"],
  ["ch15", "desired", "目的の、望まれた"],
  ["ch15", "biotech company", "バイオテクノロジー企業"],
  ["ch15", "genetically modified", "遺伝子組み換えの"],
  ["ch15", "yeast", "酵母"],
  ["ch15", "at a dizzying rate", "めまぐるしい速度で"],
  ["ch15", "convert A into B", "AをBに変換する"],
  ["ch15", "medicine", "医薬品"],
  ["ch15", "moisturizer", "保湿剤"],
  ["ch15", "cosmetics", "化粧品"],
  ["ch15", "biofuel", "バイオ燃料"],
  ["ch15", "renewable energy source", "再生可能エネルギー源"],
  ["ch15", "chief science officer", "最高科学責任者"],
  ["ch15", "industrial revolution", "産業革命"],
  ["ch15", "living system", "生物システム、生物"],
  ["ch15", "biofactory", "バイオ工場"],
  ["ch15", "substance", "物質"],
  ["ch15", "tricky", "扱いづらい、難しい"],
  ["ch15", "biological means of production", "生物学的生産手段"],
  ["ch15", "revolutionize", "大変革をもたらす"],
  ["ch15", "transform", "変える、変革する"],
  ["ch15", "environmental safety", "環境上の安全性"],
  ["ch15", "bio-security", "生物学的安全保障"],
  ["ch15", "revive", "再燃させる"],
  ["ch15", "ethical debate", "倫理的論争"],
  ["ch15", "play God", "神を演じる"],
  ["ch15", "in the pipeline", "開発中で、進行中で"],
  ["ch15", "be founded", "創業される"],
  ["ch15", "a decade", "10年間"],
  ["ch15", "legend", "伝説的な存在"],
  ["ch15", "at the intersection of A and B", "AとBが交わる領域で"],
  ["ch15", "genetic engineering", "遺伝子工学"],
  ["ch15", "swap", "入れ替える"],
  ["ch15", "gene", "遺伝子"],
  ["ch15", "genome", "ゲノム"],
  ["ch15", "from scratch", "ゼロから"],

  ["ch16", "accurate", "正確な"],
  ["ch16", "essential factor", "不可欠な要素"],
  ["ch16", "weather forecast", "天気予報"],
  ["ch16", "atmospheric conditions", "大気の状況"],
  ["ch16", "meteorological", "気象の、気象学上の"],
  ["ch16", "detailed", "詳細な"],
  ["ch16", "cloud map", "雲地図"],
  ["ch16", "Earth's surface", "地球表面"],
  ["ch16", "processing supercomputer", "処理用スーパーコンピュータ"],
  ["ch16", "accurate forecast", "正確な予報"],
  ["ch16", "typhoon", "台風"],
  ["ch16", "heavy rain", "大雨"],
  ["ch16", "divide A into B", "AをBに分ける"],
  ["ch16", "square block", "正方形の区画"],
  ["ch16", "cloud formation", "雲の形成"],
  ["ch16", "movement", "動き"],
  ["ch16", "predict", "予測する"],
  ["ch16", "based on", "～に基づいて"],
  ["ch16", "meteorological institution", "気象機関"],
  ["ch16", "measure", "～の大きさである"],
  ["ch16", "previous attempt", "従来の試み"],
  ["ch16", "narrow A down to B", "AをBまで狭める"],
  ["ch16", "split A into B", "AをBに分割する"],
  ["ch16", "hexagonal", "六角形の"],
  ["ch16", "space ... apart", "～の間隔を空ける"],
  ["ch16", "reproduce", "再現する"],
  ["ch16", "devastate", "甚大な被害を与える"],
  ["ch16", "entire globe", "地球全体"],
  ["ch16", "work on", "～に取り組む"],
  ["ch16", "improve", "改善する"],
  ["ch16", "natural disaster", "自然災害"],

  ["ch18", "utilize", "活用する"],
  ["ch18", "advanced technology", "先端技術"],
  ["ch18", "nervous system", "神経系"],
  ["ch18", "telecommunication technology", "情報通信技術"],
  ["ch18", "home electronic appliance", "家庭電化製品"],
  ["ch18", "intention", "意図"],
  ["ch18", "brain wave", "脳波"],
  ["ch18", "in line with", "～に沿って、～と一致して"],
  ["ch18", "graying", "高齢化"],
  ["ch18", "put to practical use", "実用化する"],
  ["ch18", "nursing care facility", "介護施設、老人ホーム"],
  ["ch18", "labor shortage", "労働力不足"],
  ["ch18", "research institute", "研究所"],
  ["ch18", "machinery manufacturer", "機械メーカー"],
  ["ch18", "sensor", "センサー、検知器"],
  ["ch18", "detect", "検知する"],
  ["ch18", "analyze", "分析する"],
  ["ch18", "predict", "予測する"],
  ["ch18", "recognize", "認識する"],
  ["ch18", "direction", "方向"],
  ["ch18", "multiple", "多数の"],
  ["ch18", "obstacle", "障害物"],
  ["ch18", "uneven", "凹凸のある、平らでない"],
  ["ch18", "current location", "現在地"],
  ["ch18", "destination", "目的地"],
  ["ch18", "route", "経路"],
  ["ch18", "latest", "最新の"],
  ["ch18", "avoid danger", "危険を避ける"],
  ["ch18", "cooperation", "協力"],
  ["ch18", "aim to", "～することを目指す"],
  ["ch18", "perform", "行う"],
  ["ch18", "share", "共有する、分担する"],
  ["ch18", "via", "～を経由して"],

  ["ch19", "determine", "特定する、決定する"],
  ["ch19", "utilize", "利用する、活用する"],
  ["ch19", "prevent", "防ぐ、阻止する"],
  ["ch19", "DNA barcoding", "DNAバーコーディング"],
  ["ch19", "living object", "生物"],
  ["ch19", "be based on", "～に基づく"],
  ["ch19", "automatically", "自動的に"],
  ["ch19", "database", "データベース"],
  ["ch19", "experience", "経験"],
  ["ch19", "detect", "見破る、検知する"],
  ["ch19", "environmental", "環境の"],
  ["ch19", "species", "種（単数・複数が同形）"],
  ["ch19", "fungus", "菌類、キノコ類", "複数形 fungi"],
  ["ch19", "organism", "生物"],
  ["ch19", "virus", "ウイルス", "複数形 viruses"],
  ["ch19", "family", "科", "複数形 families"],
  ["ch19", "genus", "属", "複数形 genera"],
  ["ch19", "halt", "阻止する、中止する"],
  ["ch19", "food fraud", "食品偽装"],
  ["ch19", "fraudulent mislabeling", "悪質な不当表示"],
  ["ch19", "farm products", "農産物"],
  ["ch19", "DNA sequence information", "DNA配列情報"],
  ["ch19", "yellowfin tuna", "キハダマグロ"],
  ["ch19", "Pacific bluefin tuna", "太平洋クロマグロ"],
  ["ch19", "drastically", "大幅に"],
  ["ch19", "distinguish", "見分ける、区別する"],
  ["ch19", "existing", "既存の"],
  ["ch19", "to date", "現在までのところ"],
  ["ch19", "tissue", "組織"],
  ["ch19", "mislabeling", "不当表示、誤表示"],
  ["ch19", "play a central role", "中心的役割を果たす"],
  ["ch19", "belong to", "～に属する"],
  ["ch19", "be related to", "～と関連している"],
  ["ch19", "fraud", "詐欺、詐欺行為"],
  ["ch19", "fraudulent", "詐欺の、不正な"],
  ["ch19", "announce", "発表する"],
  ["ch19", "set off an alarm", "警報を作動させる"],
  ["ch19", "including", "～を含む"],
  ["ch19", "compare A with B", "AとBを比較する"],
  ["ch19", "graduate school", "大学院"],
];

export const ENGLISH_VOCAB: EnglishVocabCard[] = RAW_VOCAB
  .map(([unit, en, ja, note], index) => ({
    id: `ev-${String(index + 1).padStart(3, "0")}`,
    unit,
    en,
    ja,
    note,
  }))
  .filter((card) => card.unit !== "exam-sample");

export const ENGLISH_PASSAGES: EnglishPassage[] = [
  {
    id: "passage-amyris",
    unit: "ch15",
    title: "Scientists now creating millions of organisms from scratch",
    titleJa: "Chapter 15｜新しい生命体を作り出す企業",
    paragraphs: [
      {
        en: "For scientist Jack Newman, creating a new life-form has become as simple as this: He types out a DNA sequence on his laptop, and clicks ‘send.’",
        ja: "科学者ジャック・ニューマン氏にとって、新しい生命体を作ることは、ノートパソコンでDNA配列を打ち込み「送信」をクリックするほど簡単になった。",
      },
      {
        en: "Nearby in the laboratory, robotic arms start to mix together some compounds to produce the desired cells.",
        ja: "近くの実験室では、目的の細胞を作るために、ロボットアームがいくつかの化合物を混ぜ始める。",
      },
      {
        en: "Newman’s biotech company is creating new organisms, mostly forms of genetically modified yeast, at a dizzying rate of more than 1,500 a day.",
        ja: "ニューマン氏のバイオ企業は、主に遺伝子組み換え酵母の形をした新しい生命体を、1日1,500個を超えるめまぐるしい速度で作っている。",
      },
      {
        en: "Some convert sugar into medicines. Others create moisturizers that can be used in cosmetics. And still others make biofuel, a renewable energy source usually made from corn.",
        ja: "砂糖を医薬品に変換するもの、化粧品に使える保湿剤を作るもの、さらに通常はトウモロコシから作られる再生可能エネルギー源であるバイオ燃料を作るものもある。",
      },
      {
        en: "You can now build a cell the same way you might build an app for your iPhone, said Newman, chief science officer of Amyris.",
        ja: "「今ではiPhone用アプリを作るのと同じように細胞を作れます」と、Amyrisの最高科学責任者ニューマン氏は述べた。",
      },
      {
        en: "Some believe this kind of work marks the beginning of a third industrial revolution—one based on using living systems as biofactories for creating substances that are too tricky or too expensive to grow in nature or to make with petrochemicals.",
        ja: "この仕事は、生物をバイオ工場として使い、自然界で育てたり石油化学製品から作ったりするには難しすぎる、または高価すぎる物質を生み出す第三次産業革命の始まりだと考える人もいる。",
      },
      {
        en: "The rush to biological means of production promises to revolutionize the chemical industry and transform the economy, but it also raises questions about environmental safety and bio-security and revives ethical debates about playing God. Hundreds of products are in the pipeline.",
        ja: "生物学的な生産手段への動きは、化学産業と経済を変革すると期待される一方、環境上の安全性や生物学的安全保障への疑問を生み、「神を演じること」に関する倫理論争を再燃させる。何百もの製品が開発中である。",
      },
      {
        en: "Since it was founded a decade ago, Amyris has become a legend in the field that sits at the intersection of biology and engineering, creating more than 3 million new organisms.",
        ja: "10年前の創業以来、Amyrisは生物学と工学の交差する分野で伝説的存在となり、300万を超える新しい生命体を作ってきた。",
      },
      {
        en: "Unlike traditional genetic engineering, which typically involves swapping a few genes, the scientists are building entire genomes from scratch.",
        ja: "通常は少数の遺伝子を入れ替える従来の遺伝子工学とは異なり、科学者たちはゲノム全体をゼロから構築している。",
      },
    ],
  },
  {
    id: "passage-weather",
    unit: "ch16",
    title: "Japanese supercomputer shows detailed cloud movements on Earth’s surface",
    titleJa: "Chapter 16｜スパコンで天気予報①",
    paragraphs: [
      {
        en: "A group of scientists have created a detailed cloud map of the Earth’s surface using the K computer—Japan’s fastest processing supercomputer—that could help provide more accurate forecasts for typhoons and heavy rain.",
        ja: "科学者グループは、日本最速の処理用スーパーコンピュータ「京」を使って地球表面の詳細な雲地図を作った。この地図は台風や大雨をより正確に予報する助けとなる可能性がある。",
      },
      {
        en: "With a cloud map, the Earth’s surface is divided into square blocks. Cloud formation and movements, which are essential factors in weather forecasts, are predicted based on atmospheric conditions in each block.",
        ja: "雲地図では地球表面を正方形の区画に分け、天気予報に不可欠な雲の形成と動きを各区画の大気条件に基づいて予測する。",
      },
      {
        en: "Typically, computers at meteorological institutions, such as the Japan Meteorological Agency, divide each block into squares measuring 20 km by 20 km.",
        ja: "通常、気象庁などの気象機関のコンピュータは、各区画を20km四方に分割する。",
      },
      {
        en: "Previous attempts to use high-tech supercomputers have been able to narrow each block down to 3.5 kilometers.",
        ja: "従来の高性能スーパーコンピュータでは、各区画を3.5km四方まで狭めることができた。",
      },
      {
        en: "By using the K computer, the team were able to split the Earth’s surface into some 63 billion hexagonal blocks, with each block spaced only 870 meters apart, and successfully reproduced cloud movement in each block.",
        ja: "「京」を使ったチームは地球表面を約630億個の六角形区画に分け、区画同士の間隔をわずか870mにし、各区画の雲の動きを再現することに成功した。",
      },
      {
        en: "When the team tested the system to reproduce cloud movement during Typhoon No. 15 in August 2012, the cloud map showed a detailed picture of clouds across the entire globe.",
        ja: "チームが2012年8月の台風15号の雲の動きを再現するテストを行ったところ、雲地図は地球全体の雲を詳細に示した。",
      },
      {
        en: "The team will work on improving the system for more accurate typhoon and heavy rain forecasting, as there has been an increase in such natural disasters.",
        ja: "こうした自然災害が増加しているため、チームはより正確な台風・大雨予報に向けてシステム改善に取り組む。",
      },
    ],
  },
  {
    id: "passage-wheelchair",
    unit: "ch18",
    title: "Robot wheelchairs would read users’ minds",
    titleJa: "Chapter 18｜高齢化社会に強力な助っ人",
    paragraphs: [
      {
        en: "The Internal Affairs and Communications Ministry said it aims to start a project to develop robot wheelchairs, which detect users’ intentions from their brain waves and automatically move in line with the users’ will.",
        ja: "総務省は、脳波から利用者の意図を読み取り、利用者の意志に沿って自動的に動くロボット車椅子を開発するプロジェクトの開始を目指していると述べた。",
      },
      {
        en: "While the graying of Japan’s population continues, the ministry expects that robot wheelchairs will be put to practical use in nursing care facilities, where a labor shortage is predicted.",
        ja: "日本人口の高齢化が続く中、総務省は、労働力不足が予想される介護施設でロボット車椅子が実用化されることを期待している。",
      },
      {
        en: "In cooperation with research institutes, telecommunications companies and machinery manufacturers, the ministry aims to put the technology to practical use possibly in 2017.",
        ja: "研究所、通信会社、機械メーカーと協力し、総務省はこの技術を2017年にも実用化することを目指している。",
      },
      {
        en: "The planned robot wheelchairs will have sensors that detect users’ intentions by analyzing their brain waves and nervous system activity, moving automatically.",
        ja: "計画中のロボット車椅子は、脳波と神経系の活動を分析して利用者の意図を検知するセンサーを備え、自動的に動く。",
      },
      {
        en: "Some research institutions have studied technologies needed for the robot wheelchairs.",
        ja: "一部の研究機関はロボット車椅子に必要な技術を研究してきた。",
      },
      {
        en: "They include a system in which computers recognize users’ intentions if users think about the directions, for example right or left, in which they want to move.",
        ja: "その技術には、利用者が右・左など進みたい方向を思い浮かべると、コンピューターが利用者の意図を認識するシステムが含まれる。",
      },
      {
        en: "In their experiments, wheelchairs have successfully moved short distances and performed simple operations involving home electronic appliances.",
        ja: "実験では、車椅子は短距離の移動に成功し、家庭電化製品に関わる簡単な操作を行った。",
      },
      {
        en: "The ministry also plans to establish telecommunication technology in which multiple wheelchairs will be connected by networks so that their users will be able to share information about obstacles and uneven surfaces.",
        ja: "総務省は、多数の車椅子をネットワークで接続し、利用者が障害物や凹凸のある表面について情報を共有できる通信技術の確立も計画している。",
      },
      {
        en: "Under the planned system, wheelchairs will calculate current locations and routes to destinations.",
        ja: "計画中のシステムでは、車椅子が現在地と目的地までの経路を計算する。",
      },
      {
        en: "The latest information from wheelchairs that have passed through dangerous places will be sent to other wheelchairs to help them choose routes that avoid danger.",
        ja: "危険な場所を通過した車椅子からの最新情報は、危険を避ける経路選びを助けるため、ほかの車椅子に送られる。",
      },
    ],
  },
  {
    id: "passage-dna",
    unit: "ch19",
    title: "Kyoto researchers develop DNA software that can halt food fraud",
    titleJa: "Chapter 19｜食品偽装を見破るソフト",
    paragraphs: [
      {
        en: "A group of researchers at Kyoto University has developed DNA barcoding software that can prevent the fraudulent mislabeling of farm products and seafood.",
        ja: "京都大学の研究者グループが、農産物や水産物の悪質な不当表示を防止できるDNAバーコーディングソフトウェアを開発した。",
      },
      {
        en: "Utilizing the newly developed software, users can easily determine the species of living objects based on their DNA sequence information.",
        ja: "新開発のソフトウェアを利用すれば、ユーザーは生物のDNA配列情報に基づいて、その種を容易に特定できる。",
      },
      {
        en: "The development of the software was announced in the U.S. scientific research journal PLOS ONE.",
        ja: "そのソフトウェアの開発は、米国の科学学術誌PLOS ONEで発表された。",
      },
      {
        en: "Prices of yellowfin tuna and Pacific bluefin tuna are drastically different. But if they are used in cooking, it is difficult even for experts to distinguish between them.",
        ja: "キハダマグロと太平洋クロマグロでは価格が大幅に異なる。しかし料理に使われてしまうと、専門家でさえ両者を見分けるのは難しい。",
      },
      {
        en: "If you use this software, you can easily detect mislabeling, said Akifumi Tanabe, who played the central role in the software’s development.",
        ja: "「このソフトウェアを使えば、不当表示を簡単に見抜くことができます」と、ソフトウェア開発で中心的役割を果たした田辺氏は述べた。",
      },
      {
        en: "The researchers, including those of the university’s Graduate School of Global Environmental Studies, created software that can compare the DNA sequences of plants, fish and other living objects with those stored in DNA databases.",
        ja: "大学院地球環境学堂の研究者を含む研究者グループは、植物や魚、その他の生物のDNA配列を、DNAデータベースに蓄積されたものと照合できるソフトウェアを作り上げた。",
      },
      {
        en: "By comparing the DNA barcoding, the software can automatically determine the species the tissue came from.",
        ja: "DNAバーコーディングを比較することで、そのソフトウェアは、その組織がどの種のものかを自動的に特定できる。",
      },
      {
        en: "Even in the case of new species, the software can determine which families or genera they belong to and which existing species they are related to.",
        ja: "新種の場合でも、そのソフトウェアは、それらがどの科や属に入るか、またどの既存種と関連しているかを特定できる。",
      },
      {
        en: "Databases have been released in Japan, the United States and Europe that store the DNA sequences of a total of about 288,000 species of living organisms, including fungi and viruses.",
        ja: "菌類やウイルスを含む合計約28万8千種の生物のDNA配列を蓄積したデータベースが、日米欧で公開されている。",
      },
      {
        en: "To date, the work to determine which species living organisms belong to has mostly depended on the knowledge of experts and their experience.",
        ja: "現在まで、生物がどの種に属するかを特定する作業は、主に専門家の知識と経験に頼ってきた。",
      },
    ],
  },
];

type RawOrder = [
  unit: string,
  keyword: string,
  prompt: string,
  tokens: string[],
  answer: string,
];

const ORDER_QUESTIONS: RawOrder[] = [
  ["exam-sample", "substantially", "語句を並べ替え：トム・ブラウンの研修は、従業員が業績を大幅に改善するのに役立った。", ["Tom Brown's training", "has helped", "employees", "improve", "their performance", "substantially"], "Tom Brown's training has helped employees improve their performance substantially."],
  ["exam-sample", "be surrounded by", "語句を並べ替え：その建物は大木に囲まれています。", ["The building", "is", "surrounded", "by", "large trees"], "The building is surrounded by large trees."],
  ["exam-sample", "be connected to", "語句を並べ替え：男性の頭部は天井に繋げられています。", ["The man's head", "is", "connected", "to", "the ceiling"], "The man's head is connected to the ceiling."],

  ["ch15", "from scratch", "その男性は一からビジネスを立ち上げた。", ["The man", "built", "his business up", "from", "scratch"], "The man built his business up from scratch."],
  ["ch15", "millions of", "その試合は何百万人もの人が見ています。", ["The game", "is", "watched", "by", "millions", "of", "people"], "The game is watched by millions of people."],
  ["ch15", "twice as ... as", "この部屋はあの部屋の2倍の大きさだ。", ["This room", "is", "twice", "as big", "as", "that room"], "This room is twice as big as that room."],
  ["ch15", "modify", "合うようにテーブルの高さを修正しなければならなかった。", ["They", "had", "to", "modify", "the height", "of", "the table", "to", "make", "it fit"], "They had to modify the height of the table to make it fit."],
  ["ch15", "at the rate of", "この会社は一日に200台の割合で車を製造している。", ["This firm", "manufactures", "cars", "at", "the rate", "of", "two hundred", "per day"], "This firm manufactures cars at the rate of two hundred per day."],
  ["ch15", "convert A into B", "48時間を分に直すと何分ですか？", ["If", "you", "convert", "48 hours", "into minutes", "how many minutes", "does that make"], "If you convert 48 hours into minutes, how many minutes does that make?"],
  ["ch15", "build up", "その女性は大きな財産を築き上げた。", ["The woman", "built up", "a", "large", "fortune"], "The woman built up a large fortune."],

  ["ch16", "detailed", "部長は私達にその企画の詳細な説明を提供してくれた。", ["The manager", "gave", "us", "a detailed", "explanation of", "the project"], "The manager gave us a detailed explanation of the project."],
  ["ch16", "surface", "草原が地表の3分の1を覆っています。", ["Grasslands", "cover", "one", "third of", "the Earth's", "surface"], "Grasslands cover one third of the Earth's surface."],
  ["ch16", "accurate", "あなたの言う事実が正確であることを確認してください。", ["Make", "sure", "your", "facts", "are", "accurate"], "Make sure your facts are accurate."],
  ["ch16", "heavy rain", "そのイベントは大雨のために明日に延期になりました。", ["The event", "has", "been", "postponed", "to tomorrow", "due to", "heavy", "rain"], "The event has been postponed to tomorrow due to heavy rain."],
  ["ch16", "be divided into", "クラスはグループプロジェクトのためにグループに分けられました。", ["The class", "was", "divided", "into", "groups", "for", "a group project"], "The class was divided into groups for a group project."],
  ["ch16", "formation", "火山活動が約500万年前にハワイ諸島の形成につながった。", ["Volcanic", "activity", "led to", "the formation", "of", "the Hawaiian Islands", "around 5 million", "years ago"], "Volcanic activity led to the formation of the Hawaiian Islands around 5 million years ago."],
  ["ch16", "factor", "経済の安定性は、国の発展にとって重要な要素です。", ["Economic", "stability", "is", "a crucial", "factor", "for", "a country's", "development"], "Economic stability is a crucial factor for a country's development."],
  ["ch16", "essential", "自転車に乗る時に、ヘルメットをかぶるのは不可欠です。", ["It's", "essential", "to", "wear", "a helmet", "while riding", "a bicycle"], "It's essential to wear a helmet while riding a bicycle."],
  ["ch16", "based on", "その医師の決断は検査結果に基づいていた。", ["The doctor's", "decision", "was", "based on", "the test", "results"], "The doctor's decision was based on the test results."],
  ["ch16", "atmospheric", "大気中の二酸化炭素レベルを下げる必要があります。", ["We", "need", "to", "reduce", "atmospheric", "carbon dioxide", "levels"], "We need to reduce atmospheric carbon dioxide levels."],
  ["ch16", "measure", "そのプールは3メートルの深さがある。", ["The", "pool", "measures", "3", "meters", "deep"], "The pool measures 3 meters deep."],
  ["ch16", "narrow", "そのプレゼンのためのテーマを狭めるべきです。", ["You", "should", "narrow", "your", "topic", "for", "the presentation"], "You should narrow your topic for the presentation."],
  ["ch16", "split", "この食事は割り勘にするべきです。", ["We", "should", "split", "the check", "for this", "meal"], "We should split the check for this meal."],

  ["ch18", "intention", "彼らには結婚する意向はなかった。", ["They", "had", "no", "intention of", "getting", "married"], "They had no intention of getting married."],
  ["ch18", "in line with", "双方の意見は一致していた。", ["The", "two sides", "are", "in", "line", "with", "each", "other"], "The two sides are in line with each other."],
  ["ch18", "predict", "そのシステムは気象パターンを予測するのに機械学習を使っている。", ["The system", "uses", "machine learning", "to", "predict", "weather", "patterns"], "The system uses machine learning to predict weather patterns."],
  ["ch18", "put into practical use", "暗記した英文を実践で応用したい。", ["I", "want to", "put", "the English", "sentences", "that I memorized", "into", "practical use"], "I want to put the English sentences that I memorized into practical use."],
  ["ch18", "cooperation", "その学生たちは協力することの大切さを学んでいる。", ["The students", "are", "learning", "the importance", "of", "cooperation"], "The students are learning the importance of cooperation."],
  ["ch18", "aim to", "彼らは世界一のスポーツ選手になることを目指している。", ["They", "aim", "to be", "the top", "athletes", "in", "the world"], "They aim to be the top athletes in the world."],
  ["ch18", "recognize", "私は彼の声からすぐに彼だと分かった。", ["I", "recognized", "him", "instantly from", "his", "voice"], "I recognized him instantly from his voice."],
  ["ch18", "perform", "外科医は患者の心臓に手術を行います。", ["The surgeon", "will", "perform", "surgery", "on the patient's", "heart"], "The surgeon will perform surgery on the patient's heart."],
  ["ch18", "share", "チームは仕事を均等に分担することにしました。", ["The", "team", "decided", "to", "share", "the", "workload", "evenly"], "The team decided to share the workload evenly."],
  ["ch18", "via", "ユーザーはネットワークを経由して障害物を検知します。", ["The", "user", "detects", "obstacles", "via", "a network"], "The user detects obstacles via a network."],

  ["ch19", "fraud", "そのケースには、さまざまな異なる手口の詐欺が含まれていた。", ["The case", "included", "a number", "of", "different", "kinds of", "fraud"], "The case included a number of different kinds of fraud."],
  ["ch19", "halt", "著者が情報源を偽っていたことがわかり、出版社はその本の発行を中止した。", ["The publisher", "halted", "the release", "of", "the book", "when", "they found", "the author", "had lied about", "his sources"], "The publisher halted the release of the book when they found the author had lied about his sources."],
  ["ch19", "fraudulent", "その従業員は詐欺行為のため解雇された。", ["The employee", "was", "dismissed", "due", "to", "fraudulent", "activities"], "The employee was dismissed due to fraudulent activities."],
  ["ch19", "determine", "専門家は、それがどのような種類の車であるかをはっきりさせるだろう。", ["Experts", "will", "determine", "what", "kind of", "car", "it is"], "Experts will determine what kind of car it is."],
  ["ch19", "announce", "彼らは受賞者を発表するところだ。", ["They", "are", "about", "to", "announce", "the", "winner"], "They are about to announce the winner."],
  ["ch19", "distinguish", "その子供はまだ空想と現実を区別できない。", ["The", "child", "still cannot", "distinguish", "fantasy", "from", "reality"], "The child still cannot distinguish fantasy from reality."],
  ["ch19", "detect", "このセンサーは煙を感知すると警報を作動させる。", ["This", "sensor", "sets off", "an alarm", "when", "it", "detects", "smoke"], "This sensor sets off an alarm when it detects smoke."],
  ["ch19", "mislabeling", "我が社は食品内容の誤表示を避けるべきです。", ["Our", "company", "should", "avoid", "mislabeling", "the product", "contents"], "Our company should avoid mislabeling the product contents."],
  ["ch19", "play a role", "彼にはその団体での重要な役割があります。", ["He", "has", "an", "important", "role", "in", "the organization"], "He has an important role in the organization."],
  ["ch19", "including", "その観光客は東京と京都を含む多くの都市を訪れました。", ["The tourists", "visited", "many", "cities", "including", "Tokyo", "and Kyoto"], "The tourists visited many cities, including Tokyo and Kyoto."],
  ["ch19", "compare A with B", "彼は自分を兄たちと比べるべきではない。", ["He", "shouldn't", "compare", "himself", "with", "his", "brothers"], "He shouldn't compare himself with his brothers."],
  ["ch19", "graduate school", "私の姉は今月、いくつかの大学院に出願しています。", ["My", "sister", "is", "applying", "to", "several", "graduate", "schools", "this", "month"], "My sister is applying to several graduate schools this month."],
  ["ch19", "tissue", "科学者たちが、傷を治す助けとなる人工組織を開発した。", ["Scientists", "have", "developed", "an artificial", "tissue", "to help", "heal", "wounds"], "Scientists have developed an artificial tissue to help heal wounds."],
  ["ch19", "container", "刺身のプラスチックの入れ物が、店の棚の上にあります。", ["Plastic", "containers of", "sashimi", "are", "on", "the store", "shelves"], "Plastic containers of sashimi are on the store shelves."],
];

const CORE_QUESTIONS: EnglishQuestion[] = [
  {
    id: "sample-his",
    unit: "exam-sample",
    group: "文法・語形",
    format: "choice",
    prompt: "The team leader evaluated all of his team members on ( ___ ) own.",
    options: ["he", "his", "him", "himself"],
    answer: "his",
    explanation: "on one's own（自分で）のone'sに、主語と対応する所有格hisを入れます。",
  },
  {
    id: "sample-efficiently",
    unit: "exam-sample",
    group: "文法・語形",
    format: "choice",
    prompt: "He works so ( ___ ) that everyone trusts him.",
    options: ["efficient", "efficiency", "efficiently", "more efficient"],
    answer: "efficiently",
    explanation: "動詞worksを修飾するため、副詞efficientlyを選びます。",
  },
  {
    id: "sample-significant",
    unit: "exam-sample",
    group: "文法・語形",
    format: "choice",
    prompt: "The difference between the two results was so ( ___ ).",
    options: ["signify", "significant", "significantly", "significance"],
    answer: "significant",
    explanation: "be動詞の補語には形容詞significant（重要な／かなりの）を置きます。",
  },
  {
    id: "sample-correction",
    unit: "exam-sample",
    group: "誤文訂正",
    format: "input",
    prompt: "誤りを2か所直す：After completing intensive training, sales staff will have to visit them clients by theirs.",
    answer: "them → their / theirs → themselves",
    accepted: ["them to their, theirs to themselves", "them→their theirs→themselves", "their themselves"],
    explanation: "clientsの前は所有格their、by oneself（自分たちで）はby themselvesです。",
  },
  {
    id: "sample-weight",
    unit: "exam-sample",
    group: "語形変化",
    format: "input",
    prompt: "3つの空欄を同じ語の適切な形で埋める：The pendulum (1) 200 tons. / It is a (2) pendulum. / It is 200 tons in (3).",
    answer: "weighs / 200-ton / weight",
    accepted: ["weighs, 200-ton, weight", "weighs 200 ton weight"],
    explanation: "動詞weighs、複合形容詞200-ton、名詞weightを使い分けます。",
  },
  {
    id: "sample-prompted",
    unit: "exam-sample",
    group: "疑問文",
    format: "input",
    prompt: "「何が彼女にこのレビューを書かせたのですか」を英訳する。",
    answer: "What prompted her to write this review?",
    accepted: ["what prompted her to write this review"],
    explanation: "prompt A to doで「Aに～するよう促す」です。What自体が主語なのでdidは不要です。",
  },

  {
    id: "ch15-prep-1",
    unit: "ch15",
    group: "時間・単位",
    format: "choice",
    prompt: "The maintenance engineer works 8 hours ( ___ ) a day.",
    options: ["前置詞なし", "per", "by", "in"],
    answer: "前置詞なし",
    explanation: "a day自体で「1日につき」を表すため前置詞は置きません。",
  },
  {
    id: "ch15-prep-2",
    unit: "ch15",
    group: "時間・単位",
    format: "choice",
    prompt: "The rental fee of the device costs 2,000 yen ( ___ ) week.",
    options: ["前置詞なし", "per", "by", "at"],
    answer: "per",
    explanation: "per + 単位で「～につき」です。",
  },
  {
    id: "ch15-prep-3",
    unit: "ch15",
    group: "時間・単位",
    format: "choice",
    prompt: "The researcher gets paid ( ___ ) the hour.",
    options: ["前置詞なし", "per", "by", "for"],
    answer: "by",
    explanation: "by the hourで「時間単位で」です。",
  },
  {
    id: "ch15-prep-4",
    unit: "ch15",
    group: "時間・単位",
    format: "choice",
    prompt: "This science magazine is published twice ( ___ ) a month.",
    options: ["前置詞なし", "per", "by", "on"],
    answer: "前置詞なし",
    explanation: "twice a monthで「月2回」です。",
  },
  {
    id: "ch15-tf-1",
    unit: "ch15",
    group: "長文 True / False",
    format: "choice",
    prompt: "The main purpose of the article is to introduce a biotechnology company that creates new organisms.",
    options: ["T", "F"],
    answer: "T",
    passageId: "passage-amyris",
  },
  {
    id: "ch15-tf-2",
    unit: "ch15",
    group: "長文 True / False",
    format: "choice",
    prompt: "A new cell can be built by using an iPhone application.",
    options: ["T", "F"],
    answer: "F",
    explanation: "本文は「iPhoneアプリを作るのと同じように」であり、iPhoneアプリを使うとは述べていません。",
    passageId: "passage-amyris",
  },
  {
    id: "ch15-tf-3",
    unit: "ch15",
    group: "長文 True / False",
    format: "choice",
    prompt: "The article says the technology raises ethical and environmental questions.",
    options: ["T", "F"],
    answer: "T",
    passageId: "passage-amyris",
  },
  {
    id: "ch15-summary-1",
    unit: "ch15",
    group: "要約穴埋め",
    format: "choice",
    prompt: "A biotech company has ( ___ ) over 3 million new organisms using computers and robots.",
    options: ["arisen", "been", "become", "created"],
    answer: "created",
  },
  {
    id: "ch15-summary-2",
    unit: "ch15",
    group: "要約穴埋め",
    format: "choice",
    prompt: "The company has ( ___ ) a symbol of a new kind of genetic engineering.",
    options: ["arisen", "been", "become", "created"],
    answer: "become",
  },
  {
    id: "ch15-summary-3",
    unit: "ch15",
    group: "要約穴埋め",
    format: "choice",
    prompt: "There has ( ___ ) criticism concerning the ethics of creating new life forms.",
    options: ["arisen", "been", "become", "created"],
    answer: "been",
  },
  {
    id: "ch15-summary-4",
    unit: "ch15",
    group: "要約穴埋め",
    format: "choice",
    prompt: "Hope has ( ___ ) for a new revolution in the chemical industry.",
    options: ["arisen", "been", "become", "created"],
    answer: "arisen",
  },

  {
    id: "ch16-word-1",
    unit: "ch16",
    group: "語形・文脈",
    format: "choice",
    prompt: "High-tech supercomputers could ( ___ ) each block down to 3.5 kilometers.",
    options: ["map", "narrow", "surface"],
    answer: "narrow",
  },
  {
    id: "ch16-word-2",
    unit: "ch16",
    group: "語形・文脈",
    format: "choice",
    prompt: "The problems started to ( ___ ) in the 1980s.",
    options: ["map", "narrow", "surface"],
    answer: "surface",
  },
  {
    id: "ch16-word-3",
    unit: "ch16",
    group: "語形・文脈",
    format: "input",
    prompt: "mapを適切な形にする：Researchers have ( ___ ) the genome of a spider for the first time.",
    answer: "mapped",
    explanation: "現在完了haveの後なので過去分詞。語尾pを重ねてmappedです。",
  },
  ...[
    ["Scientists are using a supercomputer to help predict the weather.", "T"],
    ["Cloud formations are important to consider when making weather forecasts.", "T"],
    ["There were about 63 billion cloud movements over the Earth's surface.", "F"],
    ["The K computer uses weather information from small areas to predict cloud formations.", "T"],
    ["The system was tested and will be further improved.", "T"],
  ].map(([prompt, answer], index) => ({
    id: `ch16-tf-${index + 1}`,
    unit: "ch16",
    group: "長文 True / False",
    format: "choice" as const,
    prompt,
    options: ["T", "F"],
    answer,
    passageId: "passage-weather",
  })),

  {
    id: "ch18-relative-1",
    unit: "ch18",
    group: "前置詞＋関係代名詞",
    format: "input",
    prompt: "Technologies include a system ( ___ ) which computers recognize users' intentions.",
    answer: "in",
    explanation: "a system in which ...（その中で～するシステム）です。",
  },
  {
    id: "ch18-relative-2",
    unit: "ch18",
    group: "前置詞＋関係代名詞",
    format: "input",
    prompt: "Telecommunication technology ( ___ ) which multiple wheelchairs will be connected enables users to share information.",
    answer: "in",
  },
  {
    id: "ch18-read-1",
    unit: "ch18",
    group: "長文内容理解",
    format: "choice",
    prompt: "The robot wheelchairs detect the users' commands by reading ...",
    options: ["their voices", "their brain waves", "their hands", "their helpers"],
    answer: "their brain waves",
    passageId: "passage-wheelchair",
  },
  {
    id: "ch18-read-2",
    unit: "ch18",
    group: "長文内容理解",
    format: "choice",
    prompt: "During the trial, the wheelchairs succeeded in ...",
    options: ["traveling a long distance", "connecting with each other", "operating home electronic appliances", "receiving information from users"],
    answer: "operating home electronic appliances",
    passageId: "passage-wheelchair",
  },
  {
    id: "ch18-read-3",
    unit: "ch18",
    group: "長文内容理解",
    format: "choice",
    prompt: "According to the article, the wheelchairs will be able to ...",
    options: ["move obstacles", "physically link together", "calculate the cheapest route", "share data concerning uneven paths"],
    answer: "share data concerning uneven paths",
    passageId: "passage-wheelchair",
  },
  {
    id: "ch18-translation-1",
    unit: "ch18",
    group: "和訳",
    format: "choice",
    prompt: "While the graying of Japan's population continues, the ministry expects that robot wheelchairs will be put to practical use in nursing care facilities, where a labor shortage is predicted.",
    options: [
      "日本の高齢化が続く中、総務省は、労働力不足が予想される介護施設でロボット車椅子が実用化されると見込んでいる。",
      "日本の人口が増える中、総務省は介護施設の閉鎖を予想している。",
      "労働力不足が解消したので、車椅子の研究は中止された。",
      "介護施設はロボット車椅子を海外へ輸出する予定である。",
    ],
    answer: "日本の高齢化が続く中、総務省は、労働力不足が予想される介護施設でロボット車椅子が実用化されると見込んでいる。",
    passageId: "passage-wheelchair",
  },
  {
    id: "ch18-translation-2",
    unit: "ch18",
    group: "和訳",
    format: "choice",
    prompt: "In their experiments, wheelchairs have successfully moved short distances and performed simple operations involving home electronic appliances.",
    options: [
      "実験では、車椅子は短距離の移動に成功し、家庭電化製品に関わる簡単な操作を行った。",
      "車椅子は長距離を移動したが、家電の操作には失敗した。",
      "家庭電化製品が車椅子を短距離だけ運んだ。",
      "実験は家庭ではなく研究所だけで行われた。",
    ],
    answer: "実験では、車椅子は短距離の移動に成功し、家庭電化製品に関わる簡単な操作を行った。",
    passageId: "passage-wheelchair",
  },
  {
    id: "ch18-translation-3",
    unit: "ch18",
    group: "和訳",
    format: "choice",
    prompt: "Under the planned system, wheelchairs will calculate current locations and routes to destinations.",
    options: [
      "計画中のシステムでは、車椅子が現在地と目的地までの経路を計算する。",
      "利用者が現在地を忘れた場合だけ目的地を変更する。",
      "計画では目的地の位置を人が毎回入力する。",
      "車椅子は現在地の情報を計算せず共有する。",
    ],
    answer: "計画中のシステムでは、車椅子が現在地と目的地までの経路を計算する。",
    passageId: "passage-wheelchair",
  },
  {
    id: "ch19-abstract-method",
    unit: "ch19",
    group: "Abstract構成",
    format: "choice",
    prompt: "The survey was completed in 2012 and all interviews were conducted over the telephone. この文はAbstractのどの部分か。",
    options: ["① 研究の背景・目的", "② 実験の方法", "③ 実験結果", "④ 結論"],
    answer: "② 実験の方法",
  },
  {
    id: "ch19-abstract-purpose",
    unit: "ch19",
    group: "Abstract構成",
    format: "choice",
    prompt: "The purpose of this study is to examine the effects of indoor heating on pets. この文はAbstractのどの部分か。",
    options: ["① 研究の背景・目的", "② 実験の方法", "③ 実験結果", "④ 結論"],
    answer: "① 研究の背景・目的",
  },
  {
    id: "ch19-meaning-drastically",
    unit: "ch19",
    group: "英→日",
    format: "choice",
    prompt: "drastically の意味を選ぶ。",
    options: ["大幅に", "自動的に", "現在まで", "不正に"],
    answer: "大幅に",
  },
  {
    id: "ch19-meaning-existing",
    unit: "ch19",
    group: "英→日",
    format: "choice",
    prompt: "existing の意味を選ぶ。",
    options: ["既存の", "絶滅した", "実験中の", "悪質な"],
    answer: "既存の",
  },
  {
    id: "ch19-meaning-distinguish",
    unit: "ch19",
    group: "英→日",
    format: "choice",
    prompt: "distinguish の意味を選ぶ。",
    options: ["見分ける、区別する", "蓄積する", "依存する", "発表する"],
    answer: "見分ける、区別する",
  },
  ...[
    ["The ministry plans to ( ___ ) developing robot wheelchairs.", ["share", "connect", "start", "recognize"], "start"],
    ["The wheelchairs ( ___ ) their users' commands and move automatically.", ["share", "connect", "start", "recognize"], "recognize"],
    ["The ministry aims to ( ___ ) multiple wheelchairs using networks.", ["share", "connect", "start", "recognize"], "connect"],
    ["Networks enable users to ( ___ ) information about dangerous places.", ["share", "connect", "start", "recognize"], "share"],
  ].map(([prompt, options, answer], index) => ({
    id: `ch18-summary-${index + 1}`,
    unit: "ch18",
    group: "要約穴埋め",
    format: "choice" as const,
    prompt: prompt as string,
    options: options as string[],
    answer: answer as string,
  })),
  ...[
    ["And ( ___ ) long did you test the ThinkChair for?", "how"],
    ["As a wheelchair user, ( ___ ) did you think about the ThinkChair?", "what"],
    ["( ___ ) did you experience these problems? — Mostly at the beginning.", "when"],
    ["But you said it was quite good. ( ___ )? — Because it showed the shortest route.", "why"],
  ].map(([prompt, answer], index) => ({
    id: `ch18-interview-${index + 1}`,
    unit: "ch18",
    group: "疑問詞",
    format: "input" as const,
    prompt,
    answer,
  })),

  ...[
    ["families", "family"],
    ["species", "species"],
    ["fungi", "fungus"],
    ["genera", "genus"],
  ].map(([prompt, answer], index) => ({
    id: `ch19-singular-${index + 1}`,
    unit: "ch19",
    group: "単数形",
    format: "input" as const,
    prompt: `次の語を単数形にする：${prompt}`,
    answer,
  })),
  ...[
    ["The main purpose of this article is to warn customers about food fraud.", "F"],
    ["The software compares DNA sequences from a database with those from actual food.", "T"],
    ["Mislabeled food is easier to find with the new software.", "T"],
    ["The family of a new species can also be detected with this software.", "T"],
    ["Until now, only experts from Japan, the U.S. and Europe could identify unknown organisms.", "F"],
  ].map(([prompt, answer], index) => ({
    id: `ch19-tf-${index + 1}`,
    unit: "ch19",
    group: "長文 True / False",
    format: "choice" as const,
    prompt,
    options: ["T", "F"],
    answer,
    passageId: "passage-dna",
  })),
  ...[
    ["The software can detect ( ___ ) labeled foods.", "incorrectly"],
    ["It compares actual DNA sequences to sequences ( ___ ) stored in databases.", "already"],
    ["The software ( ___ ) detects the species of the product.", "automatically"],
    ["The process has ( ___ ) depended on experts' knowledge and experience.", "commonly"],
  ].map(([prompt, answer], index) => ({
    id: `ch19-summary-${index + 1}`,
    unit: "ch19",
    group: "要約穴埋め",
    format: "choice" as const,
    prompt,
    options: ["automatically", "already", "incorrectly", "commonly"],
    answer,
  })),
  ...[
    ["Today is Tuesday and you want to know about the weather for the whole of Japan on the weekend.", "National weather / Weekly forecast"],
    ["You want to know how much sun protection you will need today.", "Weather data / UV index"],
    ["You want to know more about a blizzard that your friends told you about.", "Weather warnings / Snow"],
    ["Today is Friday and you want to know about the weather in your area tomorrow.", "Regional weather / 3-day forecast"],
    ["You want to know about today's air quality.", "Weather data / Air pollution"],
  ].map(([prompt, answer], index) => ({
    id: `ch16-homepage-${index + 1}`,
    unit: "ch16",
    group: "情報検索",
    format: "choice" as const,
    prompt,
    options: [
      "National weather / Weekly forecast",
      "Regional weather / 3-day forecast",
      "Weather data / UV index",
      "Weather data / Air pollution",
      "Weather warnings / Snow",
    ],
    answer,
  })),
];

const VOCAB_QUESTIONS: EnglishQuestion[] = ENGLISH_VOCAB.map((card) => ({
  id: `question-${card.id}`,
  unit: card.unit,
  group: "語彙・熟語（日→英）",
  format: "input",
  prompt: `「${card.ja}」を英語で答える。`,
  answer: card.en,
  accepted: card.en.split(/\s*\/\s*/).map((answer) => answer.trim()),
  explanation: card.note,
}));

const BUILT_ORDER_QUESTIONS: EnglishQuestion[] = ORDER_QUESTIONS.map(
  ([unit, keyword, prompt, tokens, answer], index) => ({
    id: `order-${String(index + 1).padStart(2, "0")}`,
    unit,
    group: `語順整序｜${keyword}`,
    format: "order",
    prompt,
    tokens,
    answer,
  }),
);

const PASSAGE_TRANSLATION_QUESTIONS: EnglishQuestion[] = ENGLISH_PASSAGES.flatMap((passage) =>
  passage.paragraphs.map((paragraph, index) => ({
    id: `${passage.id}-translation-${index + 1}`,
    unit: passage.unit,
    group: "長文和訳",
    format: "translation" as const,
    prompt: `次の英文を自然な日本語に訳す：${paragraph.en}`,
    answer: paragraph.ja,
    explanation: `主語・動作・修飾関係を押さえた模範訳です。表現が異なっても、本文の重要な情報が合っていれば正解として扱います。`,
    passageId: passage.id,
  })),
);

export const ENGLISH_QUESTIONS: EnglishQuestion[] = [
  ...CORE_QUESTIONS,
  ...BUILT_ORDER_QUESTIONS,
  ...VOCAB_QUESTIONS,
  ...PASSAGE_TRANSLATION_QUESTIONS,
].filter((question) => question.unit !== "exam-sample");
