import {
  ENGLISH_ESSENTIALS,
  MECHANICAL_ESSENTIALS,
  NETWORK_ESSENTIALS,
  type EssentialSubject,
} from "./essentials-data";
import {
  MATERIAL_ESSENTIALS,
  SMART_CONTROL_ESSENTIALS,
  THERMODYNAMICS_ESSENTIALS,
} from "./essentials-engineering-data";
import {
  APPLIED_MATH_ESSENTIALS,
  DIGITAL_CIRCUIT_ESSENTIALS,
  STATISTICS_ESSENTIALS,
} from "./essentials-math-data";

export type { EssentialKind } from "./essentials-data";

export const ESSENTIAL_SUBJECTS: EssentialSubject[] = [
  {
    id: "subject-2",
    order: 1,
    name: "英語",
    englishName: "ENGLISH",
    accent: "#c7ff5e",
    examDate: "2026-07-28",
    examDateLabel: "7/28",
    description: "Chapter 14・15・16・18、TOEIC Reading、Housing・Medicalから、語彙・文法・本文根拠に直結する項目だけを選定。Chapter 14のWhat's new?欄とChapter 19は含みません。",
    items: ENGLISH_ESSENTIALS,
  },
  {
    id: "network",
    order: 2,
    name: "ネットワーク",
    englishName: "NETWORK",
    accent: "#55dde0",
    examDate: "2026-07-28",
    examDateLabel: "7/28",
    description: "手書き資料の①〜⑦を基準に、層・正式名称・働きを同時に即答するための最重要プロトコル群。",
    items: NETWORK_ESSENTIALS,
  },
  {
    id: "subject-3",
    order: 3,
    name: "機械力学",
    englishName: "MECHANICAL DYNAMICS",
    accent: "#ff5c35",
    examDate: "2026-07-29",
    examDateLabel: "7/29",
    description: "自由振動、等価剛性、減衰、ラプラス、対数減衰率、回転系を本番の計算手順へつなぐ公式。",
    items: MECHANICAL_ESSENTIALS,
  },
  {
    id: "subject-4",
    order: 4,
    name: "熱・流体力学",
    englishName: "THERMO / FLUID",
    accent: "#a88bff",
    examDate: "2026-07-29",
    examDateLabel: "7/29",
    description: "断熱・ポリトロープ・第二法則・エントロピー・オットー・カルノー・冷凍機COPを、状態変化の見分け方とセットで整理。",
    items: THERMODYNAMICS_ESSENTIALS,
  },
  {
    id: "subject-5",
    order: 5,
    name: "材料力学",
    englishName: "MATERIAL MECHANICS",
    accent: "#ffd65c",
    examDate: "2026-07-30",
    examDateLabel: "7/30",
    description: "範囲ZIP13ページの丸軸ねじり・軸設計・コイルばね・はり反力・SFD・BMDに加え、曲げ応力、長方形・中空円断面のI・Z、単純支持・片持ちばりの標準荷重パターンを整理。EIによるたわみ、曲率、カスティリアーノの定理は対象外。",
    items: MATERIAL_ESSENTIALS,
  },
  {
    id: "subject-6",
    order: 6,
    name: "スマート制御",
    englishName: "SMART CONTROL",
    accent: "#ff8fc7",
    examDate: "2026-07-30",
    examDateLabel: "7/30",
    description: "伝達関数、逆ラプラス、極・安定性、フィードバックに加え、教科書赤字の応答指標とグラフ数値を収録。",
    items: SMART_CONTROL_ESSENTIALS,
  },
  {
    id: "subject-7",
    order: 7,
    name: "確率統計",
    englishName: "PROBABILITY / STATISTICS",
    accent: "#66e39e",
    examDate: "2026-07-31",
    examDateLabel: "7/31",
    description: "12種想定試験で実際に使う代表値・確率・分布・相関の式を網羅。Σを使う式にはΣなしの展開形も併記。",
    items: STATISTICS_ESSENTIALS,
  },
  {
    id: "subject-8",
    order: 8,
    name: "応用数学",
    englishName: "APPLIED MATHEMATICS",
    accent: "#7aa7ff",
    examDate: "2026-07-31",
    examDateLabel: "7/31",
    description: "ベクトルからgrad・div・curl、線積分・面積分・グリーンの定理まで、向きと符号を含めた最短確認。",
    items: APPLIED_MATH_ESSENTIALS,
  },
  {
    id: "subject-9",
    order: 9,
    name: "デジタル回路",
    englishName: "DIGITAL CIRCUITS",
    accent: "#ff9f68",
    examDate: "2026-08-03",
    examDateLabel: "8/3",
    description: "ゲート、ラッチ、D/JK-FF、レジスタ、カウンタ、状態表・状態図・1001系列検出の必須規則。",
    items: DIGITAL_CIRCUIT_ESSENTIALS,
  },
];
