import type { SubjectId } from "./study-data";

// v3 is deliberately pinned to explicit IDs. Adding or reordering bank entries
// cannot silently change a live leaderboard; a future set must bump the version.
export const OFFICIAL_RANKING_QUESTION_IDS = Object.freeze({
  "subject-2": [
    "rapid-exam-ch14-tf-1",
    "rapid-exam-ch14-summary-1",
    "rapid-exam-toeic-keller-181",
    "rapid-exam-toeic-eston-135",
    "rapid-exam-question-ev-199",
    "rapid-exam-exam-level-english-expected-01-q09-toeic-part5-104",
    "rapid-exam-exam-level-english-expected-01-q13-ch14-summary-1",
    "rapid-exam-exam-level-english-expected-01-q17-passage-order-ch14-1",
    "rapid-exam-exam-level-english-expected-01-q23-ch14-tf-1",
    "rapid-exam-exam-level-english-expected-01-q29-toeic-keller-181",
    "rapid-exam-exam-level-english-expected-01-q32-passage-big-battery-translation-1",
    "rapid-exam-exam-level-english-expected-02-q09-ch16-extra-map",
    "rapid-exam-exam-level-english-expected-02-q13-ch14-summary-2",
    "rapid-exam-exam-level-english-expected-02-q17-passage-order-ch14-2",
    "rapid-exam-exam-level-english-expected-02-q23-ch14-tf-2",
    "rapid-exam-exam-level-english-expected-02-q29-toeic-keller-182",
    "rapid-exam-exam-level-english-expected-02-q32-passage-big-battery-translation-2",
    "rapid-exam-question-ev-214",
    "rapid-exam-exam-level-english-expected-03-q29-toeic-keller-183",
    "rapid-exam-exam-level-english-expected-03-q32-passage-big-battery-translation-3",
  ],
  network: [
    "rapid-l1-1000base-t",
    "rapid-l1-ieee-802-11ax",
    "rapid-l1-bluetooth",
    "rapid-l1-zigbee",
    "rapid-l1-twisted-pair-cable",
    "rapid-l1-optical-fiber",
    "rapid-l2-arp",
    "rapid-l2-garp",
    "rapid-l2-ppp",
    "rapid-l2-pap",
    "rapid-l2-chap",
    "rapid-l2-pppoe",
    "rapid-l2-radius",
    "rapid-l2-l2tp",
    "rapid-l3-ipv4",
    "rapid-l3-ipv6",
    "rapid-l3-icmp",
    "rapid-l3-ndp",
    "rapid-l3-dhcp",
    "rapid-l3-rip",
    "rapid-l3-ospf",
    "rapid-l3-eigrp",
    "rapid-l3-bgp",
    "rapid-l3-ipsec",
    "rapid-l3-pptp",
    "rapid-l3-openflow",
    "rapid-l4-tcp",
    "rapid-l4-udp",
    "rapid-l5-sip",
    "rapid-l5-rtsp",
    "rapid-l6-ssl-tls",
    "rapid-l6-alpn",
    "rapid-l6-quic",
    "rapid-l7-http",
    "rapid-l7-https",
    "rapid-l7-dns",
    "rapid-l7-smtp",
    "rapid-l7-pop3",
    "rapid-l7-imap4",
    "rapid-l7-ssh",
    "rapid-l7-telnet",
    "rapid-l7-ftp",
    "rapid-l7-tftp",
    "rapid-l7-snmp",
    "rapid-l7-ntp",
    "rapid-l7-cdp",
    "rapid-l7-lldp",
    "rapid-l7-stp",
    "rapid-l7-vrrp",
    "rapid-l7-hsrp",
  ],
  "subject-3": [
    "rapid-exam-md-expected-5-m6-s1", "rapid-exam-md-expected-5-m7-s1",
    "rapid-exam-md-expected-2-m6-s1", "rapid-exam-md-q-d6", "rapid-exam-md-q-s3",
    "rapid-exam-md-expected-3-m4-s1", "rapid-exam-md-expected-4-m1-s2",
    "rapid-exam-md-expected-4-m4-s1", "rapid-exam-md-expected-1-m6-s1",
    "rapid-exam-md-expected-2-m3-s1", "rapid-exam-md-expected-4-m6-s1",
    "rapid-exam-md-expected-6-m3-s3", "rapid-exam-md-expected-2-m5-s1",
    "rapid-exam-md-expected-1-m4-s1", "rapid-exam-md-expected-1-m6-s3",
    "rapid-exam-md-practice-actual-m6-s1", "rapid-exam-md-expected-3-m1-s3",
    "rapid-exam-md-q-r3", "rapid-exam-md-expected-2-m2-s1", "rapid-exam-md-expected-2-m6-s2",
  ],
  "subject-4": [
    "rapid-exam-thermo-expected-03-m3-q1", "rapid-exam-thermo-expected-05-m1-q2",
    "rapid-exam-thermo-expected-04-m5-q4", "rapid-exam-thermo-expected-02-m1-q1",
    "rapid-exam-thermo-expected-01-m5-q4", "rapid-exam-thermo-expected-06-m3-q2",
    "rapid-exam-thermo-expected-04-m4-q1", "rapid-exam-thermo-expected-06-m5-q2",
    "rapid-exam-thermo-expected-05-m3-q2", "rapid-exam-thermo-expected-04-m3-q2",
    "rapid-exam-th-q-poly-temperature", "rapid-exam-thermo-expected-03-m5-q4",
    "rapid-exam-thermo-expected-01-m1-q1", "rapid-exam-thermo-expected-04-m2-q2",
    "rapid-exam-thermo-expected-03-m4-q1", "rapid-exam-thermo-expected-05-m5-q1",
    "rapid-exam-thermo-expected-02-m3-q2", "rapid-exam-thermo-expected-06-m4-q4",
    "rapid-exam-thermo-expected-06-m2-q1", "rapid-exam-thermo-expected-05-m5-q4",
  ],
  "subject-5": [
    "rapid-exam-material-print-e1-m2", "rapid-exam-material-print-e1-m3", "rapid-exam-material-print-e1-m4",
    "rapid-exam-material-print-e2-m2", "rapid-exam-material-print-e2-m4", "rapid-exam-material-print-e2-m5",
    "rapid-exam-material-print-e3-m2", "rapid-exam-material-print-e3-m3", "rapid-exam-material-print-e3-m5",
    "rapid-exam-material-print-e4-m3", "rapid-exam-material-print-e4-m4",
    "rapid-exam-material-print-e5-m2", "rapid-exam-material-print-e5-m4", "rapid-exam-material-print-e5-m5",
    "rapid-exam-material-print-e6-m3", "rapid-exam-material-print-e6-m5",
    "rapid-exam-mm-q-supplement-q2-straight-beam", "rapid-exam-mm-q-supplement-q5-pin-support",
    "rapid-exam-mm-q-supplement-q7-concentrated-load", "rapid-exam-mm-q-supplement-q10-cantilever-wording",
  ],  "subject-6": [
    "rapid-exam-smart-exam-3-q1", "rapid-exam-textbook-response-q17-symbol-map",
    "rapid-exam-textbook-response-q22-normalized-comparison", "rapid-exam-smart-q-response-2",
    "rapid-exam-smart-q-response-7", "rapid-exam-smart-q-transfer-3",
    "rapid-exam-textbook-response-q05-delay-time", "rapid-exam-smart-exam-3-q4",
    "rapid-exam-textbook-response-q09-damping", "rapid-exam-smart-q-inverse-5",
    "rapid-exam-smart-q-transfer-2", "rapid-exam-textbook-response-q06-rapidity",
    "rapid-exam-smart-exam-6-q4", "rapid-exam-smart-q-inverse-8",
    "rapid-exam-smart-q-feedback-4", "rapid-exam-smart-q-response-5",
    "rapid-exam-textbook-response-q21-no-overshoot", "rapid-exam-smart-q-response-4",
    "rapid-exam-textbook-response-q04-rise-time", "rapid-exam-smart-exam-6-q1",
  ],
  "subject-7": [
    "rapid-exam-stats-ex1-blood-slope", "rapid-exam-expected-01-m07-s2",
    "rapid-exam-stats-ex4-normal-negative-interval", "rapid-exam-expected-02-m02-s2",
    "rapid-exam-stats-ex1-blood-correlation", "rapid-exam-stats-ex2-score-one",
    "rapid-exam-expected-06-m03-s3", "rapid-exam-expected-10-m01-s6",
    "rapid-exam-expected-09-m03-s3", "rapid-exam-expected-03-m03-s3",
    "rapid-exam-stats-ex2-bags-even-black", "rapid-exam-expected-10-m04-s1",
    "rapid-exam-expected-08-m03-s4", "rapid-exam-expected-12-m08-s1",
    "rapid-exam-stats-ex2-bags-same-color", "rapid-exam-expected-11-m11-s1",
    "rapid-exam-expected-02-m03-s2", "rapid-exam-expected-08-m03-s2",
    "rapid-exam-expected-03-m07-s3", "rapid-exam-expected-10-m05-s1",
  ],
  "subject-8": [
    "rapid-exam-applied-expected-04-m4-s3", "rapid-exam-applied-expected-06-m5-s3",
    "rapid-exam-am-q-source-directional", "rapid-exam-am-q-source-paraboloid-area",
    "rapid-exam-applied-expected-02-m3-s3", "rapid-exam-applied-expected-02-m6-s2",
    "rapid-exam-applied-expected-02-m6-s1", "rapid-exam-applied-expected-05-m4-s3",
    "rapid-exam-applied-expected-05-m3-s1", "rapid-exam-applied-expected-03-m5-s4",
    "rapid-exam-applied-expected-01-m5-s1", "rapid-exam-applied-expected-02-m5-s2",
    "rapid-exam-am-q-green-square", "rapid-exam-applied-expected-03-m4-s3",
    "rapid-exam-applied-expected-06-m1-s3", "rapid-exam-am-q-cross-product-rule",
    "rapid-exam-applied-expected-05-m2-s2", "rapid-exam-applied-expected-06-m6-s4",
    "rapid-exam-applied-expected-02-m4-s3", "rapid-exam-applied-expected-06-m6-s1",
  ],
  "subject-9": [
    "rapid-exam-dc-q-count-down", "rapid-exam-dc-expected-4-dc-extra-q-sequence-stream-m5s2",
    "rapid-exam-dc-expected-2-dc-extra-q-sequence-stream-m5s2",
    "rapid-exam-dc-expected-2-dc-q-sr-forbid-m2s2", "rapid-exam-dc-q-reg-value",
    "rapid-exam-dc-extra-q-sequence-state", "rapid-exam-dc-expected-6-dc-extra-q-cycle-design-m4s2",
    "rapid-exam-dc-expected-4-dc-q-sr-forbid-m2s1", "rapid-exam-dc-extra-q-ex3-equation",
    "rapid-exam-dc-expected-6-dc-q-count-ripple-m4s3", "rapid-exam-dc-expected-1-dc-q-and-seq-m1s1",
    "rapid-exam-dc-extra-q-sequence-output", "rapid-exam-dc-expected-6-dc-extra-q-ex3-equation-m5s1",
    "rapid-exam-dc-expected-4-dc-q-or-seq-m1s1", "rapid-exam-dc-expected-3-dc-q-reg-hold-m3s2",
    "rapid-exam-dc-expected-2-dc-q-reg-hold-m3s2", "rapid-exam-dc-expected-3-dc-extra-q-past-full-table-m5s1",
    "rapid-exam-dc-extra-q-cycle-states", "rapid-exam-dc-expected-1-dc-extra-q-ex3-equation-m5s1",
    "rapid-exam-dc-expected-3-dc-extra-q-sequence-output-m5s2",
  ],
} as const satisfies Record<SubjectId, readonly string[]>);
