import type {
  SmartControlCard,
  SmartControlQuestion,
} from "./smart-control-data";

/**
 * 教科書 p.65-68（講義05「システムの応答特性」）専用。
 *
 * SmartControlQuestion の source は元データ作成時点では
 * "scope-zip" | "past2-overlap" に限定されているため、教科書由来であることを
 * 偽らず保持できるよう source だけをローカルで拡張している。
 */
export type TextbookResponseQuestion = Omit<SmartControlQuestion, "source"> & {
  source: "textbook-p65-68";
};

export const TEXTBOOK_RESPONSE_CARDS: SmartControlCard[] = [
  {
    id: "textbook-response-steady-characteristic",
    topic: "response-stability",
    title: "定常特性",
    prompt: "定常特性（steady state characteristic）とは何を表す？",
    formula: "\\lim_{t\\to\\infty}y(t)=y_\\infty",
    explanation:
      "十分に時間が経過した後、応答がある値付近へ収束するか、収束するならどの値へ収束するかというシステム固有の性質。図5.1では過渡部分の後、応答が定常値付近に落ち着いた領域を『定常特性』として示している。",
    cue: "最後に落ち着くか・どこへ落ち着くか",
    example:
      "単位ステップ入力でも定常値が必ず1になるわけではなく、システムの特性によって決まる。",
  },
  {
    id: "textbook-response-transient-characteristic",
    topic: "response-stability",
    title: "過渡特性",
    prompt: "過渡特性（transient characteristic）とは何を表す？",
    formula: "y(0)\\longrightarrow y_\\infty",
    explanation:
      "初期値から最終的な状態へ至るまでに、応答がどのような波形・過程をたどるかというシステム固有の性質。速さ、行き過ぎ、振動の収まり方などを応答波形から調べる。",
    cue: "開始から定常状態へ至る途中の形",
  },
  {
    id: "textbook-response-steady-value",
    topic: "response-stability",
    title: "定常値",
    prompt: "定常値（steady-state value）\\(y_\\infty\\) の定義は？",
    formula: "y_\\infty=\\lim_{t\\to\\infty}y(t)",
    explanation:
      "ステップ入力に対する応答が最終的に収束する値。値はシステムの特性に依存し、一般に1とは限らない。発散して一定値へ収束しない場合は、定常値という言葉を用いないのが一般的。",
    cue: "tを無限大へ送ったときのy(t)",
  },
  {
    id: "textbook-response-transient-steady-boundary",
    topic: "response-stability",
    title: "図5.1の2領域",
    prompt: "図5.1で『過渡特性』と『定常特性』をどう見分ける？",
    formula: "\\text{過渡領域}\\;\\longrightarrow\\;\\text{定常領域}",
    explanation:
      "立ち上がり・最大値・振動・整定までが過渡領域で、その後に定常値付近へ落ち着いている部分が定常領域。境目は単なる最初の交差ではなく、許容帯内へ入り、その後出なくなる整定の考え方で読む。",
    cue: "整定前が過渡、整定後が定常",
  },
  {
    id: "textbook-response-rise-time",
    topic: "response-stability",
    title: "立ち上がり時間",
    prompt: "立ち上がり時間（rise time）\\(t_r\\) はどこからどこまで？",
    formula: "t_r=t_{90}-t_{10}",
    explanation:
      "応答が定常値の10%に初めて達してから90%に初めて達するまでの時間。図5.1では \\(0.1y_\\infty\\) と \\(0.9y_\\infty\\) の交点間を横軸上で測る。",
    cue: "10% → 90%",
    example:
      "10%到達が0.2 s、90%到達が0.8 sなら、\\(t_r=0.6\\,\\mathrm{s}\\)。",
  },
  {
    id: "textbook-response-rapidity",
    topic: "response-stability",
    title: "速応性",
    prompt: "速応性とは何を評価し、どの指標で見る？",
    formula: "t_r\\downarrow\\;\\Rightarrow\\;\\text{速応性}\\uparrow",
    explanation:
      "入力値の変化に反応して、出力がどの程度早く定常値へ向かうかを評価する性質。主に立ち上がり時間 \\(t_r\\) や遅れ時間 \\(t_d\\) で見て、これらが小さいほど速応性が高い。",
    cue: "反応の早さ。tr・tdが小さいほど高い",
  },
  {
    id: "textbook-response-delay-time",
    topic: "response-stability",
    title: "遅れ時間",
    prompt: "遅れ時間（delay time）\\(t_d\\) はどこまでの時間？",
    formula: "y(t_d)=0.5y_\\infty",
    explanation:
      "応答が初期値0から定常値の50%に初めて達するまでの時間。立ち上がり時間とほぼ同義の速応性指標だが、\\(t_d\\) は0から50%、\\(t_r\\) は10%から90%なので定義を混同しない。",
    cue: "0 → 50%",
  },
  {
    id: "textbook-response-overshoot",
    topic: "response-stability",
    title: "オーバーシュート（行き過ぎ量）",
    prompt: "オーバーシュート \\(O_s\\) は何を表す？",
    formula: "O_s=\\frac{y_{\\max}-y_\\infty}{y_\\infty}\\times100\\%",
    explanation:
      "応答の最大値 \\(y_{\\max}\\) が定常値 \\(y_\\infty\\) をどれだけ上回ったかを、定常値に対する百分率で表したもの。図5.1の縦の差だけでなく、必ず \\(y_\\infty\\) で割って正規化する。",
    cue: "（最大値−定常値）÷定常値×100%",
  },
  {
    id: "textbook-response-peak-time",
    topic: "response-stability",
    title: "行き過ぎ時間",
    prompt: "行き過ぎ時間（peak time）\\(t_p\\) の定義は？",
    formula: "y(t_p)=y_{\\max}",
    explanation:
      "ステップ応答が最大値 \\(y_{\\max}\\) に達する時刻。図5.1では最初の山の頂点から時間軸へ下ろした位置であり、最大値そのものではなく『その時刻』を答える。",
    cue: "最大の山に達した時刻",
  },
  {
    id: "textbook-response-damping",
    topic: "response-stability",
    title: "減衰性",
    prompt: "減衰性とは何を評価する性質？",
    formula: "O_s\\downarrow,\\;t_s\\downarrow\\;\\Rightarrow\\;\\text{減衰性が高い}",
    explanation:
      "入力値の変化に対応して生じる振動現象が、どの程度すみやかに収束するかを評価する性質。オーバーシュートが大きいほど振動が長く続きやすく、整定時間も遅くなりやすい。",
    cue: "振動の収まりやすさ",
  },
  {
    id: "textbook-response-settling-time",
    topic: "response-stability",
    title: "整定時間",
    prompt: "整定時間（settling time）\\(t_s\\) の定義は？",
    formula: "0.95y_\\infty\\le y(t)\\le1.05y_\\infty\\quad(t\\ge t_s)",
    explanation:
      "応答が定常値の±5%以内へ入り、その後その区間からはみ出さなくなる時刻。最初に許容帯へ入った時刻ではなく、最後に帯へ入って以後ずっと残る時刻である。",
    cue: "±5%帯へ最後に入り、以後出ない時刻",
  },
  {
    id: "textbook-response-graph-levels",
    topic: "response-stability",
    title: "図5.1の基準高さ",
    prompt: "図5.1で暗記する縦軸の基準値を下から並べると？",
    formula: "0.1y_\\infty,\\;0.5y_\\infty,\\;0.9y_\\infty,\\;y_\\infty,\\;y_{\\max}",
    explanation:
      "10%と90%は立ち上がり時間、50%は遅れ時間、\\(y_\\infty\\) は定常値、\\(y_{\\max}\\) は最大値を読むための高さ。許容帯の0.95倍・1.05倍は定常値のすぐ下と上に別途置かれる。",
    cue: "0.1・0.5・0.9・1.0・最大",
  },
  {
    id: "textbook-response-five-percent-band",
    topic: "response-stability",
    title: "±5%許容帯",
    prompt: "定常値 \\(y_\\infty\\) の±5%帯の上下限は？",
    formula: "0.95y_\\infty\\le y(t)\\le1.05y_\\infty",
    explanation:
      "下限は95%、上限は105%。図5.1〜5.3ではこの2本の線で整定を判定し、応答が最後に帯へ入る位置が \\(t_s\\) になる。",
    cue: "下95%、上105%",
  },
  {
    id: "textbook-response-figure-51-map",
    topic: "response-stability",
    title: "図5.1 記号マップ",
    prompt: "図5.1の \\(t_d,t_r,t_p,t_s,O_s\\) を一息で対応させると？",
    formula: "t_d:50\\%,\\quad t_r:10\\to90\\%,\\quad t_p:y_{\\max},\\quad t_s:\\pm5\\%,\\quad O_s:\\text{行き過ぎ率}",
    explanation:
      "横軸の時刻・区間は \\(t_d,t_r,t_p,t_s\\)、縦方向の最大値と定常値の差を百分率化したものが \\(O_s\\)。\\(t_r\\) だけは0からの時刻ではなく10%から90%までの『差』である。",
    cue: "50／10→90／最大時刻／±5%／最大超過率",
  },
  {
    id: "textbook-response-figure-52",
    topic: "response-stability",
    title: "図5.2 曲線比較",
    prompt: "オーバーシュートがない図5.2で、\\(y_a,y_b,y_c\\) の速応性と整定時間の順は？",
    formula: "\\text{速応性}:y_a>y_b>y_c,\\qquad t_s(y_a)<t_s(y_b)<t_s(y_c)",
    explanation:
      "青の \\(y_a(t)\\) が最も急に立ち上がり最初に±5%帯へ入り、\\(y_b(t)\\)、赤の \\(y_c(t)\\) の順に遅い。オーバーシュートがない場合、速応性が低いほど整定時間も遅くなる。",
    cue: "図5.2は aが最速、cが最遅",
  },
  {
    id: "textbook-response-figure-53",
    topic: "response-stability",
    title: "図5.3 曲線比較",
    prompt: "図5.3でオーバーシュートが大きくなると、整定時間はどうなる？",
    formula: "O_s(y_a)<O_s(y_b)<O_s(y_c)\\;\\Rightarrow\\;t_s(y_a)<t_s(y_b)<t_s(y_c)",
    explanation:
      "\\(y_a(t)\\) は行き過ぎが小さく早く整定し、\\(y_b(t)\\) は中間、赤の \\(y_c(t)\\) は大きく振動して整定が最も遅い。速く立ち上がっても行き過ぎが過大なら、振動が収まりにくく整定は遅れる。",
    cue: "図5.3は行き過ぎ大 → 振動長い → ts遅い",
  },
  {
    id: "textbook-response-no-overshoot-caution",
    topic: "response-stability",
    title: "オーバーシュートの注意",
    prompt: "すべてのシステムにオーバーシュートが生じる？",
    formula: "O_s=0\\%\\quad\\text{となる応答もある}",
    explanation:
      "生じるとは限らない。図5.2のように定常値へ単調に近づく応答では、最大値が定常値を上回らず、オーバーシュートは生じない。",
    cue: "単調応答なら行き過ぎなし",
  },
  {
    id: "textbook-response-normalized-overshoot",
    topic: "response-stability",
    title: "行き過ぎ量は割合で比較",
    prompt: "定常値が異なる2曲線の行き過ぎを公平に比べるには？",
    formula: "O_s=\\frac{y_{\\max}-y_\\infty}{y_\\infty}\\times100\\%",
    explanation:
      "単なる差 \\(y_{\\max}-y_\\infty\\) ではなく、その差を各曲線の定常値で割った百分率 \\(O_s\\) を比較する。定常値が違っても相対的な行き過ぎを比べられる。",
    cue: "差だけでなく定常値で割る",
  },
];

export const TEXTBOOK_RESPONSE_QUESTIONS: TextbookResponseQuestion[] = [
  {
    id: "textbook-response-q01-steady-characteristic",
    topic: "response-stability",
    genre: "赤文字・定義",
    difficulty: 1,
    format: "choice",
    prompt: "『十分な時間の後に応答が収束するか、収束するならどの値か』を表す性質は？",
    answer: "定常特性",
    options: ["定常特性", "過渡特性", "速応性", "減衰性"],
    formula: "\\lim_{t\\to\\infty}y(t)=y_\\infty",
    steps: [
      "問題文の『十分な時間の後』に注目する。",
      "最終的な収束の有無と収束先を扱うので定常特性と判断する。",
    ],
    explanation:
      "過渡特性は初期値から最終状態へ至る途中の波形、速応性は反応の早さ、減衰性は振動の収まり方を表す。",
    source: "textbook-p65-68",
  },
  {
    id: "textbook-response-q02-transient-characteristic",
    topic: "response-stability",
    genre: "赤文字・定義",
    difficulty: 1,
    format: "choice",
    prompt: "初期値 \\(y(0)\\) から定常値へ至る過程の波形に関する性質は？",
    answer: "過渡特性",
    options: ["過渡特性", "定常特性", "定常値", "行き過ぎ時間"],
    formula: "y(0)\\longrightarrow y_\\infty",
    steps: [
      "『初期値から定常値へ至る過程』という範囲を確認する。",
      "途中の応答波形を扱う性質なので過渡特性を選ぶ。",
    ],
    explanation:
      "定常特性はその過程が終わった後の収束を扱う。図5.1では整定前の領域が過渡特性、整定後が定常特性である。",
    source: "textbook-p65-68",
  },
  {
    id: "textbook-response-q03-steady-value",
    topic: "response-stability",
    genre: "赤文字・数式",
    difficulty: 1,
    format: "text",
    prompt: "定常値 \\(y_\\infty\\) を極限で定義せよ。",
    answer: "\\(y_\\infty=\\lim_{t\\to\\infty}y(t)\\)",
    accepted: ["y∞=lim(t→∞)y(t)", "lim t→∞ y(t)", "lim y(t)"],
    keywords: ["lim", "∞", "y"],
    minKeywords: 3,
    formula: "y_\\infty=\\lim_{t\\to\\infty}y(t)",
    steps: [
      "時間を十分経過させるので \\(t\\to\\infty\\) と置く。",
      "そのときの応答 \\(y(t)\\) の極限を \\(y_\\infty\\) と定義する。",
    ],
    explanation:
      "単位ステップ入力だから定常値も1、と決めつけてはいけない。値はシステムに依存し、発散する場合には定常値は定義できない。",
    source: "textbook-p65-68",
  },
  {
    id: "textbook-response-q04-rise-time",
    topic: "response-stability",
    genre: "図5.1・記号",
    difficulty: 1,
    format: "choice",
    prompt: "立ち上がり時間 \\(t_r\\) の正しい定義は？",
    answer: "\\(0.1y_\\infty\\) から \\(0.9y_\\infty\\) まで",
    options: [
      "\\(0.1y_\\infty\\) から \\(0.9y_\\infty\\) まで",
      "0から \\(0.5y_\\infty\\) まで",
      "0から \\(y_{\\max}\\) まで",
      "±5%帯へ最後に入るまで",
    ],
    formula: "t_r=t_{90}-t_{10}",
    steps: [
      "定常値の10%の初回到達時刻を \\(t_{10}\\) とする。",
      "90%の初回到達時刻 \\(t_{90}\\) との差を取る。",
    ],
    explanation:
      "0から50%までは遅れ時間 \\(t_d\\)、最大値に達する時刻は \\(t_p\\)、±5%帯で判定するのは \\(t_s\\) である。",
    source: "textbook-p65-68",
  },
  {
    id: "textbook-response-q05-delay-time",
    topic: "response-stability",
    genre: "図5.1・記号",
    difficulty: 1,
    format: "choice",
    prompt: "遅れ時間 \\(t_d\\) の終点となる応答値は？",
    answer: "\\(0.5y_\\infty\\)",
    options: ["\\(0.5y_\\infty\\)", "\\(0.1y_\\infty\\)", "\\(0.9y_\\infty\\)", "\\(y_{\\max}\\)"],
    formula: "y(t_d)=0.5y_\\infty",
    steps: [
      "遅れ時間は初期値0から測る。",
      "定常値の50%へ初めて達した時刻を読む。",
    ],
    explanation:
      "10%と90%は立ち上がり時間の基準。\\(y_{\\max}\\) に達する時刻は行き過ぎ時間である。",
    source: "textbook-p65-68",
  },
  {
    id: "textbook-response-q06-rapidity",
    topic: "response-stability",
    genre: "赤文字・比較",
    difficulty: 1,
    format: "choice",
    prompt: "他条件が同じとき、どの応答が最も速応性が高い？",
    answer: "\\(t_r\\) と \\(t_d\\) がともに小さい応答",
    options: [
      "\\(t_r\\) と \\(t_d\\) がともに小さい応答",
      "\\(t_r\\) と \\(t_d\\) がともに大きい応答",
      "\\(O_s\\) だけが大きい応答",
      "\\(y_\\infty\\) だけが大きい応答",
    ],
    formula: "t_r,t_d\\downarrow\\;\\Rightarrow\\;\\text{速応性}\\uparrow",
    steps: [
      "速応性は入力変化に対する出力の反応の早さである。",
      "時間指標は小さいほど早いので \\(t_r,t_d\\) が小さいものを選ぶ。",
    ],
    explanation:
      "オーバーシュートは主に減衰性と関係し、定常値の大小だけでは反応速度を判断できない。",
    source: "textbook-p65-68",
  },
  {
    id: "textbook-response-q07-overshoot-formula",
    topic: "response-stability",
    genre: "赤文字・数式",
    difficulty: 1,
    format: "choice",
    prompt: "オーバーシュート（行き過ぎ量）\\(O_s\\) の式は？",
    answer: "\\(\\frac{y_{\\max}-y_\\infty}{y_\\infty}\\times100\\%\\)",
    options: [
      "\\(\\frac{y_{\\max}-y_\\infty}{y_\\infty}\\times100\\%\\)",
      "\\(\\frac{y_{\\max}}{y_\\infty}\\times100\\%\\)",
      "\\(\\frac{y_\\infty-y_{\\max}}{y_\\infty}\\times100\\%\\)",
      "\\(\\frac{y_{\\max}-y_\\infty}{y_{\\max}}\\times100\\%\\)",
    ],
    formula: "O_s=\\frac{y_{\\max}-y_\\infty}{y_\\infty}\\times100\\%",
    steps: [
      "最大値から定常値を引き、超過分を求める。",
      "超過分を定常値で割って相対化する。",
      "百分率にするため100%を掛ける。",
    ],
    explanation:
      "分母は最大値ではなく定常値。単なる最大値比でもなく、『定常値を超えた部分』だけを評価する。",
    source: "textbook-p65-68",
  },
  {
    id: "textbook-response-q08-peak-time",
    topic: "response-stability",
    genre: "図5.1・記号",
    difficulty: 1,
    format: "choice",
    prompt: "行き過ぎ時間（peak time）\\(t_p\\) で成り立つ式は？",
    answer: "\\(y(t_p)=y_{\\max}\\)",
    options: [
      "\\(y(t_p)=y_{\\max}\\)",
      "\\(y(t_p)=0.5y_\\infty\\)",
      "\\(y(t_p)=0.9y_\\infty\\)",
      "\\(y(t_p)=1.05y_\\infty\\) が必ず成り立つ",
    ],
    formula: "y(t_p)=y_{\\max}",
    steps: [
      "peakは応答波形の最初の最大の山を指す。",
      "その頂点の時刻が \\(t_p\\)、高さが \\(y_{\\max}\\) である。",
    ],
    explanation:
      "\\(t_p\\) は高さではなく時刻。最大値が1.05倍になるとは限らず、オーバーシュートの大きさによって変わる。",
    source: "textbook-p65-68",
  },
  {
    id: "textbook-response-q09-damping",
    topic: "response-stability",
    genre: "赤文字・定義",
    difficulty: 1,
    format: "choice",
    prompt: "入力変化によって生じる振動の収まり具合を評価する性質は？",
    answer: "減衰性",
    options: ["減衰性", "速応性", "定常特性", "遅れ時間"],
    formula: "O_s,t_s\\;\\text{で振動の収束を評価}",
    steps: [
      "問題文の『振動の収まり具合』に注目する。",
      "振動現象の収束度合いを表す減衰性を選ぶ。",
    ],
    explanation:
      "速応性は反応の早さ。一般に行き過ぎが大きく振動が長いほど減衰性は低く、整定時間も遅くなる。",
    source: "textbook-p65-68",
  },
  {
    id: "textbook-response-q10-settling-time",
    topic: "response-stability",
    genre: "図5.1・記号",
    difficulty: 1,
    format: "choice",
    prompt: "整定時間 \\(t_s\\) の判定として正しいものは？",
    answer: "±5%帯へ入り、その後一度も帯外へ出ない最初の時刻",
    options: [
      "±5%帯へ入り、その後一度も帯外へ出ない最初の時刻",
      "±5%帯へ最初に触れた時刻",
      "定常値を最初に横切った時刻",
      "最大値に達した時刻",
    ],
    formula: "0.95y_\\infty\\le y(t)\\le1.05y_\\infty\\quad(t\\ge t_s)",
    steps: [
      "定常値の95%と105%の2本で許容帯を作る。",
      "応答が帯へ入る候補時刻を探す。",
      "その後に帯外へ出ない最後の入り直し時刻を \\(t_s\\) とする。",
    ],
    explanation:
      "振動応答は許容帯へ何度も出入りするため、最初の進入では整定と判定できない。",
    source: "textbook-p65-68",
  },
  {
    id: "textbook-response-q11-level-order",
    topic: "response-stability",
    genre: "図5.1・数値",
    difficulty: 1,
    format: "choice",
    prompt: "図5.1の基準値を小さい順に正しく並べたものは？",
    answer: "\\(0.1y_\\infty<0.5y_\\infty<0.9y_\\infty<0.95y_\\infty<y_\\infty<1.05y_\\infty\\)",
    options: [
      "\\(0.1y_\\infty<0.5y_\\infty<0.9y_\\infty<0.95y_\\infty<y_\\infty<1.05y_\\infty\\)",
      "\\(0.1y_\\infty<0.9y_\\infty<0.5y_\\infty<y_\\infty<0.95y_\\infty<1.05y_\\infty\\)",
      "\\(0.5y_\\infty<0.1y_\\infty<0.95y_\\infty<0.9y_\\infty<1.05y_\\infty<y_\\infty\\)",
      "\\(0.1y_\\infty<0.5y_\\infty<0.9y_\\infty<1.05y_\\infty<y_\\infty<0.95y_\\infty\\)",
    ],
    formula: "0.1<0.5<0.9<0.95<1<1.05",
    steps: [
      "各係数を小数として比較する。",
      "同じ正の \\(y_\\infty\\) を掛けても大小関係は変わらない。",
    ],
    explanation:
      "\\(0.1,0.5,0.9\\) は立ち上がり・遅れの基準、\\(0.95,1.05\\) は整定の許容帯である。",
    source: "textbook-p65-68",
  },
  {
    id: "textbook-response-q12-band-numeric",
    topic: "response-stability",
    genre: "図5.1・計算",
    difficulty: 2,
    format: "text",
    prompt: "\\(y_\\infty=20\\) のとき、±5%許容帯の下限と上限を求めよ。",
    answer: "下限19、上限21",
    accepted: ["19,21", "19～21", "19から21", "下限19 上限21"],
    keywords: ["19", "21"],
    minKeywords: 2,
    formula: "0.95\\times20=19,\\qquad1.05\\times20=21",
    steps: [
      "下限は \\(0.95y_\\infty\\) なので \\(0.95\\times20=19\\)。",
      "上限は \\(1.05y_\\infty\\) なので \\(1.05\\times20=21\\)。",
    ],
    explanation:
      "20の5%は1なので、定常値20の上下に1ずつ取っても同じ結果になる。",
    source: "textbook-p65-68",
  },
  {
    id: "textbook-response-q13-rise-numeric",
    topic: "response-stability",
    genre: "図5.1・計算",
    difficulty: 2,
    format: "text",
    prompt: "応答が \\(0.1y_\\infty\\) に0.25 s、\\(0.9y_\\infty\\) に0.85 sで達した。\\(t_r\\) は？",
    answer: "\\(t_r=0.60\\,\\mathrm{s}\\)",
    accepted: ["0.60s", "0.6s", "0.60", "0.6"],
    keywords: ["0.6"],
    minKeywords: 1,
    formula: "t_r=t_{90}-t_{10}=0.85-0.25=0.60\\,\\mathrm{s}",
    steps: [
      "立ち上がり時間は90%到達時刻から10%到達時刻を引く。",
      "\\(0.85-0.25=0.60\\) sと計算する。",
    ],
    explanation:
      "0から0.85 sではない。\\(t_r\\) は10%から90%までの区間長である。",
    source: "textbook-p65-68",
  },
  {
    id: "textbook-response-q14-delay-numeric",
    topic: "response-stability",
    genre: "図5.1・計算",
    difficulty: 2,
    format: "text",
    prompt: "\\(y_\\infty=12\\) の応答が \\(y=6\\) に0.40 sで初めて達した。\\(t_d\\) は？",
    answer: "\\(t_d=0.40\\,\\mathrm{s}\\)",
    accepted: ["0.40s", "0.4s", "0.40", "0.4"],
    keywords: ["0.4"],
    minKeywords: 1,
    formula: "0.5y_\\infty=0.5\\times12=6\\;\\Rightarrow\\;t_d=0.40\\,\\mathrm{s}",
    steps: [
      "定常値の50%を計算すると6。",
      "その値へ初めて達した時刻0.40 sを遅れ時間と読む。",
    ],
    explanation:
      "\\(t_d\\) は50%到達時刻そのもの。10%と90%の差を取る \\(t_r\\) とは計算方法が異なる。",
    source: "textbook-p65-68",
  },
  {
    id: "textbook-response-q15-overshoot-numeric",
    topic: "response-stability",
    genre: "図5.1・計算",
    difficulty: 2,
    format: "text",
    prompt: "\\(y_\\infty=8\\)、\\(y_{\\max}=10\\) のとき、\\(O_s\\) を求めよ。",
    answer: "\\(O_s=25\\%\\)",
    accepted: ["25%", "25"],
    keywords: ["25"],
    minKeywords: 1,
    formula: "O_s=\\frac{10-8}{8}\\times100\\%=25\\%",
    steps: [
      "行き過ぎた量は \\(10-8=2\\)。",
      "定常値8で割ると \\(\\frac{2}{8}=0.25\\)。",
      "100%を掛けて25%とする。",
    ],
    explanation:
      "最大値10をそのまま8で割った125%ではなく、超過分だけを割合にする。",
    source: "textbook-p65-68",
  },
  {
    id: "textbook-response-q16-settling-scenario",
    topic: "response-stability",
    genre: "図5.1・読み取り",
    difficulty: 2,
    format: "choice",
    prompt: "応答は2.8 sで±5%帯へ入ったが3.1 sで帯外へ出て、4.2 sで再び入った後は出なかった。\\(t_s\\) は？",
    answer: "4.2 s",
    options: ["2.8 s", "3.1 s", "4.2 s", "2.8+4.2=7.0 s"],
    formula: "t_s=4.2\\,\\mathrm{s}",
    steps: [
      "2.8 sの進入後には帯外へ出ているので整定ではない。",
      "4.2 s以後は帯外へ出ないため、この再進入時刻を採用する。",
    ],
    explanation:
      "整定時間は最初の進入ではなく、『その後はみ出さない』条件を満たす最初の時刻である。",
    source: "textbook-p65-68",
  },
  {
    id: "textbook-response-q17-symbol-map",
    topic: "response-stability",
    genre: "図5.1・総合",
    difficulty: 2,
    format: "choice",
    prompt: "図5.1の記号対応として正しい組合せは？",
    answer: "\\(t_d\\):50%到達、\\(t_r\\):10→90%、\\(t_p\\):最大値到達、\\(t_s\\):±5%帯へ整定",
    options: [
      "\\(t_d\\):50%到達、\\(t_r\\):10→90%、\\(t_p\\):最大値到達、\\(t_s\\):±5%帯へ整定",
      "\\(t_d\\):10→90%、\\(t_r\\):50%到達、\\(t_p\\):±5%帯へ整定、\\(t_s\\):最大値到達",
      "\\(t_d\\):最大値到達、\\(t_r\\):±5%帯へ整定、\\(t_p\\):50%到達、\\(t_s\\):10→90%",
      "\\(t_d\\):±5%帯へ整定、\\(t_r\\):最大値到達、\\(t_p\\):10→90%、\\(t_s\\):50%到達",
    ],
    formula: "t_d:0\\to50\\%,\\quad t_r:10\\to90\\%,\\quad t_p:y_{\\max},\\quad t_s:\\pm5\\%",
    steps: [
      "delay、rise、peak、settlingの英語を各定義へ結び付ける。",
      "図の横軸上で50%、10→90%、山頂、許容帯の順に確認する。",
    ],
    explanation:
      "試験では記号だけが示されても即答できるよう、割合と波形上の位置をセットで覚える。",
    source: "textbook-p65-68",
  },
  {
    id: "textbook-response-q18-figure52-rapidity",
    topic: "response-stability",
    genre: "図5.2・曲線比較",
    difficulty: 2,
    format: "choice",
    prompt: "図5.2のオーバーシュートがない3曲線 \\(y_a,y_b,y_c\\) を、速応性が高い順に並べよ。",
    answer: "\\(y_a>y_b>y_c\\)",
    options: ["\\(y_a>y_b>y_c\\)", "\\(y_c>y_b>y_a\\)", "\\(y_b>y_a>y_c\\)", "3曲線は同じ"],
    formula: "\\text{速応性}:y_a>y_b>y_c",
    steps: [
      "同じ定常値へ向かう各曲線の立ち上がりの早さを見る。",
      "最初に許容帯へ近づく青の \\(y_a\\)、次に \\(y_b\\)、最後に赤の \\(y_c\\) と読む。",
    ],
    explanation:
      "図5.2では行き過ぎがないため、立ち上がりが急な曲線ほど速応性が高いと素直に比較できる。",
    source: "textbook-p65-68",
  },
  {
    id: "textbook-response-q19-figure52-settling",
    topic: "response-stability",
    genre: "図5.2・曲線比較",
    difficulty: 2,
    format: "choice",
    prompt: "図5.2の整定時間の大小関係は？",
    answer: "\\(t_s(y_a)<t_s(y_b)<t_s(y_c)\\)",
    options: [
      "\\(t_s(y_a)<t_s(y_b)<t_s(y_c)\\)",
      "\\(t_s(y_c)<t_s(y_b)<t_s(y_a)\\)",
      "\\(t_s(y_a)=t_s(y_b)=t_s(y_c)\\)",
      "\\(t_s(y_b)<t_s(y_a)<t_s(y_c)\\)",
    ],
    formula: "t_s(y_a)<t_s(y_b)<t_s(y_c)",
    steps: [
      "各曲線が±5%帯へ入り、その後出ない時刻を読む。",
      "図中の縦破線は左から \\(y_a,y_b,y_c\\) の \\(t_s\\) を示す。",
    ],
    explanation:
      "オーバーシュートがない図5.2では、速応性が低いほど定常値への接近が遅く、整定時間も遅くなる。",
    source: "textbook-p65-68",
  },
  {
    id: "textbook-response-q20-figure53-comparison",
    topic: "response-stability",
    genre: "図5.3・曲線比較",
    difficulty: 2,
    format: "choice",
    prompt: "図5.3の曲線比較から読み取れる正しい関係は？",
    answer: "オーバーシュートが大きい曲線ほど振動が長く残り、整定時間が遅い",
    options: [
      "オーバーシュートが大きい曲線ほど振動が長く残り、整定時間が遅い",
      "オーバーシュートが大きい曲線ほど必ず整定時間が早い",
      "オーバーシュートと整定時間には図中で関係がない",
      "行き過ぎが最大の \\(y_c\\) が最も早く整定する",
    ],
    formula: "O_s\\uparrow\\;\\Rightarrow\\;\\text{振動が収まりにくい}\\;\\Rightarrow\\;t_s\\uparrow",
    steps: [
      "\\(y_a,y_b,y_c\\) の山の高さと振動回数を比較する。",
      "許容帯へ最後に入る縦破線が右へ移ることを確認する。",
    ],
    explanation:
      "図5.3では \\(y_a\\)、\\(y_b\\)、\\(y_c\\) の順に行き過ぎと振動が大きくなり、整定も同じ順に遅くなる。",
    source: "textbook-p65-68",
  },
  {
    id: "textbook-response-q21-no-overshoot",
    topic: "response-stability",
    genre: "注意事項",
    difficulty: 1,
    format: "choice",
    prompt: "オーバーシュートについて正しい記述は？",
    answer: "定常値へ単調に近づくシステムでは生じないことがある",
    options: [
      "定常値へ単調に近づくシステムでは生じないことがある",
      "すべての動的システムで必ず生じる",
      "生じないときは定常値も存在しない",
      "生じないとき整定時間は定義できない",
    ],
    formula: "y(t)\\le y_\\infty\\;\\text{なら}\\;O_s=0\\%",
    steps: [
      "オーバーシュートは最大値が定常値を上回る現象である。",
      "単調応答では上回らないため、行き過ぎは生じない。",
    ],
    explanation:
      "図5.2はオーバーシュートなしでも速応性・整定時間を比較できる例である。",
    source: "textbook-p65-68",
  },
  {
    id: "textbook-response-q22-normalized-comparison",
    topic: "response-stability",
    genre: "オーバーシュート・計算",
    difficulty: 3,
    format: "choice",
    prompt: "Aは \\(y_\\infty=10,y_{\\max}=12\\)、Bは \\(y_\\infty=20,y_{\\max}=23\\)。行き過ぎ率が大きいのは？",
    answer: "A（20%）",
    options: ["A（20%）", "B（23%）", "B（15%）の方がAより大きい", "同じ"],
    formula: "O_{s,A}=\\frac{2}{10}\\times100=20\\%,\\qquad O_{s,B}=\\frac{3}{20}\\times100=15\\%",
    steps: [
      "Aの超過分2を定常値10で割り、20%を得る。",
      "Bの超過分3を定常値20で割り、15%を得る。",
      "絶対差3が大きいBではなく、相対率20%のAを選ぶ。",
    ],
    explanation:
      "定常値が異なる曲線は超過の絶対量だけでは比較できない。必ず定常値で正規化した \\(O_s\\) を使う。",
    source: "textbook-p65-68",
  },
  {
    id: "textbook-response-q23-steady-value-caution",
    topic: "response-stability",
    genre: "定常値・注意事項",
    difficulty: 2,
    format: "choice",
    prompt: "単位ステップ応答の定常値について正しい記述は？",
    answer: "一般に1とは限らず、システムの特性に依存する",
    options: [
      "一般に1とは限らず、システムの特性に依存する",
      "入力が1なので必ず1になる",
      "必ず0になる",
      "発散する応答でも有限の定常値を必ず定義できる",
    ],
    formula: "y_\\infty=\\lim_{t\\to\\infty}y(t)",
    steps: [
      "入力の大きさと出力の最終値はシステムのゲインを介して決まる。",
      "極限が存在するときだけ、その値を定常値と呼ぶ。",
    ],
    explanation:
      "教科書は『単位ステップ入力に対する定常値は1とはならず、値はシステムの特性に依存する』と注意している。",
    source: "textbook-p65-68",
  },
  {
    id: "textbook-response-q24-english-symbols",
    topic: "response-stability",
    genre: "赤文字・英語",
    difficulty: 1,
    format: "choice",
    prompt: "英語名と記号の対応がすべて正しいものは？",
    answer: "rise time \\(t_r\\)、delay time \\(t_d\\)、peak time \\(t_p\\)、settling time \\(t_s\\)",
    options: [
      "rise time \\(t_r\\)、delay time \\(t_d\\)、peak time \\(t_p\\)、settling time \\(t_s\\)",
      "rise time \\(t_d\\)、delay time \\(t_r\\)、peak time \\(t_s\\)、settling time \\(t_p\\)",
      "rise time \\(t_p\\)、delay time \\(t_s\\)、peak time \\(t_r\\)、settling time \\(t_d\\)",
      "rise time \\(O_s\\)、delay time \\(y_\\infty\\)、peak time \\(t_d\\)、settling time \\(t_r\\)",
    ],
    formula: "t_r:\\text{rise},\\quad t_d:\\text{delay},\\quad t_p:\\text{peak},\\quad t_s:\\text{settling}",
    steps: [
      "各記号の添字を英単語の頭文字と対応させる。",
      "r=rise、d=delay、p=peak、s=settlingと確認する。",
    ],
    explanation:
      "日本語定義だけでなく英語の頭文字まで結び付けると、図中の記号を取り違えにくい。",
    source: "textbook-p65-68",
  },
  {
    id: "textbook-response-q25-figure51-values",
    topic: "response-stability",
    genre: "図5.1・総合計算",
    difficulty: 3,
    format: "text",
    prompt: "\\(y_\\infty=40\\) のとき、図5.1の \\(0.1y_\\infty,0.5y_\\infty,0.9y_\\infty,0.95y_\\infty,1.05y_\\infty\\) を順に求めよ。",
    answer: "4、20、36、38、42",
    accepted: ["4,20,36,38,42", "4 20 36 38 42", "4、20、36、38、42"],
    keywords: ["4", "20", "36", "38", "42"],
    minKeywords: 5,
    formula: "0.1(40)=4,\\;0.5(40)=20,\\;0.9(40)=36,\\;0.95(40)=38,\\;1.05(40)=42",
    steps: [
      "10%、50%、90%を順に40へ掛ける。",
      "整定帯の下限95%と上限105%も40へ掛ける。",
      "元の設問順に4、20、36、38、42と並べる。",
    ],
    explanation:
      "図の数値は割合だけでなく、与えられた定常値に応じた実数へ即座に換算できるようにする。",
    source: "textbook-p65-68",
  },
  {
    id: "textbook-response-q26-full-explanation",
    topic: "response-stability",
    genre: "記述・総合",
    difficulty: 3,
    format: "text",
    prompt: "速応性と減衰性の違いを、\\(t_r,t_d,O_s,t_s\\) を用いて説明せよ。",
    answer:
      "速応性は入力変化に対する出力の反応の早さで、主に \\(t_r,t_d\\) が小さいほど高い。減衰性は振動の収まりやすさで、一般に \\(O_s\\) が小さく \\(t_s\\) が短いほど高い。",
    accepted: [
      "速応性はtr tdで反応の早さ、減衰性はOs tsで振動の収まり",
      "trとtdが小さいほど速応性が高く、Osが小さくtsが短いほど減衰性が高い",
    ],
    keywords: ["速応性", "減衰性", "tr", "td", "Os", "ts"],
    minKeywords: 5,
    formula: "t_r,t_d\\downarrow\\Rightarrow\\text{速応性}\\uparrow,\\qquad O_s,t_s\\downarrow\\Rightarrow\\text{減衰性}\\uparrow",
    steps: [
      "まず速応性を『反応の早さ』と定義し、\\(t_r,t_d\\) を対応させる。",
      "次に減衰性を『振動の収まり』と定義し、\\(O_s,t_s\\) を対応させる。",
      "図5.2と5.3から、速い立ち上がりだけでは整定の良さが決まらない場合もあると補足する。",
    ],
    explanation:
      "図5.2ではオーバーシュートがないため速い応答ほど早く整定する。一方、図5.3では速く立ち上がっても行き過ぎが大きければ振動が残り、整定は遅くなる。",
    source: "textbook-p65-68",
  },
];
