export type SmartControlTopicId =
  | "transfer"
  | "inverse-laplace"
  | "response-stability"
  | "feedback"
  | "block-diagram";

export type SmartControlTopic = {
  id: SmartControlTopicId;
  number: string;
  title: string;
  shortTitle: string;
  description: string;
  color: string;
  source: string;
};

export type SmartControlCard = {
  id: string;
  topic: SmartControlTopicId;
  title: string;
  prompt: string;
  formula: string;
  explanation: string;
  cue: string;
  example?: string;
};

export type SmartControlQuestion = {
  id: string;
  topic: SmartControlTopicId;
  genre: string;
  difficulty: 1 | 2 | 3;
  format: "choice" | "text";
  prompt: string;
  context?: string;
  answer: string;
  options?: string[];
  accepted?: string[];
  keywords?: string[];
  minKeywords?: number;
  formula?: string;
  steps: string[];
  explanation: string;
  source: "scope-zip" | "past2-overlap" | "textbook-p65-68";
};

export type SmartControlExamQuestion = {
  id: string;
  section: string;
  points: number;
  prompt: string;
  answer: string;
  formula?: string;
  steps: string[];
};

export type SmartControlExam = {
  id: string;
  title: string;
  subtitle: string;
  questions: SmartControlExamQuestion[];
};

export type SmartControlExamFormat = {
  id: string;
  title: string;
  description: string;
  strategy: string;
};

export const SMART_CONTROL_TOPICS: SmartControlTopic[] = [
  {
    id: "transfer",
    number: "01",
    title: "伝達関数と標準入力",
    shortTitle: "伝達関数・入力",
    description: "微分方程式を初期値0でラプラス変換し、入力から出力への伝達関数と時間応答を求める。",
    color: "#55dde0",
    source: "範囲ZIP 010709",
  },
  {
    id: "inverse-laplace",
    number: "02",
    title: "逆ラプラス変換",
    shortTitle: "逆ラプラス",
    description: "単根・重根・複素根・実根と複素根の混在を見分け、部分分数分解から時間関数へ戻す。",
    color: "#ffd65c",
    source: "範囲ZIP 010717〜010733",
  },
  {
    id: "response-stability",
    number: "03",
    title: "ステップ応答・極・安定性",
    shortTitle: "応答・極・安定",
    description: "応答指標を読み取り、極を複素平面へ配置して収束・安定性を判定する。",
    color: "#ff9f68",
    source: "範囲ZIP 010737〜010802＋教科書p.65〜68＋過去問2の重複部分",
  },
  {
    id: "feedback",
    number: "04",
    title: "フィードバックとゲインK",
    shortTitle: "帰還・ゲインK",
    description: "閉ループ伝達関数と特性方程式を作り、極が左半平面に入るKの範囲を求める。",
    color: "#ff8fc7",
    source: "範囲ZIP 010802〜010813",
  },
  {
    id: "block-diagram",
    number: "05",
    title: "ブロック線図の等価変換",
    shortTitle: "ブロック線図",
    description: "直列・並列・帰還を簡約し、加え合わせ点と引き出し点を移動して等価な伝達関数を作る。",
    color: "#a88bff",
    source: "範囲ZIP 教科書p.38 図3.13〜3.15＋過去問2の重複部分",
  },
];

export const SMART_CONTROL_CARDS: SmartControlCard[] = [
  {
    id: "smart-impulse-transform",
    topic: "transfer",
    title: "単位インパルス入力",
    prompt: "単位インパルス \\(\\delta(t)\\) のラプラス変換は？",
    formula: "\\mathcal{L}\\{\\delta(t)\\}=1",
    explanation: "時刻0に瞬間的に加える入力。伝達関数そのものを出力へ掛けるので、インパルス応答は伝達関数の逆ラプラス変換になる。",
    cue: "針状の入力 → s領域では1",
  },
  {
    id: "smart-step-transform",
    topic: "transfer",
    title: "単位ステップ入力",
    prompt: "時刻0から1を保つ単位ステップ入力のラプラス変換は？",
    formula: "\\mathcal{L}\\{1\\}=\\frac{1}{s}",
    explanation: "ステップ応答を求めるときは、伝達関数に \\(\\frac{1}{s}\\) を掛けてから逆ラプラス変換する。",
    cue: "段差状の入力 → \\(\\frac{1}{s}\\)",
  },
  {
    id: "smart-transfer-definition",
    topic: "transfer",
    title: "伝達関数の定義",
    prompt: "初期値0のとき、入力U(s)から出力Y(s)への伝達関数は？",
    formula: "G(s)=\\frac{Y(s)}{U(s)}",
    explanation: "初期値を0として運動方程式・保存式をラプラス変換し、入力以外を出力側へ整理して比を取る。",
    cue: "出力 ÷ 入力",
  },
  {
    id: "smart-tank-balance",
    topic: "transfer",
    title: "液面系の保存式",
    prompt: "容量係数C、液面H、流入Qi、流出Qoの液面系の式は？",
    formula: "C\\frac{dH}{dt}=Q_i-Q_o",
    explanation: "液面に蓄えられる量の変化は『流入−流出』。タンク系の伝達関数を作る出発点になる。",
    cue: "蓄積＝流入−流出",
  },
  {
    id: "smart-tank-outflow",
    topic: "transfer",
    title: "液面系の流出則",
    prompt: "流動抵抗Rを通る流出量Qoと液面Hの関係は？",
    formula: "Q_o=\\frac{H}{R}",
    explanation: "液面差を抵抗で割った量が流れる。電気回路のオーム則と似た形で覚える。",
    cue: "高さ ÷ 抵抗",
  },
  {
    id: "smart-tank-transfer",
    topic: "transfer",
    title: "液面系の伝達関数",
    prompt: "液面系の入力Qiから出力Hへの伝達関数は？",
    formula: "\\frac{H(s)}{Q_i(s)}=\\frac{R}{CRs+1}",
    explanation: "保存式へ \\(Q_o=\\frac{H}{R}\\) を代入し、初期値0でラプラス変換すると \\((CRs+1)H=RQ_i\\) になる。",
    cue: "一次遅れ・時定数CR・定常ゲインR",
  },
  {
    id: "smart-first-order-impulse",
    topic: "transfer",
    title: "一次遅れのインパルス応答",
    prompt: "\\(G(s)=\\frac{K}{Ts+1}\\) の単位インパルス応答は？",
    formula: "g(t)=\\frac{K}{T}e^{-\\frac{t}{T}}",
    explanation: "\\(\\frac{K}{Ts+1}=\\frac{\\frac{K}{T}}{s+\\frac{1}{T}}\\) と変形し、\\(\\frac{1}{s+a}\\) の変換対へ合わせる。",
    cue: "係数 \\(\\frac{K}{T}\\)、指数の時定数 \\(T\\)",
  },
  {
    id: "smart-first-order-step",
    topic: "transfer",
    title: "一次遅れのステップ応答",
    prompt: "\\(G(s)=\\frac{K}{Ts+1}\\) の単位ステップ応答は？",
    formula: "y(t)=K\\left(1-e^{-\\frac{t}{T}}\\right)",
    explanation: "\\(\\frac{G(s)}{s}\\) を部分分数分解する。\\(t\\to\\infty\\) ではKへ単調に近づく。",
    cue: "0からKへ指数的に近づく",
  },
  {
    id: "smart-ilaplace-one-over-s",
    topic: "inverse-laplace",
    title: "定数の変換対",
    prompt: "\\(\\frac{1}{s}\\) の逆ラプラス変換は？",
    formula: "\\mathcal{L}^{-1}\\left\\{\\frac{1}{s}\\right\\}=1",
    explanation: "単位ステップに対応する最重要の基本対。",
    cue: "\\(\\frac{1}{s}\\leftrightarrow1\\)",
  },
  {
    id: "smart-ilaplace-one-over-s2",
    topic: "inverse-laplace",
    title: "ランプの変換対",
    prompt: "\\(\\frac{1}{s^2}\\) の逆ラプラス変換は？",
    formula: "\\mathcal{L}^{-1}\\left\\{\\frac{1}{s^2}\\right\\}=t",
    explanation: "積分されたステップ、つまり傾き1のランプ入力に対応する。",
    cue: "sの2乗 → t",
  },
  {
    id: "smart-ilaplace-simple-pole",
    topic: "inverse-laplace",
    title: "単根の指数関数",
    prompt: "\\(\\frac{1}{s+a}\\) の逆ラプラス変換は？",
    formula: "\\mathcal{L}^{-1}\\left\\{\\frac{1}{s+a}\\right\\}=e^{-at}",
    explanation: "極はs=-a。a>0なら左半平面にあり、時間応答は減衰する。",
    cue: "s+a ↔ e^{-at}",
  },
  {
    id: "smart-ilaplace-double-pole",
    topic: "inverse-laplace",
    title: "重根の指数関数",
    prompt: "\\(\\frac{1}{(s+a)^2}\\) の逆ラプラス変換は？",
    formula: "\\mathcal{L}^{-1}\\left\\{\\frac{1}{(s+a)^2}\\right\\}=te^{-at}",
    explanation: "同じ極が2回現れると時間領域でtが掛かる。3重根ならt²の項が現れる。",
    cue: "2重根 → tを1個掛ける",
  },
  {
    id: "smart-ilaplace-sine",
    topic: "inverse-laplace",
    title: "正弦の変換対",
    prompt: "\\(\\frac{\\omega}{s^2+\\omega^2}\\) の逆ラプラス変換は？",
    formula: "\\mathcal{L}^{-1}\\left\\{\\frac{\\omega}{s^2+\\omega^2}\\right\\}=\\sin\\omega t",
    explanation: "分子が \\(\\omega\\) であることを確認する。\\(\\frac{1}{s^2+\\omega^2}\\) なら \\(\\frac{1}{\\omega}\\) を外へ出す。",
    cue: "分子ω → sin",
  },
  {
    id: "smart-ilaplace-cosine",
    topic: "inverse-laplace",
    title: "余弦の変換対",
    prompt: "\\(\\frac{s}{s^2+\\omega^2}\\) の逆ラプラス変換は？",
    formula: "\\mathcal{L}^{-1}\\left\\{\\frac{s}{s^2+\\omega^2}\\right\\}=\\cos\\omega t",
    explanation: "分子がsなら余弦。sinとcosの分子を取り違えない。",
    cue: "分子s → cos",
  },
  {
    id: "smart-ilaplace-shifted-sine",
    topic: "inverse-laplace",
    title: "減衰正弦",
    prompt: "\\(\\frac{\\omega}{(s+a)^2+\\omega^2}\\) の逆変換は？",
    formula: "e^{-at}\\sin\\omega t",
    explanation: "sをs+aへ平行移動すると、時間領域ではe^{-at}が掛かる。",
    cue: "s+aのずれ → e^{-at}",
  },
  {
    id: "smart-ilaplace-shifted-cosine",
    topic: "inverse-laplace",
    title: "減衰余弦",
    prompt: "\\(\\frac{s+a}{(s+a)^2+\\omega^2}\\) の逆変換は？",
    formula: "e^{-at}\\cos\\omega t",
    explanation: "分子もs+aの形へ揃える。余った定数部分はsin項へ分ける。",
    cue: "分子s+a → 減衰cos",
  },
  {
    id: "smart-heaviside",
    topic: "inverse-laplace",
    title: "ヘビサイド法（単根）",
    prompt: "単根pに対応する係数Aを一発で求める式は？",
    formula: "A=\\lim_{s\\to p}(s-p)F(s)",
    explanation: "F(s)の分母に(s-p)が1個だけ含まれるとき、その因子を消してs=pを代入する。",
    cue: "求めたい因子を掛けて、その根を代入",
  },
  {
    id: "smart-complete-square",
    topic: "inverse-laplace",
    title: "2次式の平方完成",
    prompt: "\\(s^2+2as+(a^2+\\omega^2)\\) を変換対へ合わせる形は？",
    formula: "(s+a)^2+\\omega^2",
    explanation: "複素根を持つ2次式は平方完成し、減衰率aと角周波数ωを読み取る。",
    cue: "半分を足して引く",
  },
  {
    id: "smart-pole-definition",
    topic: "response-stability",
    title: "極の定義",
    prompt: "伝達関数の極とは？",
    formula: "D(s)=0\\quad\\Rightarrow\\quad s=p_i",
    explanation: "伝達関数 \\(G(s)=\\frac{N(s)}{D(s)}\\) の分母を0にする \\(s\\) の値。約分前後を確認し、実際に残る分母から求める。",
    cue: "分母＝0",
  },
  {
    id: "smart-stability-rule",
    topic: "response-stability",
    title: "安定判別",
    prompt: "この授業資料でシステムが安定となる極の条件は？",
    formula: "\\operatorname{Re}(p_i)<0\\quad(\\text{all }i)",
    explanation: "全ての極が複素平面の開左半平面にあるときだけ安定。右半平面だけでなく虚軸上の極も不安定扱い。",
    cue: "全極の実部が負",
  },
  {
    id: "smart-response-times",
    topic: "response-stability",
    title: "過渡応答の時間指標",
    prompt: "立ち上がり・ピーク・整定の各時刻の記号は？",
    formula: "t_r,\\quad t_p,\\quad t_s",
    explanation: "trは立ち上がり時間、tpは最大値に達する時刻、tsは応答が許容帯内へ入り続ける時刻。",
    cue: "rise / peak / settling",
  },
  {
    id: "smart-overshoot",
    topic: "response-stability",
    title: "最大行き過ぎ量",
    prompt: "定常値y∞に対する百分率オーバーシュートの式は？",
    formula: "M_p=\\frac{y_{\\max}-y_\\infty}{y_\\infty}\\times100\\%",
    explanation: "最大値が定常値をどれだけ超えたかを、定常値に対する割合で表す。",
    cue: "（最大−定常）÷定常",
  },
  {
    id: "smart-settling-band",
    topic: "response-stability",
    title: "5%整定帯",
    prompt: "定常値y∞の上下5%の帯は？",
    formula: "0.95y_\\infty\\le y(t)\\le1.05y_\\infty",
    explanation: "応答がこの帯へ入り、その後外へ出なくなる最初の時刻が5%整定時間。",
    cue: "95%〜105%",
  },
  {
    id: "smart-negative-feedback",
    topic: "feedback",
    title: "負帰還の閉ループ伝達関数",
    prompt: "前向きG、帰還Hの負帰還系の閉ループ伝達関数は？",
    formula: "G_{\\mathrm{cl}}(s)=\\frac{G(s)}{1+G(s)H(s)}",
    explanation: "加え合わせ点が『入力−帰還信号』なら分母は1+GHになる。符号を直感だけで決めず、式から確認する。",
    cue: "負帰還 → 分母はプラス",
  },
  {
    id: "smart-positive-feedback",
    topic: "feedback",
    title: "正帰還の閉ループ伝達関数",
    prompt: "前向きG、帰還Hの正帰還系の閉ループ伝達関数は？",
    formula: "G_{\\mathrm{cl}}(s)=\\frac{G(s)}{1-G(s)H(s)}",
    explanation: "加え合わせ点が『入力＋帰還信号』なら分母は1−GH。",
    cue: "正帰還 → 分母はマイナス",
  },
  {
    id: "smart-characteristic-equation",
    topic: "feedback",
    title: "特性方程式",
    prompt: "閉ループ系の極を求める特性方程式は？",
    formula: "1+G(s)H(s)=0",
    explanation: "負帰還では閉ループ伝達関数の分母1+GHを0とする。整理後の多項式の根が閉ループ極。",
    cue: "閉ループ分母＝0",
  },
  {
    id: "smart-gain-first-order",
    topic: "feedback",
    title: "不安定一次系のK安定化",
    prompt: "\\(\\frac{K}{s-1}\\) を単位負帰還したときの安定条件は？",
    formula: "G_{\\mathrm{cl}}(s)=\\frac{K}{s-1+K},\\qquad K>1",
    explanation: "閉ループ極はs=1−K。左半平面へ入れるには1−K<0が必要。K=1は極0なので安定ではない。",
    cue: "極1−Kを負にする",
  },
  {
    id: "smart-gain-second-order",
    topic: "feedback",
    title: "積分要素を含む系のK安定化",
    prompt: "\\(\\frac{K}{s(s+1)}\\) を単位負帰還したときの安定条件は？",
    formula: "G_{\\mathrm{cl}}(s)=\\frac{K}{s^2+s+K},\\qquad K>0",
    explanation: "極は \\(\\frac{-1\\pm\\sqrt{1-4K}}{2}\\)。\\(K>0\\) なら実根でも複素根でも実部が負になる。",
    cue: "この系はK>0",
  },
  {
    id: "smart-series-block",
    topic: "block-diagram",
    title: "直列結合",
    prompt: "G1とG2を直列につないだ等価伝達関数は？",
    formula: "G_{\\mathrm{eq}}=G_2G_1",
    explanation: "前段の出力が後段の入力になるため、入出力関係を代入すると積になる。",
    cue: "直列＝積",
  },
  {
    id: "smart-parallel-block",
    topic: "block-diagram",
    title: "並列結合",
    prompt: "同じ入力をG1とG2へ入れて加減算する等価伝達関数は？",
    formula: "G_{\\mathrm{eq}}=G_1\\pm G_2",
    explanation: "各枝の出力G1UとG2Uを加え合わせるので、共通入力Uでくくる。",
    cue: "並列＝和または差",
  },
  {
    id: "smart-summing-shift",
    topic: "block-diagram",
    title: "加え合わせ点の移動",
    prompt: "加え合わせ点をブロックGの後ろから前へ移すと、移動した枝に何を置く？",
    formula: "\\frac{1}{G}",
    explanation: "移動後も加算される信号の大きさを同じにするため、Gを通る前に \\(\\frac{1}{G}\\) で補正する。逆方向なら \\(G\\) を置く。",
    cue: "後→前は \\(\\frac{1}{G}\\)、前→後は \\(G\\)",
  },
  {
    id: "smart-pickoff-shift",
    topic: "block-diagram",
    title: "引き出し点の移動",
    prompt: "引き出し点をブロックGの後ろから前へ移すと、引き出し枝に何を置く？",
    formula: "G",
    explanation: "元はGを通過した後の信号を取り出していたため、前へ移した枝側に \\(G\\) を置く。逆方向なら \\(\\frac{1}{G}\\)。",
    cue: "後→前は \\(G\\)、前→後は \\(\\frac{1}{G}\\)",
  },
];

export const SMART_CONTROL_QUESTIONS: SmartControlQuestion[] = [
  {
    id: "smart-q-transfer-1",
    topic: "transfer",
    genre: "標準入力",
    difficulty: 1,
    format: "choice",
    prompt: "単位インパルス入力 \\(\\delta(t)\\) のラプラス変換を選べ。",
    answer: "\\(1\\)",
    options: ["\\(1\\)", "\\(\\frac{1}{s}\\)", "\\(s\\)", "\\(e^{-t}\\)"],
    formula: "\\mathcal{L}\\{\\delta(t)\\}=1",
    steps: ["インパルスは時刻0に面積1を持つ瞬間入力。", "積分すると1なので、s領域でも1になる。"],
    explanation: "ステップ入力の \\(\\frac{1}{s}\\) と混同しない。",
    source: "scope-zip",
  },
  {
    id: "smart-q-transfer-2",
    topic: "transfer",
    genre: "標準入力",
    difficulty: 1,
    format: "choice",
    prompt: "単位ステップ入力をs領域で表したものを選べ。",
    answer: "\\(\\frac{1}{s}\\)",
    options: ["\\(1\\)", "\\(\\frac{1}{s}\\)", "\\(\\frac{1}{s^2}\\)", "\\(s\\)"],
    formula: "\\mathcal{L}\\{1\\}=\\frac{1}{s}",
    steps: ["時刻0以後の入力は常に1。", "1をラプラス変換すると \\(\\frac{1}{s}\\)。"],
    explanation: "ステップ応答は \\(\\frac{G(s)}{s}\\) を逆変換して求める。",
    source: "scope-zip",
  },
  {
    id: "smart-q-transfer-3",
    topic: "transfer",
    genre: "定義",
    difficulty: 1,
    format: "choice",
    prompt: "初期値0で入力U(s)、出力Y(s)の伝達関数を選べ。",
    answer: "\\(\\frac{Y(s)}{U(s)}\\)",
    options: ["\\(\\frac{Y(s)}{U(s)}\\)", "\\(\\frac{U(s)}{Y(s)}\\)", "\\(Y(s)+U(s)\\)", "\\(Y(s)U(s)\\)"],
    formula: "G(s)=\\frac{Y(s)}{U(s)}",
    steps: ["入出力をs領域へ変換する。", "出力を入力で割る。"],
    explanation: "初期値0という条件も定義に含めて覚える。",
    source: "scope-zip",
  },
  {
    id: "smart-q-transfer-4",
    topic: "transfer",
    genre: "液面系",
    difficulty: 1,
    format: "text",
    prompt: "液面系の蓄積を表す保存式を、C、H、Qi、Qoを使って書け。",
    answer: "\\(C\\,\\frac{dH}{dt}=Q_i-Q_o\\)",
    accepted: ["C dH/dt=Qi-Qo", "CdH/dt=Qi-Qo"],
    keywords: ["C", "dH", "Qi", "Qo"],
    minKeywords: 4,
    formula: "C\\frac{dH}{dt}=Q_i-Q_o",
    steps: ["液面の蓄積速度は \\(C\\frac{dH}{dt}\\)。", "蓄積＝流入−流出を使う。"],
    explanation: "流出を引く符号が重要。",
    source: "scope-zip",
  },
  {
    id: "smart-q-transfer-5",
    topic: "transfer",
    genre: "液面系",
    difficulty: 2,
    format: "choice",
    prompt: "\\(C\\,\\frac{dH}{dt}=Q_i-Q_o\\)、\\(Q_o=\\frac{H}{R}\\) から得られる \\(\\frac{H(s)}{Q_i(s)}\\) を選べ。",
    answer: "\\(\\frac{R}{CRs+1}\\)",
    options: ["\\(\\frac{R}{CRs+1}\\)", "\\(\\frac{CR}{Rs+1}\\)", "\\(\\frac{1}{CR+s}\\)", "\\(\\frac{CRs+1}{R}\\)"],
    formula: "\\frac{H(s)}{Q_i(s)}=\\frac{R}{CRs+1}",
    steps: ["\\(Q_o=\\frac{H}{R}\\) を保存式へ代入する。", "初期値0で \\(CsH=Q_i-\\frac{H}{R}\\)。", "Rを掛けて \\((CRs+1)H=RQ_i\\)。"],
    explanation: "時定数はCR、定常ゲインはR。",
    source: "scope-zip",
  },
  {
    id: "smart-q-transfer-6",
    topic: "transfer",
    genre: "一次遅れ",
    difficulty: 2,
    format: "choice",
    prompt: "\\(G(s)=\\frac{1}{s+1}\\) の単位インパルス応答を選べ。",
    answer: "\\(e^{-t}\\)",
    options: ["\\(e^{-t}\\)", "\\(1-e^{-t}\\)", "\\(t\\)", "\\(\\sin t\\)"],
    formula: "\\mathcal{L}^{-1}\\left\\{\\frac{1}{s+1}\\right\\}=e^{-t}",
    steps: ["インパルス入力はs領域で1。", "\\(Y(s)=G(s)\\)。", "基本対から \\(e^{-t}\\)。"],
    explanation: "1−e^{-t}は同じ系のステップ応答。",
    source: "scope-zip",
  },
  {
    id: "smart-q-transfer-7",
    topic: "transfer",
    genre: "一次遅れ",
    difficulty: 2,
    format: "choice",
    prompt: "\\(G(s)=\\frac{1}{s+1}\\) の単位ステップ応答を選べ。",
    answer: "\\(1-e^{-t}\\)",
    options: ["\\(e^{-t}\\)", "\\(1-e^{-t}\\)", "\\(te^{-t}\\)", "\\(1+e^{-t}\\)"],
    formula: "Y(s)=\\frac{1}{s(s+1)}=\\frac{1}{s}-\\frac{1}{s+1}",
    steps: ["入力 \\(\\frac{1}{s}\\) を掛ける。", "部分分数分解する。", "各項を逆変換する。"],
    explanation: "t=0で0、t→∞で1になることでも確認できる。",
    source: "scope-zip",
  },
  {
    id: "smart-q-inverse-1",
    topic: "inverse-laplace",
    genre: "単根",
    difficulty: 1,
    format: "choice",
    prompt: "\\(\\frac{1}{s(s+1)}\\) の逆ラプラス変換を選べ。",
    answer: "\\(1-e^{-t}\\)",
    options: ["\\(1-e^{-t}\\)", "\\(e^{-t}\\)", "\\(1+e^{-t}\\)", "\\(t-e^{-t}\\)"],
    formula: "\\frac{1}{s(s+1)}=\\frac{1}{s}-\\frac{1}{s+1}",
    steps: ["\\(\\frac{A}{s}+\\frac{B}{s+1}\\) と置く。", "\\(s=0\\) で \\(A=1\\)、\\(s=-1\\) で \\(B=-1\\)。", "1と \\(e^{-t}\\) へ戻す。"],
    explanation: "ヘビサイド法の最小例。",
    source: "scope-zip",
  },
  {
    id: "smart-q-inverse-2",
    topic: "inverse-laplace",
    genre: "重根",
    difficulty: 3,
    format: "choice",
    prompt: "\\(\\frac{s+2}{s(s+1)^2}\\) の逆ラプラス変換を選べ。",
    answer: "\\(2-2e^{-t}-te^{-t}\\)",
    options: ["\\(2-2e^{-t}-te^{-t}\\)", "\\(2-e^{-t}-2te^{-t}\\)", "\\(1-2e^{-t}-te^{-t}\\)", "\\(2+2e^{-t}+te^{-t}\\)"],
    formula: "\\frac{s+2}{s(s+1)^2}=\\frac{2}{s}-\\frac{2}{s+1}-\\frac{1}{(s+1)^2}",
    steps: ["\\(\\frac{A}{s}+\\frac{B}{s+1}+\\frac{C}{(s+1)^2}\\) と置く。", "\\(A=2\\)、\\(B=-2\\)、\\(C=-1\\)。", "\\(\\frac{1}{(s+1)^2}\\) は \\(te^{-t}\\)。"],
    explanation: "重根では \\(\\frac{1}{s+1}\\) と \\(\\frac{1}{(s+1)^2}\\) の両方が必要。",
    source: "scope-zip",
  },
  {
    id: "smart-q-inverse-3",
    topic: "inverse-laplace",
    genre: "複素根",
    difficulty: 1,
    format: "choice",
    prompt: "\\(\\frac{1}{s^2+1}\\) の逆ラプラス変換を選べ。",
    answer: "\\(\\sin t\\)",
    options: ["\\(\\sin t\\)", "\\(\\cos t\\)", "\\(e^{-t}\\)", "\\(t\\)"],
    formula: "\\mathcal{L}\\{\\sin t\\}=\\frac{1}{s^2+1}",
    steps: ["ω=1の正弦変換対と照合する。"],
    explanation: "分子がsならcos、分子がωならsin。",
    source: "scope-zip",
  },
  {
    id: "smart-q-inverse-4",
    topic: "inverse-laplace",
    genre: "複素根",
    difficulty: 2,
    format: "choice",
    prompt: "\\(\\frac{s+2}{s^2+1}\\) の逆ラプラス変換を選べ。",
    answer: "\\(\\cos t+2\\sin t\\)",
    options: ["\\(\\cos t+2\\sin t\\)", "\\(2\\cos t+\\sin t\\)", "\\(e^{-t}+2\\sin t\\)", "\\(\\cos 2t+\\sin t\\)"],
    formula: "\\frac{s+2}{s^2+1}=\\frac{s}{s^2+1}+2\\frac{1}{s^2+1}",
    steps: ["分子をsと定数2に分ける。", "s項はcos、定数項は2sin。"],
    explanation: "線形性で項ごとに逆変換する。",
    source: "scope-zip",
  },
  {
    id: "smart-q-inverse-5",
    topic: "inverse-laplace",
    genre: "平方完成",
    difficulty: 2,
    format: "choice",
    prompt: "\\(\\frac{1}{s^2+2s+5}\\) の逆ラプラス変換を選べ。",
    answer: "\\(\\frac{1}{2}e^{-t}\\sin 2t\\)",
    options: ["\\(\\frac{1}{2}e^{-t}\\sin 2t\\)", "\\(e^{-t}\\sin 2t\\)", "\\(\\frac{1}{2}e^{-2t}\\sin t\\)", "\\(e^{-t}\\cos 2t\\)"],
    formula: "s^2+2s+5=(s+1)^2+2^2",
    steps: ["分母を \\((s+1)^2+4\\) へ平方完成する。", "分子1を \\(\\frac{1}{2}\\times2\\) とみなす。", "減衰正弦の変換対を使う。"],
    explanation: "\\(\\sin\\) の変換対は分子 \\(\\omega\\) が必要なので \\(\\frac{1}{2}\\) が付く。",
    source: "scope-zip",
  },
  {
    id: "smart-q-inverse-6",
    topic: "inverse-laplace",
    genre: "実根＋複素根",
    difficulty: 3,
    format: "choice",
    prompt: "\\(\\frac{1}{(s+1)(s^2+2s+2)}\\) の逆ラプラス変換を選べ。",
    answer: "\\(e^{-t}-e^{-t}\\cos t\\)",
    options: ["\\(e^{-t}-e^{-t}\\cos t\\)", "\\(e^{-t}+e^{-t}\\cos t\\)", "\\(e^{-t}-\\sin t\\)", "\\(1-e^{-t}\\cos t\\)"],
    formula: "\\frac{1}{(s+1)(s^2+2s+2)}=\\frac{1}{s+1}-\\frac{s+1}{(s+1)^2+1}",
    steps: ["\\(\\frac{A}{s+1}+\\frac{Bs+C}{s^2+2s+2}\\) と置く。", "\\(A=1\\)、\\(B=-1\\)、\\(C=-1\\)。", "分子を \\(-(s+1)\\) へまとめる。"],
    explanation: "同じe^{-t}を持つ指数項と減衰余弦項の差になる。",
    source: "scope-zip",
  },
  {
    id: "smart-q-inverse-7",
    topic: "inverse-laplace",
    genre: "重根＋複素根",
    difficulty: 3,
    format: "choice",
    prompt: "\\(\\frac{1}{s^2(s^2+1)}\\) の逆ラプラス変換を選べ。",
    answer: "\\(t-\\sin t\\)",
    options: ["\\(t-\\sin t\\)", "\\(t+\\sin t\\)", "\\(1-\\cos t\\)", "\\(te^{-t}\\)"],
    formula: "\\frac{1}{s^2(s^2+1)}=\\frac{1}{s^2}-\\frac{1}{s^2+1}",
    steps: ["\\(\\frac{A}{s^2}+\\frac{B}{s}+\\frac{Cs+D}{s^2+1}\\) と置く。", "\\(A=1\\)、\\(B=C=0\\)、\\(D=-1\\)。", "\\(t\\) と \\(\\sin t\\) へ戻す。"],
    explanation: "偶関数なので \\(\\frac{1}{s}\\) と \\(\\frac{s}{s^2+1}\\) の係数が0になることも確認できる。",
    source: "scope-zip",
  },
  {
    id: "smart-q-inverse-8",
    topic: "inverse-laplace",
    genre: "部分分数の形",
    difficulty: 2,
    format: "choice",
    prompt: "分母に \\(s(s+1)^2\\) を持つ式の正しい部分分数の形を選べ。",
    answer: "\\(\\frac{A}{s}+\\frac{B}{s+1}+\\frac{C}{(s+1)^2}\\)",
    options: ["\\(\\frac{A}{s}+\\frac{B}{s+1}+\\frac{C}{(s+1)^2}\\)", "\\(\\frac{A}{s}+\\frac{B}{(s+1)^2}\\)", "\\(\\frac{As+B}{s(s+1)^2}\\)", "\\(\\frac{A}{s^2}+\\frac{B}{s+1}\\)"],
    steps: ["\\(s\\) は単根なので \\(\\frac{A}{s}\\)。", "\\(s=-1\\) は2重根なので1次と2次の両項を置く。"],
    explanation: "重根の次数分だけ項を並べる。",
    source: "scope-zip",
  },
  {
    id: "smart-q-inverse-9",
    topic: "inverse-laplace",
    genre: "ヘビサイド法",
    difficulty: 2,
    format: "text",
    prompt: "単根pに対応する部分分数係数Aを求めるヘビサイド法の式を書け。",
    answer: "\\(A=\\lim_{s\\to p}(s-p)F(s)\\)",
    keywords: ["lim", "s-p", "F"],
    minKeywords: 3,
    formula: "A=\\lim_{s\\to p}(s-p)F(s)",
    steps: ["求めたい因子(s−p)をF(s)へ掛ける。", "sを極pへ近づける。"],
    explanation: "単根だけにそのまま使える。重根の下位係数には微分が必要。",
    source: "scope-zip",
  },
  {
    id: "smart-q-response-1",
    topic: "response-stability",
    genre: "極",
    difficulty: 1,
    format: "text",
    prompt: "伝達関数の極を一文で定義せよ。",
    answer: "伝達関数の分母を0にするsの値",
    accepted: ["分母を0にするs", "分母=0の解"],
    keywords: ["分母", "0", "s"],
    minKeywords: 2,
    steps: ["\\(G(s)=\\frac{N(s)}{D(s)}\\) と置く。", "\\(D(s)=0\\) の解を求める。"],
    explanation: "極は時間応答の指数・振動・収束を決める。",
    source: "past2-overlap",
  },
  {
    id: "smart-q-response-2",
    topic: "response-stability",
    genre: "安定判別",
    difficulty: 1,
    format: "choice",
    prompt: "この授業資料で安定と判定する極配置を選べ。",
    answer: "全ての極の実部が負",
    options: ["全ての極の実部が負", "極が1つでも虚軸上", "右半平面の極が1つ", "全ての極の実部が正"],
    formula: "\\operatorname{Re}(p_i)<0\\ \\text{for all }i",
    steps: ["全ての極を求める。", "複素平面の左半平面に全て入るか確認する。"],
    explanation: "虚軸上は持続振動または非収束なので安定扱いにしない。",
    source: "scope-zip",
  },
  {
    id: "smart-q-response-3",
    topic: "response-stability",
    genre: "安定判別",
    difficulty: 1,
    format: "choice",
    prompt: "\\(G(s)=\\frac{1}{s-1}\\) の極と安定性を選べ。",
    answer: "極1・不安定",
    options: ["極1・不安定", "極−1・安定", "極0・安定", "極±j・不安定"],
    formula: "s-1=0\\Rightarrow s=1",
    steps: ["分母を0にする。", "s=1は右半平面。"],
    explanation: "応答にe^tが現れ発散する。",
    source: "scope-zip",
  },
  {
    id: "smart-q-response-4",
    topic: "response-stability",
    genre: "安定判別",
    difficulty: 1,
    format: "choice",
    prompt: "\\(G(s)=\\frac{1}{s^2+1}\\) の極と安定性を選べ。",
    answer: "極±j・不安定",
    options: ["極±j・不安定", "極±1・安定", "極−1±j・安定", "極0・安定"],
    formula: "s^2+1=0\\Rightarrow s=\\pm j",
    steps: ["s²=−1。", "極は虚軸上の±j。", "応答は持続振動し収束しない。"],
    explanation: "この資料では虚軸上の極を安定に含めない。",
    source: "scope-zip",
  },
  {
    id: "smart-q-response-5",
    topic: "response-stability",
    genre: "安定判別",
    difficulty: 2,
    format: "choice",
    prompt: "\\(G(s)=\\frac{1}{(s+1)^2+1}\\) の極と安定性を選べ。",
    answer: "極−1±j・安定",
    options: ["極−1±j・安定", "極1±j・不安定", "極±j・不安定", "極−1・安定"],
    formula: "(s+1)^2+1=0\\Rightarrow s=-1\\pm j",
    steps: ["(s+1)²=−1。", "s=−1±j。", "両方の実部が−1。"],
    explanation: "時間応答は減衰振動して0へ収束する。",
    source: "scope-zip",
  },
  {
    id: "smart-q-response-6",
    topic: "response-stability",
    genre: "高次系",
    difficulty: 2,
    format: "choice",
    prompt: "\\(\\frac{1}{s^3-3s^2+2s}\\) の極と安定性を選べ。",
    answer: "極0,1,2・不安定",
    options: ["極0,1,2・不安定", "極0,−1,−2・安定", "極−1,−2,−3・安定", "極±j,0・安定"],
    formula: "s^3-3s^2+2s=s(s-1)(s-2)",
    steps: ["sでくくる。", "s²−3s+2=(s−1)(s−2)。", "右半平面極1,2を含む。"],
    explanation: "1つでも右半平面極があれば不安定。",
    source: "scope-zip",
  },
  {
    id: "smart-q-response-7",
    topic: "response-stability",
    genre: "高次系",
    difficulty: 2,
    format: "choice",
    prompt: "\\(\\frac{1}{s^3+s^2+s+1}\\) の極と安定性を選べ。",
    answer: "極−1,±j・不安定",
    options: ["極−1,±j・不安定", "極−1,−1,−1・安定", "極1,±j・不安定", "極−1±j・安定"],
    formula: "s^3+s^2+s+1=(s+1)(s^2+1)",
    steps: ["前半と後半をまとめて因数分解する。", "極は−1と±j。", "虚軸上の極を含む。"],
    explanation: "左半平面極があっても、他の全ての極も確認する。",
    source: "scope-zip",
  },
  {
    id: "smart-q-response-8",
    topic: "response-stability",
    genre: "応答指標",
    difficulty: 1,
    format: "choice",
    prompt: "応答が定常値の±5%内へ入り、その後外へ出なくなるまでの時間は？",
    answer: "整定時間",
    options: ["整定時間", "立ち上がり時間", "ピーク時間", "むだ時間"],
    steps: ["上下5%の整定帯を確認する。", "最後に帯へ入る時刻を読む。"],
    explanation: "英語はsettling time、記号はts。",
    source: "past2-overlap",
  },
  {
    id: "smart-q-response-9",
    topic: "response-stability",
    genre: "応答指標",
    difficulty: 1,
    format: "choice",
    prompt: "最大値と定常値の差を定常値で割った指標は？",
    answer: "オーバーシュート",
    options: ["オーバーシュート", "時定数", "立ち上がり時間", "減衰係数"],
    formula: "M_p=\\frac{y_{\\max}-y_\\infty}{y_\\infty}\\times100\\%",
    steps: ["最大値から定常値を引く。", "定常値で割り百分率にする。"],
    explanation: "減衰性を評価する代表指標。",
    source: "past2-overlap",
  },
  {
    id: "smart-q-feedback-1",
    topic: "feedback",
    genre: "閉ループ伝達関数",
    difficulty: 1,
    format: "choice",
    prompt: "前向きG、帰還Hの負帰還系の閉ループ伝達関数を選べ。",
    answer: "\\(\\frac{G}{1+GH}\\)",
    options: ["\\(\\frac{G}{1+GH}\\)", "\\(\\frac{G}{1-GH}\\)", "\\(\\frac{GH}{1+G}\\)", "\\(G+H\\)"],
    formula: "G_{cl}=\\frac{G}{1+GH}",
    steps: ["\\(Y=G(U-HY)\\) と書く。", "\\(Y+GHY=GU\\)。", "\\(\\frac{Y}{U}=\\frac{G}{1+GH}\\)。"],
    explanation: "負帰還なのに分母はプラスになる点が頻出。",
    source: "scope-zip",
  },
  {
    id: "smart-q-feedback-2",
    topic: "feedback",
    genre: "特性方程式",
    difficulty: 1,
    format: "text",
    prompt: "負帰還系の特性方程式をG(s)、H(s)で書け。",
    answer: "\\(1+G(s)H(s)=0\\)",
    accepted: ["1+GH=0", "1+G(s)H(s)=0"],
    keywords: ["1", "G", "H", "0"],
    minKeywords: 4,
    formula: "1+G(s)H(s)=0",
    steps: ["閉ループ伝達関数の分母を取り出す。", "分母を0と置く。"],
    explanation: "整理して得た多項式の根が閉ループ極。",
    source: "scope-zip",
  },
  {
    id: "smart-q-feedback-3",
    topic: "feedback",
    genre: "ゲインK",
    difficulty: 2,
    format: "choice",
    prompt: "\\(\\frac{K}{s-1}\\) を単位負帰還したときの閉ループ伝達関数を選べ。",
    answer: "\\(\\frac{K}{s-1+K}\\)",
    options: ["\\(\\frac{K}{s-1+K}\\)", "\\(\\frac{K}{s-1-K}\\)", "\\(\\frac{1}{s-1+K}\\)", "\\(\\frac{K(s-1)}{1+K}\\)"],
    formula: "\\frac{\\frac{K}{s-1}}{1+\\frac{K}{s-1}}=\\frac{K}{s-1+K}",
    steps: ["\\(\\frac{G}{1+G}\\) へ \\(G=\\frac{K}{s-1}\\) を代入。", "分子分母へ \\(s-1\\) を掛ける。"],
    explanation: "閉ループ極は1−K。",
    source: "scope-zip",
  },
  {
    id: "smart-q-feedback-4",
    topic: "feedback",
    genre: "ゲインK",
    difficulty: 2,
    format: "choice",
    prompt: "前問の系が安定になるKの範囲を選べ。",
    context: "閉ループ極は \\(s=1-K\\)。",
    answer: "\\(K>1\\)",
    options: ["\\(K>1\\)", "\\(K\\ge1\\)", "\\(K<1\\)", "\\(K>0\\)"],
    formula: "1-K<0\\Rightarrow K>1",
    steps: ["安定条件は極の実部<0。", "1−K<0を解く。", "K=1は極0なので除く。"],
    explanation: "境界を含めない不等号が重要。",
    source: "scope-zip",
  },
  {
    id: "smart-q-feedback-5",
    topic: "feedback",
    genre: "ゲインK",
    difficulty: 2,
    format: "choice",
    prompt: "\\(\\frac{K}{s(s+1)}\\) を単位負帰還した閉ループ伝達関数を選べ。",
    answer: "\\(\\frac{K}{s^2+s+K}\\)",
    options: ["\\(\\frac{K}{s^2+s+K}\\)", "\\(\\frac{K}{s^2+s-K}\\)", "\\(\\frac{1}{s^2+s+K}\\)", "\\(\\frac{K}{s+1+K}\\)"],
    formula: "\\frac{\\frac{K}{s(s+1)}}{1+\\frac{K}{s(s+1)}}=\\frac{K}{s^2+s+K}",
    steps: ["\\(\\frac{G}{1+G}\\) へ代入する。", "分子分母へ \\(s(s+1)\\) を掛ける。"],
    explanation: "特性方程式はs²+s+K=0。",
    source: "scope-zip",
  },
  {
    id: "smart-q-feedback-6",
    topic: "feedback",
    genre: "ゲインK",
    difficulty: 3,
    format: "choice",
    prompt: "\\(\\frac{K}{s^2+s+K}\\) が安定となるKの範囲を選べ。",
    answer: "\\(K>0\\)",
    options: ["\\(K>0\\)", "\\(K\\ge0\\)", "\\(K>\\frac{1}{4}\\)", "\\(K<0\\)"],
    formula: "s=\\frac{-1\\pm\\sqrt{1-4K}}{2}",
    steps: ["K<0では正の実極が生じる。", "K=0では極0を含む。", "K>0では全極の実部が負。"],
    explanation: "\\(K=\\frac{1}{4}\\) は極の種類が変わる境界だが、安定境界ではない。",
    source: "scope-zip",
  },
  {
    id: "smart-q-feedback-7",
    topic: "feedback",
    genre: "極の移動",
    difficulty: 2,
    format: "choice",
    prompt: "\\(s^2+s+K=0\\) で \\(K=\\frac{1}{4}\\) のときの極を選べ。",
    answer: "\\(s=-\\frac{1}{2}\\) の重極",
    options: ["\\(s=-\\frac{1}{2}\\) の重極", "\\(s=\\frac{1}{2}\\) の重極", "\\(s=\\pm\\frac{j}{2}\\)", "\\(s=0,-1\\)"],
    formula: "s=\\frac{-1\\pm\\sqrt{1-4K}}{2}",
    steps: ["\\(K=\\frac{1}{4}\\) を代入する。", "平方根の中が0。", "2つの極が \\(-\\frac{1}{2}\\) で一致。"],
    explanation: "\\(K>\\frac{1}{4}\\) では実部 \\(-\\frac{1}{2}\\) の共役複素極になる。",
    source: "scope-zip",
  },
  {
    id: "smart-q-block-1",
    topic: "block-diagram",
    genre: "直列結合",
    difficulty: 1,
    format: "choice",
    prompt: "G1とG2の直列結合の等価伝達関数を選べ。",
    answer: "\\(G_2G_1\\)",
    options: ["\\(G_2G_1\\)", "\\(G_1+G_2\\)", "\\(\\frac{G_1}{G_2}\\)", "\\(\\frac{G_1}{1+G_2}\\)"],
    formula: "Y=G_2(G_1U)=G_2G_1U",
    steps: ["中間信号をG1Uとする。", "G2へ代入して積にする。"],
    explanation: "スカラー伝達関数なら掛ける順序は結果に影響しない。",
    source: "past2-overlap",
  },
  {
    id: "smart-q-block-2",
    topic: "block-diagram",
    genre: "並列結合",
    difficulty: 1,
    format: "choice",
    prompt: "同じ入力をG1、G2へ入れて両出力を加える並列結合は？",
    answer: "\\(G_1+G_2\\)",
    options: ["\\(G_1+G_2\\)", "\\(G_1G_2\\)", "\\(G_1-G_2\\)", "\\(\\frac{G_1}{1+G_2}\\)"],
    formula: "Y=G_1U+G_2U=(G_1+G_2)U",
    steps: ["各枝の出力を書く。", "共通入力Uでくくる。"],
    explanation: "加え合わせ点がマイナスならG1−G2になる。",
    source: "past2-overlap",
  },
  {
    id: "smart-q-block-3",
    topic: "block-diagram",
    genre: "帰還結合",
    difficulty: 2,
    format: "choice",
    prompt: "前向きG1、帰還G2の負帰還結合を1ブロックへまとめよ。",
    answer: "\\(\\frac{G_1}{1+G_1G_2}\\)",
    options: ["\\(\\frac{G_1}{1+G_1G_2}\\)", "\\(\\frac{G_1}{1-G_1G_2}\\)", "\\(\\frac{G_1G_2}{1+G_1}\\)", "\\(G_1+G_2\\)"],
    formula: "G_{eq}=\\frac{G_1}{1+G_1G_2}",
    steps: ["帰還信号はG2Y。", "Y=G1(U−G2Y)を解く。"],
    explanation: "過去問2のブロック線図形式とも直接重なる範囲。",
    source: "past2-overlap",
  },
  {
    id: "smart-q-block-4",
    topic: "block-diagram",
    genre: "加え合わせ点移動",
    difficulty: 2,
    format: "choice",
    prompt: "加え合わせ点をGの後ろから前へ移す。移動した枝に置く要素は？",
    answer: "\\(\\frac{1}{G}\\)",
    options: ["\\(\\frac{1}{G}\\)", "\\(G\\)", "\\(1+G\\)", "何も置かない"],
    steps: ["元はG通過後に枝信号を加えている。", "前へ移すと枝信号もGを通る。", "事前に \\(\\frac{1}{G}\\) で相殺する。"],
    explanation: "逆向き、前から後へ移すときはGを置く。",
    source: "scope-zip",
  },
  {
    id: "smart-q-block-5",
    topic: "block-diagram",
    genre: "引き出し点移動",
    difficulty: 2,
    format: "choice",
    prompt: "引き出し点をGの後ろから前へ移す。引き出し枝に置く要素は？",
    answer: "\\(G\\)",
    options: ["\\(G\\)", "\\(\\frac{1}{G}\\)", "\\(1-G\\)", "何も置かない"],
    steps: ["元はG通過後の信号を引き出している。", "前へ移した枝でも同じ信号を得るためGを置く。"],
    explanation: "加え合わせ点の移動規則と逆になりやすいので、信号を式で追う。",
    source: "scope-zip",
  },
  {
    id: "smart-q-block-6",
    topic: "block-diagram",
    genre: "複合簡約",
    difficulty: 3,
    format: "choice",
    prompt: "G2を前向き、G3を帰還とする負帰還ループをG1と直列にした等価伝達関数は？",
    answer: "\\(\\frac{G_1G_2}{1+G_2G_3}\\)",
    options: ["\\(\\frac{G_1G_2}{1+G_2G_3}\\)", "\\(\\frac{G_1G_2}{1-G_2G_3}\\)", "\\(\\frac{G_1}{1+G_2G_3}\\)", "\\(G_1+G_2+G_3\\)"],
    formula: "G_{eq}=G_1\\cdot\\frac{G_2}{1+G_2G_3}",
    steps: ["内側の負帰還ループを \\(\\frac{G_2}{1+G_2G_3}\\) へまとめる。", "外側の \\(G_1\\) と直列なので掛ける。"],
    explanation: "複雑な線図は内側のループから一つずつ簡約する。",
    source: "scope-zip",
  },
];

export const SMART_CONTROL_EXAM_FORMATS: SmartControlExamFormat[] = [
  {
    id: "smart-format-terms",
    title: "語群・用語穴埋め",
    description: "過去問1・3は制御系の名称や日英用語を語群から選ぶ形式。今回は範囲写真で確認できる入力、応答指標、極、安定性、帰還の用語だけを出す。",
    strategy: "日本語・記号・式を3点セットで覚える。",
  },
  {
    id: "smart-format-chain",
    title: "式を段階的に導く連続小問",
    description: "微分方程式→初期値0のラプラス変換→伝達関数→時間応答という流れで途中式を採点する形式。",
    strategy: "最終式だけでなく、変換前後の式を1行ずつ残す。",
  },
  {
    id: "smart-format-inverse",
    title: "部分分数・逆ラプラス",
    description: "根の種類を判別し、正しい部分分数形を立ててから基本変換対へ戻す。",
    strategy: "因数分解→分解形→係数→変換対の順番を崩さない。",
  },
  {
    id: "smart-format-poles",
    title: "極の計算と安定判別",
    description: "極を求め、複素平面で左半平面・虚軸・右半平面を区別し、理由付きで安定性を答える。",
    strategy: "『極を列挙』と『全極の実部を確認』を別行で書く。",
  },
  {
    id: "smart-format-block",
    title: "ブロック線図の等価変換",
    description: "直列・並列・帰還を簡約し、加え合わせ点・引き出し点の移動規則を使う。過去問2・3の形式と重なる。",
    strategy: "内側のループから1個ずつ箱へ置き換える。",
  },
];

export const SMART_CONTROL_EXAMS: SmartControlExam[] = [
  {
    id: "smart-exam-1",
    title: "想定試験 01",
    subtitle: "一次遅れ・重根・K安定化",
    questions: [
      {
        id: "smart-exam-1-q1",
        section: "大問1｜用語と標準入力",
        points: 20,
        prompt: "単位インパルスと単位ステップのs領域表現を答え、立ち上がり時間tr・ピーク時間tp・整定時間tsをそれぞれ説明せよ。",
        answer: "インパルスは \\(1\\)、ステップは \\(\\frac{1}{s}\\)。\\(t_r\\) は立ち上がり、\\(t_p\\) は最大値到達、\\(t_s\\) は許容帯へ収まるまでの時間。",
        formula: "\\delta(t)\\leftrightarrow1,\\qquad 1\\leftrightarrow\\frac{1}{s}",
        steps: ["2つの入力を図の形と一緒に区別する。", "tr・tp・tsを応答曲線上の位置で説明する。"],
      },
      {
        id: "smart-exam-1-q2",
        section: "大問2｜逆ラプラス変換",
        points: 30,
        prompt: "\\(\\frac{s+3}{s(s+1)^2}\\) を部分分数分解し、逆ラプラス変換せよ。",
        answer: "\\(3-3e^{-t}-2te^{-t}\\)",
        formula: "\\frac{s+3}{s(s+1)^2}=\\frac{3}{s}-\\frac{3}{s+1}-\\frac{2}{(s+1)^2}",
        steps: ["\\(\\frac{A}{s}+\\frac{B}{s+1}+\\frac{C}{(s+1)^2}\\) と置く。", "\\(A=3\\)、\\(B=-3\\)、\\(C=-2\\)。", "\\(\\frac{1}{(s+1)^2}\\leftrightarrow te^{-t}\\) を使う。"],
      },
      {
        id: "smart-exam-1-q3",
        section: "大問3｜極と安定性",
        points: 25,
        prompt: "\\(G(s)=\\frac{1}{(s+2)(s-1)}\\) の極を求め、安定性を理由付きで答えよ。",
        answer: "極は−2, 1。右半平面極1を含むため不安定。",
        formula: "(s+2)(s-1)=0\\Rightarrow s=-2,1",
        steps: ["各因子を0と置く。", "全極の実部を確認する。"],
      },
      {
        id: "smart-exam-1-q4",
        section: "大問4｜フィードバック",
        points: 25,
        prompt: "\\(G(s)=\\frac{K}{s-1}\\) を単位負帰還する。閉ループ伝達関数と安定となるKの範囲を求めよ。",
        answer: "\\(G_{cl}=\\frac{K}{s-1+K}\\)、安定条件は \\(K>1\\)。",
        formula: "s=1-K<0\\Rightarrow K>1",
        steps: ["\\(\\frac{G}{1+G}\\) へ代入する。", "閉ループ極 \\(1-K\\) を求める。", "極を左半平面へ入れる。"],
      },
    ],
  },
  {
    id: "smart-exam-2",
    title: "想定試験 02",
    subtitle: "減衰振動・複素極・帰還線図",
    questions: [
      {
        id: "smart-exam-2-q1",
        section: "大問1｜過渡応答",
        points: 20,
        prompt: "過渡状態・定常状態・最大行き過ぎ量・5%整定帯をそれぞれ説明せよ。",
        answer: "過渡は定常へ至る途中、定常は十分時間後の状態。最大行き過ぎ量は定常値を超える最大割合、5%帯は0.95y∞〜1.05y∞。",
        formula: "M_p=\\frac{y_{max}-y_\\infty}{y_\\infty}\\times100\\%",
        steps: ["時間領域の区分を説明する。", "割合と帯を式で示す。"],
      },
      {
        id: "smart-exam-2-q2",
        section: "大問2｜逆ラプラス変換",
        points: 30,
        prompt: "\\(\\frac{2s+5}{s^2+2s+5}\\) を逆ラプラス変換せよ。",
        answer: "\\(2e^{-t}\\cos2t+\\frac{3}{2}e^{-t}\\sin2t\\)",
        formula: "\\frac{2(s+1)+3}{(s+1)^2+2^2}",
        steps: ["分母を(s+1)^2+4へ平方完成する。", "分子を2(s+1)+3へ分ける。", "減衰cosと減衰sinへ対応させる。"],
      },
      {
        id: "smart-exam-2-q3",
        section: "大問3｜極と安定性",
        points: 25,
        prompt: "\\(G(s)=\\frac{1}{s^2+4s+8}\\) の極を求め、安定性を判定せよ。",
        answer: "極は−2±2j。全ての実部が−2なので安定。",
        formula: "s^2+4s+8=(s+2)^2+2^2",
        steps: ["平方完成または解の公式を使う。", "複素極の実部を確認する。"],
      },
      {
        id: "smart-exam-2-q4",
        section: "大問4｜ブロック線図",
        points: 25,
        prompt: "G1とG2を直列にし、その全体へHを単位負帰還形で接続した等価伝達関数を求めよ。",
        answer: "\\(\\frac{G_1G_2}{1+G_1G_2H}\\)",
        formula: "G=G_1G_2\\Rightarrow G_{cl}=\\frac{G_1G_2}{1+G_1G_2H}",
        steps: ["直列部をG1G2へまとめる。", "負帰還公式へ代入する。"],
      },
    ],
  },
  {
    id: "smart-exam-3",
    title: "想定試験 03",
    subtitle: "液面系・混合根・ゲインK",
    questions: [
      {
        id: "smart-exam-3-q1",
        section: "大問1｜液面系",
        points: 20,
        prompt: "\\(C\\,\\frac{dH}{dt}=Q_i-Q_o\\)、\\(Q_o=\\frac{H}{R}\\) から \\(\\frac{H(s)}{Q_i(s)}\\) を導き、単位ステップ応答を求めよ。",
        answer: "\\(\\frac{H}{Q_i}=\\frac{R}{CRs+1}\\)、\\(h(t)=R\\left(1-e^{-\\frac{t}{CR}}\\right)\\)。",
        formula: "\\frac{H}{Q_i}=\\frac{R}{CRs+1}",
        steps: ["\\(Q_o=\\frac{H}{R}\\) を代入する。", "初期値0でラプラス変換する。", "\\(\\frac{1}{s}\\) を掛けて逆変換する。"],
      },
      {
        id: "smart-exam-3-q2",
        section: "大問2｜逆ラプラス変換",
        points: 30,
        prompt: "\\(\\frac{1}{s^2(s^2+4)}\\) を逆ラプラス変換せよ。",
        answer: "\\(\\frac{t}{4}-\\frac{1}{8}\\sin2t\\)",
        formula: "\\frac{1}{s^2(s^2+4)}=\\frac{1}{4s^2}-\\frac{1}{4(s^2+4)}",
        steps: ["偶関数の分解形を立てる。", "\\(\\frac{1}{s^2}\\leftrightarrow t\\)。", "\\(\\frac{1}{s^2+4}\\leftrightarrow\\frac{1}{2}\\sin2t\\)。"],
      },
      {
        id: "smart-exam-3-q3",
        section: "大問3｜高次系の安定性",
        points: 25,
        prompt: "\\(G(s)=\\frac{1}{s^3+s^2+4s+4}\\) の極と安定性を答えよ。",
        answer: "分母=(s+1)(s²+4)。極は−1, ±2j。虚軸上の極を含むため不安定。",
        formula: "s^3+s^2+4s+4=(s+1)(s^2+4)",
        steps: ["グループ分けして因数分解する。", "全極を列挙する。", "虚軸上の極を確認する。"],
      },
      {
        id: "smart-exam-3-q4",
        section: "大問4｜ゲインK",
        points: 25,
        prompt: "\\(G(s)=\\frac{K}{s(s+1)}\\) を単位負帰還する。閉ループ極を示し、安定なKの範囲を求めよ。",
        answer: "\\(G_{cl}=\\frac{K}{s^2+s+K}\\)、極は \\(\\frac{-1\\pm\\sqrt{1-4K}}{2}\\)、安定条件は \\(K>0\\)。",
        formula: "s=\\frac{-1\\pm\\sqrt{1-4K}}{2}",
        steps: ["閉ループ分母s²+s+Kを作る。", "解の公式を使う。", "K=0を除きK>0と判定する。"],
      },
    ],
  },
  {
    id: "smart-exam-4",
    title: "想定試験 04",
    subtitle: "応答分類・実根＋複素根・線図移動",
    questions: [
      {
        id: "smart-exam-4-q1",
        section: "大問1｜応答の概形",
        points: 20,
        prompt: "\\(\\frac{1}{s}\\)、\\(\\frac{1}{s+1}\\)、\\(\\frac{1}{s^2+1}\\)、\\(\\frac{1}{(s+1)^2+1}\\) の各伝達関数について、単位ステップ応答を非収束ランプ・単調収束・持続振動・減衰振動へ対応させよ。",
        answer: "\\(\\frac{1}{s}\\) →非収束ランプ、\\(\\frac{1}{s+1}\\) →単調収束、\\(\\frac{1}{s^2+1}\\) →持続振動、\\(\\frac{1}{(s+1)^2+1}\\) →減衰振動。",
        steps: ["各伝達関数の極を求める。", "極の位置から応答の形を決める。"],
      },
      {
        id: "smart-exam-4-q2",
        section: "大問2｜逆ラプラス変換",
        points: 30,
        prompt: "\\(\\frac{1}{(s+2)(s^2+2s+2)}\\) を逆ラプラス変換せよ。",
        answer: "\\(\\frac{1}{2}e^{-2t}-\\frac{1}{2}e^{-t}\\cos t+\\frac{1}{2}e^{-t}\\sin t\\)",
        formula: "\\frac{1}{2(s+2)}-\\frac{s}{2(s^2+2s+2)}",
        steps: ["\\(\\frac{A}{s+2}+\\frac{Bs+C}{s^2+2s+2}\\) と置く。", "\\(A=\\frac{1}{2}\\)、\\(B=-\\frac{1}{2}\\)、\\(C=0\\)。", "\\(-\\frac{s}{2}=-\\frac{s+1}{2}+\\frac{1}{2}\\) へ直す。"],
      },
      {
        id: "smart-exam-4-q3",
        section: "大問3｜不安定な複素極",
        points: 25,
        prompt: "\\(G(s)=\\frac{1}{s^2-2s+5}\\) の極を求め、安定性を判定せよ。",
        answer: "極は1±2j。実部が正なので不安定。",
        formula: "s^2-2s+5=(s-1)^2+2^2",
        steps: ["平方完成する。", "極の実部1を確認する。"],
      },
      {
        id: "smart-exam-4-q4",
        section: "大問4｜線図の移動規則",
        points: 25,
        prompt: "加え合わせ点と引き出し点をGの後ろから前へ移す場合、それぞれ移動枝へ置く要素を答え、理由を信号式で説明せよ。",
        answer: "加え合わせ点は \\(\\frac{1}{G}\\)、引き出し点は \\(G\\)。移動前後で各枝の信号値を等しく保つため。",
        formula: "\\text{summing: }\\frac{1}{G},\\qquad\\text{pickoff: }G",
        steps: ["元の枝信号を式で置く。", "移動後にGを通るか否かを比較する。", "不足または過剰なGを補正する。"],
      },
    ],
  },
  {
    id: "smart-exam-5",
    title: "想定試験 05",
    subtitle: "整定指標・部分分数・境界極",
    questions: [
      {
        id: "smart-exam-5-q1",
        section: "大問1｜応答指標",
        points: 20,
        prompt: "応答曲線上の定常値y∞、最大値ymax、オーバーシュートMp、整定時間tsの関係を式と文章で説明せよ。",
        answer: "\\(M_p=\\frac{y_{\\max}-y_\\infty}{y_\\infty}\\times100\\%\\)。\\(t_s\\) は応答が \\(0.95y_\\infty\\)〜\\(1.05y_\\infty\\) へ入り続ける最初の時刻。",
        formula: "M_p=\\frac{y_{max}-y_\\infty}{y_\\infty}\\times100\\%",
        steps: ["最大値と定常値を区別する。", "5%帯の上下限を式で書く。"],
      },
      {
        id: "smart-exam-5-q2",
        section: "大問2｜逆ラプラス変換",
        points: 30,
        prompt: "\\(\\frac{s+4}{s(s+2)}\\) を部分分数分解し、逆ラプラス変換せよ。",
        answer: "\\(2-e^{-2t}\\)",
        formula: "\\frac{s+4}{s(s+2)}=\\frac{2}{s}-\\frac{1}{s+2}",
        steps: ["\\(\\frac{A}{s}+\\frac{B}{s+2}\\) と置く。", "\\(A=2\\)、\\(B=-1\\)。", "基本対へ戻す。"],
      },
      {
        id: "smart-exam-5-q3",
        section: "大問3｜重極と安定性",
        points: 25,
        prompt: "\\(G(s)=\\frac{1}{s^3+2s^2+s}\\) の極を求め、安定性を判定せよ。",
        answer: "分母=s(s+1)²。極は0, −1（重極）。虚軸上の極0を含むため不安定。",
        formula: "s^3+2s^2+s=s(s+1)^2",
        steps: ["sでくくる。", "残りを完全平方にする。", "虚軸上の極を確認する。"],
      },
      {
        id: "smart-exam-5-q4",
        section: "大問4｜安定境界",
        points: 25,
        prompt: "\\(\\frac{K}{s^2+s+K}\\) について \\(K<0\\)、\\(K=0\\)、\\(0<K<\\frac{1}{4}\\)、\\(K=\\frac{1}{4}\\)、\\(K>\\frac{1}{4}\\) の極の種類と安定性を整理せよ。",
        answer: "\\(K<0\\) は正の実極を含み不安定、\\(K=0\\) は極0で不安定、\\(0<K<\\frac{1}{4}\\) は負の異なる実極で安定、\\(K=\\frac{1}{4}\\) は \\(-\\frac{1}{2}\\) の重極で安定、\\(K>\\frac{1}{4}\\) は実部 \\(-\\frac{1}{2}\\) の複素極で安定。",
        formula: "s=\\frac{-1\\pm\\sqrt{1-4K}}{2}",
        steps: ["判別式1−4Kの符号を見る。", "各場合で極の実部を確認する。"],
      },
    ],
  },
  {
    id: "smart-exam-6",
    title: "想定試験 06",
    subtitle: "総合・混合根・複合ブロック",
    questions: [
      {
        id: "smart-exam-6-q1",
        section: "大問1｜解法分類",
        points: 20,
        prompt: "逆ラプラス変換で、単根・重根・既約2次因子・単根と既約2次因子の混在ごとに、置くべき部分分数の分子と項数を説明せよ。",
        answer: "単根は \\(\\frac{\\text{定数}}{\\text{一次因子}}\\)、m重根は1乗からm乗まで全項、既約2次因子は \\(\\frac{\\text{一次式}}{\\text{二次因子}}\\)、混在時はそれらを全て並べる。",
        steps: ["分母を因数分解する。", "各因子の種類と重複度を読む。", "未定係数の形を漏れなく置く。"],
      },
      {
        id: "smart-exam-6-q2",
        section: "大問2｜逆ラプラス変換",
        points: 30,
        prompt: "\\(\\frac{s+1}{s(s^2+2s+2)}\\) を逆ラプラス変換せよ。",
        answer: "\\(\\frac{1}{2}-\\frac{1}{2}e^{-t}\\cos t+\\frac{1}{2}e^{-t}\\sin t\\)",
        formula: "\\frac{1}{2s}-\\frac{s}{2(s^2+2s+2)}",
        steps: ["\\(\\frac{A}{s}+\\frac{Bs+C}{s^2+2s+2}\\) と置く。", "\\(A=\\frac{1}{2}\\)、\\(B=-\\frac{1}{2}\\)、\\(C=0\\)。", "\\(-\\frac{s}{2}=-\\frac{s+1}{2}+\\frac{1}{2}\\) へ直す。"],
      },
      {
        id: "smart-exam-6-q3",
        section: "大問3｜複素極の安定性",
        points: 25,
        prompt: "分母が \\((s+1)(s^2+4s+13)\\) の系の極を求め、安定性を判定せよ。",
        answer: "極は−1, −2±3j。全極の実部が負なので安定。",
        formula: "s^2+4s+13=(s+2)^2+3^2",
        steps: ["一次因子から−1。", "2次因子を平方完成する。", "3つの極の実部を確認する。"],
      },
      {
        id: "smart-exam-6-q4",
        section: "大問4｜複合ブロック線図",
        points: 25,
        prompt: "G2を前向き、G3を帰還とする負帰還ループをまず簡約し、それをG1と直列接続した全体の伝達関数を求めよ。",
        answer: "内側は \\(\\frac{G_2}{1+G_2G_3}\\)、全体は \\(\\frac{G_1G_2}{1+G_2G_3}\\)。",
        formula: "G_{eq}=G_1\\frac{G_2}{1+G_2G_3}",
        steps: ["最内側の帰還ループを1ブロックにする。", "外側の直列G1を掛ける。"],
      },
    ],
  },
];

export const SMART_CONTROL_PENDING_SOURCES = [] as const;
