export const SMART_CONTROL_DIAGRAM_IDS = [
  "response-figure51",
  "response-figure52",
  "response-figure53",
  "pole-plane",
  "negative-feedback",
  "positive-feedback",
  "series-block",
  "parallel-block",
  "summing-shift",
  "pickoff-shift",
  "block-shifts",
  "series-feedback",
  "nested-feedback",
] as const;

export type SmartControlDiagramId = (typeof SMART_CONTROL_DIAGRAM_IDS)[number];

export const SMART_CONTROL_DIAGRAM_SOLUTION_TEX = {
  "negative-feedback": "\\frac{G(s)}{1+G(s)H(s)}",
  "positive-feedback": "\\frac{G(s)}{1-G(s)H(s)}",
  "series-feedback": "\\frac{G_1(s)G_2(s)}{1+G_1(s)G_2(s)H(s)}",
  "series-block": "G_{\\mathrm{eq}}=G_2G_1",
  "parallel-block": "G_{\\mathrm{eq}}=G_1+G_2",
  "summing-shift": "G^{-1}",
  "pickoff-shift": "G",
  "block-shifts": "\\text{加え合わせ点： }G^{-1},\\qquad\\text{引き出し点： }G",
  "nested-feedback": "G_{\\mathrm{eq}}=\\frac{G_1G_2}{1+G_2G_3}",
} as const satisfies Partial<Record<SmartControlDiagramId, string>>;

/** Exact problem-to-figure links. Topic-level inference can show a misleading figure. */
export const SMART_CONTROL_DIAGRAM_BY_ITEM_ID = {
  "smart-pole-definition": "pole-plane",
  "smart-stability-rule": "pole-plane",
  "smart-response-times": "response-figure51",
  "smart-overshoot": "response-figure51",
  "smart-settling-band": "response-figure51",
  "smart-negative-feedback": "negative-feedback",
  "smart-positive-feedback": "positive-feedback",
  "smart-characteristic-equation": "negative-feedback",
  "smart-gain-first-order": "negative-feedback",
  "smart-gain-second-order": "negative-feedback",
  "smart-series-block": "series-block",
  "smart-parallel-block": "parallel-block",
  "smart-summing-shift": "summing-shift",
  "smart-pickoff-shift": "pickoff-shift",
  "textbook-response-transient-steady-boundary": "response-figure51",
  "textbook-response-rise-time": "response-figure51",
  "textbook-response-rapidity": "response-figure51",
  "textbook-response-delay-time": "response-figure51",
  "textbook-response-overshoot": "response-figure51",
  "textbook-response-peak-time": "response-figure51",
  "textbook-response-damping": "response-figure51",
  "textbook-response-settling-time": "response-figure51",
  "textbook-response-graph-levels": "response-figure51",
  "textbook-response-five-percent-band": "response-figure51",
  "textbook-response-figure-51-map": "response-figure51",
  "textbook-response-figure-52": "response-figure52",
  "textbook-response-figure-53": "response-figure53",
  "textbook-response-no-overshoot-caution": "response-figure52",
  "textbook-response-normalized-overshoot": "response-figure53",
  "smart-q-response-1": "pole-plane",
  "smart-q-response-2": "pole-plane",
  "smart-q-response-3": "pole-plane",
  "smart-q-response-4": "pole-plane",
  "smart-q-response-5": "pole-plane",
  "smart-q-response-6": "pole-plane",
  "smart-q-response-7": "pole-plane",
  "smart-q-response-8": "response-figure51",
  "smart-q-response-9": "response-figure51",
  "smart-q-feedback-1": "negative-feedback",
  "smart-q-feedback-2": "negative-feedback",
  "smart-q-feedback-3": "negative-feedback",
  "smart-q-feedback-4": "negative-feedback",
  "smart-q-feedback-5": "negative-feedback",
  "smart-q-feedback-6": "negative-feedback",
  "smart-q-feedback-7": "pole-plane",
  "smart-q-block-1": "series-block",
  "smart-q-block-2": "parallel-block",
  "smart-q-block-3": "negative-feedback",
  "smart-q-block-4": "summing-shift",
  "smart-q-block-5": "pickoff-shift",
  "smart-q-block-6": "nested-feedback",
  "textbook-response-q01-steady-characteristic": "response-figure51",
  "textbook-response-q02-transient-characteristic": "response-figure51",
  "textbook-response-q03-steady-value": "response-figure51",
  "textbook-response-q04-rise-time": "response-figure51",
  "textbook-response-q05-delay-time": "response-figure51",
  "textbook-response-q06-rapidity": "response-figure51",
  "textbook-response-q07-overshoot-formula": "response-figure51",
  "textbook-response-q08-peak-time": "response-figure51",
  "textbook-response-q09-damping": "response-figure51",
  "textbook-response-q10-settling-time": "response-figure51",
  "textbook-response-q11-level-order": "response-figure51",
  "textbook-response-q12-band-numeric": "response-figure51",
  "textbook-response-q13-rise-numeric": "response-figure51",
  "textbook-response-q14-delay-numeric": "response-figure51",
  "textbook-response-q15-overshoot-numeric": "response-figure51",
  "textbook-response-q16-settling-scenario": "response-figure51",
  "textbook-response-q17-symbol-map": "response-figure51",
  "textbook-response-q18-figure52-rapidity": "response-figure52",
  "textbook-response-q19-figure52-settling": "response-figure52",
  "textbook-response-q20-figure53-comparison": "response-figure53",
  "textbook-response-q21-no-overshoot": "response-figure52",
  "textbook-response-q22-normalized-comparison": "response-figure53",
  "textbook-response-q23-steady-value-caution": "response-figure51",
  "textbook-response-q24-english-symbols": "response-figure51",
  "textbook-response-q25-figure51-values": "response-figure51",
  "textbook-response-q26-full-explanation": "response-figure51",
  "smart-exam-1-q1": "response-figure51",
  "smart-exam-1-q3": "pole-plane",
  "smart-exam-1-q4": "negative-feedback",
  "smart-exam-2-q1": "response-figure51",
  "smart-exam-2-q3": "pole-plane",
  "smart-exam-2-q4": "series-feedback",
  "smart-exam-3-q3": "pole-plane",
  "smart-exam-3-q4": "negative-feedback",
  "smart-exam-4-q3": "pole-plane",
  "smart-exam-4-q4": "block-shifts",
  "smart-exam-5-q1": "response-figure51",
  "smart-exam-5-q3": "pole-plane",
  "smart-exam-5-q4": "pole-plane",
  "smart-exam-6-q3": "pole-plane",
  "smart-exam-6-q4": "nested-feedback",
} as const satisfies Record<string, SmartControlDiagramId>;

export type SmartControlFigureItem = { id: string; diagramId?: SmartControlDiagramId };

export function smartControlDiagramIdFor(item: SmartControlFigureItem): SmartControlDiagramId | undefined {
  return item.diagramId ?? SMART_CONTROL_DIAGRAM_BY_ITEM_ID[item.id as keyof typeof SMART_CONTROL_DIAGRAM_BY_ITEM_ID];
}
