import type {
  StatisticsFormulaCard,
  StatisticsQuestion,
  StatisticsTopicId,
} from "./statistics-data";

export type StatisticsAdditionalSource = {
  page: number;
  filename: string;
  topics: StatisticsTopicId[];
  summary: string;
  usePolicy: string;
};

export const STATISTICS_ADDITIONAL_RANGE_LABEL = "確率統計追加範囲（2026-07-22・全5枚）";

/**
 * 追加ZIPをページ順に固定した出典台帳。ファイル名は提出物との照合に使うため変更しない。
 */
export const STATISTICS_ADDITIONAL_SOURCES: StatisticsAdditionalSource[] = [
  {
    page: 1,
    filename: "PXL_20260722_114642607.MP.jpg",
    topics: ["random-variable"],
    summary: "公平なサイコロの期待値・二乗の期待値と、E[aX+c] の線形性。",
    usePolicy: "数式・数値計算とも出題対象。",
  },
  {
    page: 2,
    filename: "PXL_20260722_114650437.MP.jpg",
    topics: ["continuous"],
    summary: "標準正規分布表による区間確率と、平均1・分散1/3のチェビシェフ評価。",
    usePolicy: "表の値 Φ(1.20)=0.8849、Φ(1.36)=0.9131 を含めて出題対象。",
  },
  {
    page: 3,
    filename: "PXL_20260722_114652791.MP.jpg",
    topics: ["continuous"],
    summary: "平均7000・標準偏差1000の量を、チェビシェフの不等式で評価する例。",
    usePolicy: "5000以上9000以下に入る確率の保証下限0.75を出題対象。",
  },
  {
    page: 4,
    filename: "PXL_20260722_114730085.MP.jpg",
    topics: ["random-variable", "continuous"],
    summary: "二次モーメント、分散の性質、2標本平均、指数分布・一様分布、一般の標準化。",
    usePolicy: "写真に式と導出が確認できる範囲を計算問題として出題。",
  },
  {
    page: 5,
    filename: "PXL_20260722_114734899.MP.jpg",
    topics: ["random-variable", "continuous"],
    summary: "標準化の意味と、モーメント・モーメント母関数・歪度・尖度という用語。",
    usePolicy: "定義式が写っていない4用語は名称・概念確認だけとし、計算問題は作らない。",
  },
];

export const STATISTICS_ADDITIONAL_FORMULAS: StatisticsFormulaCard[] = [
  {
    id: "stats-second-moment",
    topic: "random-variable",
    title: "二乗の期待値（2次モーメント）",
    prompt: "離散型確率変数の \\(E[X^2]\\) は？",
    formula: "E[X^2]=\\sum_i x_i^2p_i",
    expandedFormula: "E[X^2]=x_1^2p_1+x_2^2p_2+\\cdots+x_k^2p_k",
    explanation: "値を二乗してから、その値を取る確率で重み付けする。\\(E[X^2]\\) は \\(E[X]^2\\) とは別物で、分散の計算 \\(V(X)=E[X^2]-E[X]^2\\) に使う。",
    cue: "二乗してから確率を掛ける",
    example: "公平なサイコロでは \\(E[X^2]=\\frac{1^2+2^2+3^2+4^2+5^2+6^2}{6}=\\frac{91}{6}\\)。",
    sourcePages: [1, 4],
  },
  {
    id: "stats-variance-properties",
    topic: "random-variable",
    title: "分散の基本性質",
    prompt: "定数の加算・定数倍で分散はどう変わる？",
    formula: "V(c)=0,\\qquad V(X+c)=V(X),\\qquad V(cX)=c^2V(X)",
    explanation: "一定値にはばらつきがなく、平行移動しても散らばりは変わらない。倍率は偏差にも掛かるため、分散では二乗になる。",
    cue: "足す定数は消える・掛ける定数は二乗",
    sourcePages: [4],
  },
  {
    id: "stats-two-sample-average-variance",
    topic: "random-variable",
    title: "独立な2変量の平均の分散",
    prompt: "独立で同じ分散を持つ \\(X_1,X_2\\) の平均 \\(Y\\) の分散は？",
    formula: "Y=\\frac{X_1+X_2}{2},\\qquad V(Y)=\\frac{V(X)}{2}",
    explanation: "独立なら和の分散は分散の和。したがって \\(V(Y)=\\frac14\\{V(X_1)+V(X_2)\\}=\\frac12V(X)\\) となり、平均を取るとばらつきが小さくなる。",
    cue: "独立な2個の平均で分散は半分",
    example: "サイコロ2個の平均では \\(V(Y)=\\frac12\\cdot\\frac{35}{12}=\\frac{35}{24}\\)。",
    sourcePages: [4],
  },
  {
    id: "stats-exponential-variance",
    topic: "continuous",
    title: "指数分布の分散",
    prompt: "密度 \\(f(x)=\\lambda e^{-\\lambda x}\\;(x\\ge0)\\) の分散は？",
    formula: "E[X]=\\frac1\\lambda,\\qquad E[X^2]=\\frac{2}{\\lambda^2},\\qquad V(X)=\\frac1{\\lambda^2}",
    explanation: "二乗の期待値から期待値の二乗を引くと、\\(2/\\lambda^2-1/\\lambda^2=1/\\lambda^2\\) になる。",
    cue: "指数分布：平均1/λ・分散1/λ²",
    sourcePages: [4],
  },
  {
    id: "stats-unit-uniform-variance",
    topic: "continuous",
    title: "区間[0,1]の一様分布",
    prompt: "\\([0,1]\\) 上の一様分布の期待値・分散は？",
    formula: "E[X]=\\frac12,\\qquad E[X^2]=\\frac13,\\qquad V(X)=\\frac1{12}",
    explanation: "密度が1なので積分で \\(E[X]=1/2\\)、\\(E[X^2]=1/3\\)。差 \\(1/3-(1/2)^2\\) が \\(1/12\\) になる。",
    cue: "0〜1一様：平均1/2・分散1/12",
    sourcePages: [4],
  },
  {
    id: "stats-general-standardization",
    topic: "continuous",
    title: "一般の確率変数の標準化",
    prompt: "平均と分散だけを使って標準化する式は？",
    formula: "Z=\\frac{X-E[X]}{\\sqrt{V(X)}},\\qquad E[Z]=0,\\qquad V(Z)=1",
    explanation: "平均を引いて中心を0へ移し、標準偏差で割って分散を1にする。標準化した量は無次元なので、単位の異なる分布も比較できる。正規分布でなくてもこの平均・分散の性質は成り立つ。",
    cue: "平均との差÷標準偏差 → 平均0・分散1",
    sourcePages: [4, 5],
  },
  {
    id: "stats-normal-interval-cdf",
    topic: "continuous",
    title: "標準正規分布の区間確率",
    prompt: "下側累積表 \\(\\Phi\\) から \\(P(a<Z<b)\\) を求める式は？",
    formula: "P(a<Z<b)=\\Phi(b)-\\Phi(a)",
    explanation: "右端までの累積確率から左端までの累積確率を引く。負の値は \\(\\Phi(-z)=1-\\Phi(z)\\) で正側の表へ直せる。",
    cue: "右の累積−左の累積",
    example: "\\(P(1.20<Z<1.36)=0.9131-0.8849=0.0282\\)。",
    sourcePages: [2],
  },
  {
    id: "stats-moment-vocabulary",
    topic: "random-variable",
    title: "分布の形を表す用語",
    prompt: "p.99で導入された4つの用語は？",
    formula: "\\text{モーメント・モーメント母関数・歪度・尖度}",
    explanation: "モーメントは分布の特徴を数量化する考え方、モーメント母関数はモーメントをまとめて扱う道具、歪度は左右の非対称性、尖度は山の鋭さや裾の重さを見る指標。写真には定義式が写っていないため、このカードでは名称と役割だけを確認する。",
    cue: "p.99は名称と概念だけ",
    sourcePages: [5],
  },
];

export const STATISTICS_ADDITIONAL_QUESTIONS: StatisticsQuestion[] = [
  {
    id: "stats-additional-die-expectation",
    topic: "random-variable",
    genre: "サイコロ・期待値",
    difficulty: 2,
    format: "number",
    prompt: "公平な6面サイコロの出目を \\(X\\) とする。\\(E[X]\\) を求めよ。",
    answer: "\\(\\frac72=3.5\\)",
    numericAnswer: 3.5,
    formula: "E[X]=\\sum_{x=1}^{6}xP(X=x)",
    expandedFormula: "E[X]=1\\cdot\\frac16+2\\cdot\\frac16+3\\cdot\\frac16+4\\cdot\\frac16+5\\cdot\\frac16+6\\cdot\\frac16",
    steps: ["各出目の確率はすべて \\(1/6\\)。", "\\(E[X]=\\frac{1+2+3+4+5+6}{6}=\\frac72\\)。"],
    explanation: "期待値は値を確率で重み付けした平均である。単純な和21ではなく、確率1/6を掛ける。",
    source: "course-range",
    sourcePages: [1],
  },
  {
    id: "stats-additional-die-second-moment",
    topic: "random-variable",
    genre: "サイコロ・二次モーメント",
    difficulty: 2,
    format: "number",
    prompt: "公平な6面サイコロの出目を \\(X\\) とする。\\(E[X^2]\\) を求めよ。",
    answer: "\\(\\frac{91}{6}\\approx15.167\\)",
    numericAnswer: 91 / 6,
    tolerance: 0.001,
    formula: "E[X^2]=\\sum_{x=1}^{6}x^2P(X=x)",
    expandedFormula: "E[X^2]=1^2\\cdot\\frac16+2^2\\cdot\\frac16+3^2\\cdot\\frac16+4^2\\cdot\\frac16+5^2\\cdot\\frac16+6^2\\cdot\\frac16",
    steps: ["二乗和は \\(1+4+9+16+25+36=91\\)。", "\\(E[X^2]=91/6\\)。"],
    explanation: "先に出目を二乗し、その後で確率を掛ける。期待値を先に求めて二乗する問題ではない。",
    source: "course-range",
    sourcePages: [1, 4],
  },
  {
    id: "stats-additional-die-variance",
    topic: "random-variable",
    genre: "サイコロ・分散",
    difficulty: 3,
    format: "number",
    prompt: "公平な6面サイコロの出目を \\(X\\) とする。\\(E[X]=7/2\\)、\\(E[X^2]=91/6\\) を用いて \\(V(X)\\) を求めよ。",
    answer: "\\(\\frac{35}{12}\\approx2.917\\)",
    numericAnswer: 35 / 12,
    tolerance: 0.001,
    formula: "V(X)=E[X^2]-\\{E[X]\\}^2",
    steps: ["\\(V(X)=\\frac{91}{6}-\\left(\\frac72\\right)^2\\)。", "通分して \\(V(X)=\\frac{182-147}{12}=\\frac{35}{12}\\)。"],
    explanation: "二次モーメントと期待値の二乗を区別する。分散は必ず0以上になるので符号も検算できる。",
    source: "course-range",
    sourcePages: [4],
  },
  {
    id: "stats-additional-two-dice-average-variance",
    topic: "random-variable",
    genre: "独立変数の平均",
    difficulty: 3,
    format: "number",
    prompt: "独立な公平サイコロ2個の出目を \\(X_1,X_2\\)、その平均を \\(Y=(X_1+X_2)/2\\) とする。\\(V(X_i)=35/12\\) のとき \\(V(Y)\\) を求めよ。",
    answer: "\\(\\frac{35}{24}\\approx1.458\\)",
    numericAnswer: 35 / 24,
    tolerance: 0.001,
    formula: "V\\!\\left(\\frac{X_1+X_2}{2}\\right)=\\frac14\\{V(X_1)+V(X_2)\\}",
    steps: ["独立なので \\(V(X_1+X_2)=V(X_1)+V(X_2)\\)。", "\\(V(Y)=\\frac14\\left(\\frac{35}{12}+\\frac{35}{12}\\right)=\\frac{35}{24}\\)。"],
    explanation: "平均を取ると分散は元の半分になる。標準偏差が半分になるのではない点に注意する。",
    source: "course-range",
    sourcePages: [4],
  },
  {
    id: "stats-additional-affine-expectation",
    topic: "random-variable",
    genre: "期待値の線形性",
    difficulty: 2,
    format: "number",
    prompt: "公平なサイコロの出目 \\(X\\) について \\(E[X]=7/2\\) である。\\(E[2X+1]\\) を求めよ。",
    answer: "\\(8\\)",
    numericAnswer: 8,
    formula: "E[aX+c]=aE[X]+c",
    steps: ["\\(E[2X+1]=2E[X]+1\\)。", "\\(2\\cdot\\frac72+1=8\\)。"],
    explanation: "期待値では倍率も加算定数もそのまま作用する。分散の変換則と混同しない。",
    source: "course-range",
    sourcePages: [1],
  },
  {
    id: "stats-additional-exponential-variance",
    topic: "continuous",
    genre: "指数分布",
    difficulty: 2,
    format: "number",
    prompt: "密度 \\(f(x)=2e^{-2x}\\;(x\\ge0)\\) に従う指数分布の分散を求めよ。",
    answer: "\\(\\frac14=0.25\\)",
    numericAnswer: 0.25,
    formula: "V(X)=\\frac1{\\lambda^2}",
    steps: ["この分布では \\(\\lambda=2\\)。", "\\(V(X)=1/2^2=1/4\\)。"],
    explanation: "指数分布の平均は1/λ、分散は1/λ²である。平均と分散を同じ1/λにしない。",
    source: "course-range",
    sourcePages: [4],
  },
  {
    id: "stats-additional-unit-uniform-variance",
    topic: "continuous",
    genre: "一様分布",
    difficulty: 2,
    format: "number",
    prompt: "\\([0,1]\\) 上の一様分布に従う \\(X\\) の分散を求めよ。",
    answer: "\\(\\frac1{12}\\approx0.0833\\)",
    numericAnswer: 1 / 12,
    tolerance: 0.0001,
    formula: "V(X)=E[X^2]-\\{E[X]\\}^2=\\frac13-\\left(\\frac12\\right)^2",
    steps: ["\\(E[X]=1/2\\)、\\(E[X^2]=1/3\\)。", "\\(V(X)=1/3-1/4=1/12\\)。"],
    explanation: "一様分布の密度が1であることから、期待値と二次モーメントは積分で得られる。",
    source: "course-range",
    sourcePages: [4],
  },
  {
    id: "stats-additional-variance-properties",
    topic: "random-variable",
    genre: "分散の性質",
    difficulty: 2,
    format: "choice",
    prompt: "\\(V(X)=3\\) のとき、正しい組を選べ。",
    answer: "V(X+5)=3、V(2X)=12、V(5)=0",
    options: [
      "V(X+5)=3、V(2X)=12、V(5)=0",
      "V(X+5)=8、V(2X)=6、V(5)=5",
      "V(X+5)=3、V(2X)=6、V(5)=25",
      "V(X+5)=8、V(2X)=12、V(5)=0",
    ],
    formula: "V(c)=0,\\quad V(X+c)=V(X),\\quad V(cX)=c^2V(X)",
    steps: ["定数加算は分散を変えない。", "定数倍2は二乗して4倍、定数だけの分散は0。"],
    explanation: "平行移動はばらつきを変えず、倍率は偏差の倍率として二乗で効く。",
    source: "course-range",
    sourcePages: [4],
  },
  {
    id: "stats-additional-general-standardization",
    topic: "continuous",
    genre: "一般の標準化",
    difficulty: 2,
    format: "choice",
    prompt: "\\(Z=(X-E[X])/\\sqrt{V(X)}\\) と標準化したとき、正しい性質を選べ。",
    answer: "E[Z]=0、V(Z)=1で、Zは無次元である",
    options: [
      "E[Z]=0、V(Z)=1で、Zは無次元である",
      "E[Z]=1、V(Z)=0で、ZはXと同じ単位を持つ",
      "E[Z]=0、V(Z)=V(X)で、正規分布にしか使えない",
      "E[Z]=E[X]、V(Z)=1で、平均を引く必要はない",
    ],
    formula: "Z=\\frac{X-E[X]}{\\sqrt{V(X)}},\\quad E[Z]=0,\\quad V(Z)=1",
    steps: ["平均を引くため中心は0になる。", "標準偏差で割るため分散は1になり、単位も消える。"],
    explanation: "この平均0・分散1という性質は一般の確率変数の標準化で成り立つ。正規分布表を使うかどうかは別の話である。",
    source: "course-range",
    sourcePages: [4, 5],
  },
  {
    id: "stats-additional-normal-narrow-interval",
    topic: "continuous",
    genre: "正規分布表",
    difficulty: 2,
    format: "number",
    prompt: "標準正規分布表で \\(\\Phi(1.20)=0.8849\\)、\\(\\Phi(1.36)=0.9131\\) とする。\\(P(1.20<Z<1.36)\\) を求めよ。",
    answer: "\\(0.0282\\)",
    numericAnswer: 0.0282,
    tolerance: 0.00005,
    formula: "P(a<Z<b)=\\Phi(b)-\\Phi(a)",
    steps: ["右端までの累積確率から左端までを引く。", "\\(0.9131-0.8849=0.0282\\)。"],
    explanation: "どちらも正側なので、累積表の2値をそのまま引けばよい。",
    source: "course-range",
    sourcePages: [2],
  },
  {
    id: "stats-additional-normal-x-interval",
    topic: "continuous",
    genre: "標準化・区間確率",
    difficulty: 3,
    format: "number",
    prompt: "\\(X\\sim N(2,5^2)\\) とする。\\(\\Phi(1.20)=0.8849\\)、\\(\\Phi(1.36)=0.9131\\) を用いて \\(P(-4<X<8.8)\\) を求めよ。",
    answer: "\\(0.7980\\)",
    numericAnswer: 0.798,
    tolerance: 0.00005,
    formula: "Z=\\frac{X-2}{5},\\qquad P(-1.20<Z<1.36)=\\Phi(1.36)-\\Phi(-1.20)",
    steps: ["下端は \\((-4-2)/5=-1.20\\)、上端は \\((8.8-2)/5=1.36\\)。", "\\(\\Phi(-1.20)=1-0.8849=0.1151\\)。", "\\(0.9131-0.1151=0.7980\\)。"],
    explanation: "負側累積確率を対称性で直す。0.9131−0.1151であり、0.7998ではない。",
    source: "course-range",
    sourcePages: [2],
  },
];
