import type {
  StatisticsFormulaCard,
  StatisticsQuestion,
} from "./statistics-data";

export const STATISTICS_PDF34_QUESTIONS: StatisticsQuestion[] = [
  {
    id: "stats-ex3-dog-given-white",
    topic: "conditional",
    genre: "条件付き確率",
    difficulty: 1,
    format: "number",
    prompt: "白玉3個・赤玉3個がある。白玉には犬1個・猫2個、赤玉には犬2個・猫1個が描かれている。引いた玉が白だと分かったとき、犬が描かれている確率を求めよ。",
    answer: "\\(\\frac{1}{3}\\approx 0.333\\)",
    numericAnswer: 1 / 3,
    tolerance: 0.001,
    formula: "P(A\\mid B)=\\frac{P(A\\cap B)}{P(B)}",
    steps: [
      "白玉は \\(3\\) 個あり、そのうち犬が描かれた白玉は \\(1\\) 個。",
      "したがって \\(P(\\text{犬}\\mid\\text{白})=\\frac{1}{3}\\)。",
    ],
    explanation: "白だと分かった時点で、標本空間を白玉だけに絞る。全体の犬の割合ではなく、白玉の中での犬の割合を求める。",
    source: "course-range",
  },
  {
    id: "stats-ex3-specific-coin",
    topic: "conditional",
    genre: "独立",
    difficulty: 1,
    format: "number",
    prompt: "公平なコインを左右1枚ずつ同時に投げた。左のコインが表であることを確認したとき、右のコインが裏である確率を求めよ。",
    answer: "\\(\\frac{1}{2}=0.5\\)",
    numericAnswer: 0.5,
    formula: "P(R_{\\mathrm{T}}\\mid L_{\\mathrm{H}})=P(R_{\\mathrm{T}})",
    steps: [
      "左右のコインの結果は独立である。",
      "左が表という情報を得ても、右が裏である確率は \\(\\frac{1}{2}\\) のまま。",
    ],
    explanation: "『少なくとも一方が表』ではなく、左のコインが表だと特定している。独立な試行では、一方の結果は他方の確率を変えない。",
    source: "course-range",
  },
  {
    id: "stats-ex3-first-white-second-red",
    topic: "conditional",
    genre: "非復元抽出",
    difficulty: 2,
    format: "number",
    prompt: "白玉3個・赤玉3個の袋から、戻さずに2個を順に引く。1個目が白玉だったとき、2個目が赤玉である確率を求めよ。",
    answer: "\\(\\frac{3}{5}=0.6\\)",
    numericAnswer: 0.6,
    formula: "P(R_2\\mid W_1)=\\frac{3}{5}",
    steps: [
      "1個目の白玉を取り除くと、袋には白 \\(2\\) 個・赤 \\(3\\) 個が残る。",
      "残り \\(5\\) 個のうち赤は \\(3\\) 個なので、確率は \\(\\frac{3}{5}\\)。",
    ],
    explanation: "玉を戻さないため、1個目の結果によって2個目の標本空間が変わる。",
    source: "course-range",
  },
  {
    id: "stats-ex3-bayes-white-total",
    topic: "conditional",
    genre: "全確率",
    difficulty: 2,
    format: "number",
    prompt: "袋Xには白3個・赤1個、袋Yには白1個・赤2個が入っている。各袋を \\(\\frac{1}{2}\\) の確率で選び、玉を1個引くとき、白玉を引く確率を求めよ。",
    answer: "\\(\\frac{13}{24}\\approx 0.542\\)",
    numericAnswer: 13 / 24,
    tolerance: 0.001,
    formula: "P(W)=P(W\\mid X)P(X)+P(W\\mid Y)P(Y)",
    steps: [
      "Xを選んで白を引く確率は \\(\\frac{1}{2}\\cdot\\frac{3}{4}=\\frac{3}{8}\\)。",
      "Yを選んで白を引く確率は \\(\\frac{1}{2}\\cdot\\frac{1}{3}=\\frac{1}{6}\\)。",
      "両経路を足して \\(P(W)=\\frac{3}{8}+\\frac{1}{6}=\\frac{13}{24}\\)。",
    ],
    explanation: "白玉に到達する経路を袋ごとに計算し、互いに排反な経路として足し合わせる。",
    source: "course-range",
  },
  {
    id: "stats-ex3-bayes-posterior-x",
    topic: "conditional",
    genre: "ベイズの定理",
    difficulty: 3,
    format: "number",
    prompt: "袋Xには白3個・赤1個、袋Yには白1個・赤2個が入っている。各袋を \\(\\frac{1}{2}\\) の確率で選び、引いた玉が白だった。選んだ袋がXである事後確率を求めよ。",
    answer: "\\(\\frac{9}{13}\\approx 0.692\\)",
    numericAnswer: 9 / 13,
    tolerance: 0.001,
    formula: "P(X\\mid W)=\\frac{P(W\\mid X)P(X)}{P(W)}",
    steps: [
      "Xを選んで白を引く同時確率は \\(\\frac{1}{2}\\cdot\\frac{3}{4}=\\frac{3}{8}\\)。",
      "白を引く全確率は \\(\\frac{13}{24}\\)。",
      "よって \\(P(X\\mid W)=\\frac{\\frac{3}{8}}{\\frac{13}{24}}=\\frac{9}{13}\\)。",
    ],
    explanation: "分子は目的とするX経路、分母は白玉が出る全経路の確率である。",
    source: "course-range",
  },
  {
    id: "stats-ex3-bayes-posterior-y",
    topic: "conditional",
    genre: "ベイズの定理",
    difficulty: 3,
    format: "number",
    prompt: "袋Xには白3個・赤1個、袋Yには白1個・赤2個が入っている。各袋を \\(\\frac{1}{2}\\) の確率で選び、引いた玉が白だった。選んだ袋がYである事後確率を求めよ。",
    answer: "\\(\\frac{4}{13}\\approx 0.308\\)",
    numericAnswer: 4 / 13,
    tolerance: 0.001,
    formula: "P(Y\\mid W)=\\frac{P(W\\mid Y)P(Y)}{P(W)}",
    steps: [
      "Yを選んで白を引く同時確率は \\(\\frac{1}{2}\\cdot\\frac{1}{3}=\\frac{1}{6}\\)。",
      "白を引く全確率は \\(\\frac{13}{24}\\)。",
      "よって \\(P(Y\\mid W)=\\frac{\\frac{1}{6}}{\\frac{13}{24}}=\\frac{4}{13}\\)。",
    ],
    explanation: "XとYの事後確率は合わせて \\(1\\) になり、\\(\\frac{9}{13}+\\frac{4}{13}=1\\) と検算できる。",
    source: "course-range",
  },
  {
    id: "stats-ex4-density-clipped-interval",
    topic: "continuous",
    genre: "区間確率",
    difficulty: 2,
    format: "number",
    prompt: "確率密度関数が f(x)=0.5（0≤x≤2）、それ以外では0である。P(1.5≤X≤2.5)を求めよ。",
    answer: "\\(\\frac{1}{4}=0.25\\)",
    numericAnswer: 0.25,
    formula: "P(a\\le X\\le b)=\\int_a^b f(x)\\,dx",
    steps: [
      "密度が正なのは \\(0\\le x\\le 2\\) だけなので、積分区間は \\(1.5\\le x\\le 2\\)。",
      "\\(\\int_{1.5}^{2}0.5\\,dx=0.5(2-1.5)=0.25\\)。",
    ],
    explanation: "指定区間が密度の定義域をはみ出すときは、密度が正である部分だけを積分する。",
    source: "course-range",
  },
  {
    id: "stats-ex4-continuous-point-probability",
    topic: "continuous",
    genre: "連続型の性質",
    difficulty: 1,
    format: "number",
    prompt: "連続型確率変数Xの確率密度関数が f(x)=0.5（0≤x≤2）、それ以外では0である。P(X=1.5)を求めよ。",
    answer: "\\(0\\)",
    numericAnswer: 0,
    formula: "P(X=c)=\\int_c^c f(x)\\,dx=0",
    steps: [
      "一点だけの区間の幅は \\(0\\)。",
      "したがって面積も \\(0\\) で、\\(P(X=1.5)=0\\)。",
    ],
    explanation: "連続型では確率を面積で考えるため、特定の一点を取る確率は常に \\(0\\) になる。",
    source: "course-range",
  },
  {
    id: "stats-ex4-density-normalization",
    topic: "continuous",
    genre: "確率密度",
    difficulty: 1,
    format: "number",
    prompt: "f(x)=c（0≤x≤2）、それ以外では0が確率密度関数になるように、定数cを求めよ。",
    answer: "\\(\\frac{1}{2}=0.5\\)",
    numericAnswer: 0.5,
    formula: "\\int_{-\\infty}^{\\infty}f(x)\\,dx=1",
    steps: [
      "全区間の面積が \\(1\\) なので、\\(\\int_0^2 c\\,dx=1\\)。",
      "\\(2c=1\\) より、\\(c=\\frac{1}{2}\\)。",
    ],
    explanation: "確率密度関数は負にならず、グラフ全体の面積が \\(1\\) になる。",
    source: "course-range",
  },
  {
    id: "stats-ex4-normal-lower-123",
    topic: "continuous",
    genre: "標準正規分布表",
    difficulty: 1,
    format: "number",
    prompt: "標準正規分布表（下側確率）を使い、P(Z≤1.23)を求めよ。小数第4位まで答えよ。",
    answer: "\\(0.8907\\)",
    numericAnswer: 0.8907,
    tolerance: 0.00005,
    formula: "\\Phi(z)=P(Z\\le z)",
    steps: [
      "標準正規分布表の行 \\(1.2\\)、列 \\(0.03\\) を見る。",
      "交点の値は \\(\\Phi(1.23)=0.8907\\)。",
    ],
    explanation: "下側確率表なので、表の値をそのまま \\(P(Z\\le1.23)\\) として使う。",
    source: "course-range",
  },
  {
    id: "stats-ex4-normal-positive-interval",
    topic: "continuous",
    genre: "標準正規分布表",
    difficulty: 2,
    format: "number",
    prompt: "標準正規分布表（下側確率）を使い、P(0.15<Z<1.90)を求めよ。小数第4位まで答えよ。",
    answer: "\\(0.4117\\)",
    numericAnswer: 0.4117,
    tolerance: 0.00005,
    formula: "P(a<Z<b)=\\Phi(b)-\\Phi(a)",
    steps: [
      "表から \\(\\Phi(1.90)=0.9713\\)、\\(\\Phi(0.15)=0.5596\\) を読む。",
      "\\(0.9713-0.5596=0.4117\\)。",
    ],
    explanation: "区間確率は、右端までの累積確率から左端までの累積確率を引く。",
    source: "course-range",
  },
  {
    id: "stats-ex4-normal-negative-interval",
    topic: "continuous",
    genre: "標準正規分布の対称性",
    difficulty: 3,
    format: "number",
    prompt: "標準正規分布表（下側確率）を使い、P(−1.33<Z<−0.67)を求めよ。小数第4位まで答えよ。",
    answer: "\\(0.1596\\)",
    numericAnswer: 0.1596,
    tolerance: 0.00005,
    formula: "\\Phi(-z)=1-\\Phi(z)",
    steps: [
      "対称性から \\(P(-1.33<Z<-0.67)=\\Phi(1.33)-\\Phi(0.67)\\)。",
      "表から \\(\\Phi(1.33)=0.9082\\)、\\(\\Phi(0.67)=0.7486\\) を読む。",
      "\\(0.9082-0.7486=0.1596\\)。",
    ],
    explanation: "負の範囲は標準正規分布の左右対称性を使って正の値へ移すと、表を読みやすい。",
    source: "course-range",
  },
  {
    id: "stats-ex4-chebyshev-mean-one",
    topic: "continuous",
    genre: "チェビシェフの不等式",
    difficulty: 2,
    format: "number",
    prompt: "分布の形は不明だが、平均が \\(1\\)、分散が \\(\\frac{1}{3}\\) である。\\(P(0\\le X\\le2)\\) について、チェビシェフの不等式で保証できる下限を求めよ。",
    answer: "\\(\\frac{2}{3}\\approx 0.667\\)",
    numericAnswer: 2 / 3,
    tolerance: 0.001,
    formula: "P(|X-\\mu|\\le k\\sigma)\\ge 1-\\frac{1}{k^2}",
    steps: [
      "標準偏差は \\(\\sigma=\\sqrt{\\frac{1}{3}}=\\frac{1}{\\sqrt{3}}\\)。",
      "区間は平均から \\(1\\) 以内なので、\\(k=\\frac{1}{\\sigma}=\\sqrt{3}\\)。",
      "よって \\(P(|X-1|\\le1)\\ge1-\\frac{1}{(\\sqrt{3})^2}=\\frac{2}{3}\\)。",
    ],
    explanation: "分布形が分からなくても、平均と分散だけから区間内確率の最低保証を得られる。",
    source: "course-range",
    sourcePages: [2],
  },
  {
    id: "stats-ex4-chebyshev-demand",
    topic: "continuous",
    genre: "チェビシェフの不等式",
    difficulty: 2,
    format: "number",
    prompt: "ある商品の月間需要は平均7000個、標準偏差1000個である。需要が5000個以上9000個以下となる確率について、チェビシェフの不等式で保証できる下限を求めよ。",
    answer: "\\(\\frac{3}{4}=0.75\\)",
    numericAnswer: 0.75,
    formula: "P(|X-\\mu|\\le k\\sigma)\\ge 1-\\frac{1}{k^2}",
    steps: [
      "区間は平均 \\(7000\\) から左右 \\(2000\\) 個以内。",
      "\\(2000=2\\times1000\\) なので、\\(k=2\\)。",
      "したがって \\(P(|X-7000|\\le2000)\\ge1-\\frac{1}{2^2}=\\frac{3}{4}=0.75\\)。",
    ],
    explanation: "保証される下限が \\(0.75\\) なので、この確率は少なくとも \\(0.7\\) 以上であると判定できる。\\(0.75\\) は正確な確率ではなく下限である。",
    source: "course-range",
    sourcePages: [3],
  },
];

export const STATISTICS_PDF34_FORMULAS: StatisticsFormulaCard[] = [
  {
    id: "stats-chebyshev",
    topic: "continuous",
    title: "チェビシェフの不等式",
    prompt: "平均から kσ 以上離れる確率の上限は？",
    formula: "P\\!\\left(\\lvert X-\\mu\\rvert\\ge k\\sigma\\right)\\le\\frac{1}{k^2}\\quad(k>1)",
    explanation: "分布の形を仮定せず、平均と分散だけから平均より遠い値が出る確率を上から抑える。",
    cue: "外側は k の二乗分の1以下",
    example: "\\(k=2\\) なら、平均から \\(2\\sigma\\) 以上離れる確率は \\(\\frac{1}{4}\\) 以下。",
    sourcePages: [2, 3],
  },
  {
    id: "stats-ex4-chebyshev-symmetric-interval",
    topic: "continuous",
    title: "対称区間内の確率下限",
    prompt: "平均から幅 a 以内に入る確率の下限は？",
    formula: "P\\!\\left(\\lvert X-\\mu\\rvert\\le a\\right)\\ge1-\\frac{\\sigma^2}{a^2}\\quad(a>\\sigma)",
    explanation: "対称区間の半幅を標準偏差で割って k を作れば、区間内に入る確率の最低保証を計算できる。",
    cue: "内側は 1 − 分散÷幅の二乗",
    example: "\\(a=2\\sigma\\) なら、区間内確率は少なくとも \\(1-\\frac{1}{4}=\\frac{3}{4}\\)。",
    sourcePages: [2, 3],
  },
];
