import type { StatisticsQuestion } from "./statistics-data";

function courseQuestion(question: Omit<StatisticsQuestion, "source">): StatisticsQuestion {
  return { ...question, source: "course-range" };
}

export const STATISTICS_PDF12_QUESTIONS: StatisticsQuestion[] = [
  courseQuestion({
    id: "stats-ex1-traffic-slope",
    topic: "relation",
    genre: "回帰直線",
    difficulty: 2,
    format: "number",
    prompt: "交通量を \\(x\\)、売上高を \\(y\\) とする。母共分散が \\(1243.6\\)、交通量の母分散が \\(2967\\) のとき、回帰直線の傾き \\(b\\) を小数第3位まで求めよ。",
    answer: "\\(b\\approx0.419\\)",
    numericAnswer: 1243.6 / 2967,
    tolerance: 0.0005,
    formula: "b=\\frac{\\operatorname{Cov}(X,Y)}{V(X)}",
    steps: [
      "傾きは説明変数の分散で共分散を割る。",
      "\\(b=\\frac{1243.6}{2967}\\approx0.419144\\)",
      "小数第3位までで \\(b\\approx0.419\\) とする。",
    ],
    explanation: "回帰の傾きは、交通量が \\(1\\) 増えたときに売上高が平均してどれだけ変化するかを表す。",
  }),
  courseQuestion({
    id: "stats-ex1-traffic-intercept",
    topic: "relation",
    genre: "回帰直線",
    difficulty: 2,
    format: "number",
    prompt: "交通量の平均が \\(170\\)、売上高の平均が \\(185\\)、資料で丸めた傾きが \\(b=0.42\\) である。切片 \\(a\\) を整数に丸めて求めよ。",
    answer: "\\(a\\approx114\\)",
    numericAnswer: 114,
    formula: "a=\\bar{y}-b\\bar{x}",
    steps: [
      "回帰直線は平均の点 \\((\\bar{x},\\bar{y})\\) を通る。",
      "\\(a=185-0.42\\times170=113.6\\)",
      "整数に丸めると \\(a=114\\) となる。",
    ],
    explanation: "資料と同じ丸め方を使うと、回帰直線は \\(\\hat{y}=0.42x+114\\) になる。",
  }),
  courseQuestion({
    id: "stats-ex1-traffic-prediction",
    topic: "relation",
    genre: "回帰による予測",
    difficulty: 1,
    format: "number",
    prompt: "回帰直線が \\(\\hat{y}=0.42x+114\\) のとき、交通量が \\(300\\) 台／日の店舗の予測売上高を求めよ。",
    answer: "\\(240\\)",
    numericAnswer: 240,
    formula: "\\hat{y}=a+bx",
    steps: [
      "回帰式の \\(x\\) に \\(300\\) を代入する。",
      "\\(\\hat{y}=0.42\\times300+114\\)",
      "\\(\\hat{y}=126+114=240\\)",
    ],
    explanation: "回帰直線に説明変数の値を代入すると、従属変数の予測値が得られる。",
  }),
  courseQuestion({
    id: "stats-ex1-traffic-correlation",
    topic: "relation",
    genre: "相関係数",
    difficulty: 2,
    format: "number",
    prompt: "交通量と売上高の母共分散が \\(1243.6\\)、標準偏差がそれぞれ \\(54.5\\)、\\(41.6\\) のとき、相関係数 \\(r\\) を小数第2位まで求めよ。",
    answer: "\\(r\\approx0.55\\)",
    numericAnswer: 1243.6 / (54.5 * 41.6),
    tolerance: 0.005,
    formula: "r=\\frac{\\operatorname{Cov}(X,Y)}{\\sigma_X\\sigma_Y}",
    steps: [
      "共分散を二つの標準偏差の積で割る。",
      "\\(r=\\frac{1243.6}{54.5\\times41.6}\\approx0.5485\\)",
      "小数第2位までで \\(r\\approx0.55\\) となる。",
    ],
    explanation: "\\(r\\) が正なので正の相関があり、資料では中程度の相関と判断している。",
  }),
  courseQuestion({
    id: "stats-ex1-traffic-determination",
    topic: "relation",
    genre: "決定係数",
    difficulty: 1,
    format: "number",
    prompt: "交通量と売上高の相関係数が \\(r=0.55\\) のとき、決定係数 \\(R^2\\) を小数第2位まで求めよ。",
    answer: "\\(R^2\\approx0.30\\)",
    numericAnswer: 0.3,
    tolerance: 0.005,
    formula: "R^2=r^2",
    steps: [
      "相関係数を二乗する。",
      "\\(R^2=0.55^2=0.3025\\)",
      "小数第2位までで \\(R^2\\approx0.30\\) となる。",
    ],
    explanation: "単回帰では決定係数は相関係数の二乗であり、この例では変動のおよそ \\(30\\%\\) を回帰直線で説明できる。",
  }),
  courseQuestion({
    id: "stats-ex1-blood-slope",
    topic: "relation",
    genre: "回帰直線",
    difficulty: 3,
    format: "number",
    prompt: "年齢 \\(x\\) と血圧 \\(y\\) の偏差積和が \\(4523\\)、年齢の偏差平方和が \\(4690.8\\) である。回帰直線の傾き \\(b\\) を小数第3位まで求めよ。",
    answer: "\\(b\\approx0.964\\)",
    numericAnswer: 4523 / 4690.8,
    tolerance: 0.0005,
    formula: "b=\\frac{\\sum_{i=1}^{n}(x_i-\\bar{x})(y_i-\\bar{y})}{\\sum_{i=1}^{n}(x_i-\\bar{x})^2}",
    expandedFormula: "b=\\frac{4523}{4690.8}",
    steps: [
      "偏差積和を説明変数の偏差平方和で割る。",
      "\\(b=\\frac{4523}{4690.8}\\approx0.964228\\)",
      "小数第3位までで \\(b\\approx0.964\\) とする。",
    ],
    explanation: "年齢が \\(1\\) 歳高くなると、回帰式上の血圧は平均して約 \\(0.964\\) 上昇する。",
  }),
  courseQuestion({
    id: "stats-ex1-blood-intercept",
    topic: "relation",
    genre: "回帰直線",
    difficulty: 2,
    format: "number",
    prompt: "年齢の平均が \\(42.6\\)、血圧の平均が \\(133.5\\)、回帰の傾きが \\(b=0.96422785\\) のとき、切片 \\(a\\) を小数第2位まで求めよ。",
    answer: "\\(a\\approx92.42\\)",
    numericAnswer: 133.5 - (4523 / 4690.8) * 42.6,
    tolerance: 0.005,
    formula: "a=\\bar{y}-b\\bar{x}",
    steps: [
      "平均の点を通る条件から切片を求める。",
      "\\(a=133.5-0.96422785\\times42.6\\)",
      "\\(a\\approx92.4239\\) より、小数第2位までで \\(92.42\\) となる。",
    ],
    explanation: "傾きだけでは直線の位置は決まらないため、二つの平均を使って切片を決める。",
  }),
  courseQuestion({
    id: "stats-ex1-blood-prediction",
    topic: "relation",
    genre: "回帰による予測",
    difficulty: 2,
    format: "number",
    prompt: "年齢から血圧を予測する回帰直線が \\(\\hat{y}=0.96422785x+92.42389\\) である。\\(40\\) 歳の予測血圧を小数第1位まで求めよ。",
    answer: "\\(\\hat{y}\\approx131.0\\)",
    numericAnswer: (4523 / 4690.8) * 40 + (133.5 - (4523 / 4690.8) * 42.6),
    tolerance: 0.05,
    formula: "\\hat{y}=a+bx",
    steps: [
      "回帰式に \\(x=40\\) を代入する。",
      "\\(\\hat{y}=0.96422785\\times40+92.42389\\)",
      "\\(\\hat{y}\\approx130.993\\) より、小数第1位までで \\(131.0\\) となる。",
    ],
    explanation: "回帰による値は観測値そのものではなく、直線から得られる予測値である。",
  }),
  courseQuestion({
    id: "stats-ex1-blood-correlation",
    topic: "relation",
    genre: "相関係数",
    difficulty: 3,
    format: "number",
    prompt: "年齢と血圧について、偏差積和が \\(4523\\)、年齢の偏差平方和が \\(4690.8\\)、血圧の偏差平方和が \\(7925\\) である。相関係数を小数第3位まで求めよ。",
    answer: "\\(r\\approx0.742\\)",
    numericAnswer: 4523 / Math.sqrt(4690.8 * 7925),
    tolerance: 0.0005,
    formula: "r=\\frac{\\sum_{i=1}^{n}(x_i-\\bar{x})(y_i-\\bar{y})}{\\sqrt{\\sum_{i=1}^{n}(x_i-\\bar{x})^2\\sum_{i=1}^{n}(y_i-\\bar{y})^2}}",
    expandedFormula: "r=\\frac{4523}{\\sqrt{4690.8\\times7925}}",
    steps: [
      "偏差積和を二つの偏差平方和の積の平方根で割る。",
      "\\(r=\\frac{4523}{\\sqrt{4690.8\\times7925}}\\)",
      "\\(r\\approx0.741828\\) より、小数第3位までで \\(0.742\\) となる。",
    ],
    explanation: "正で \\(1\\) に比較的近いため、年齢と血圧にはやや強い正の直線関係が見られる。",
  }),
  courseQuestion({
    id: "stats-ex1-blood-determination",
    topic: "relation",
    genre: "決定係数",
    difficulty: 2,
    format: "number",
    prompt: "年齢と血圧の相関係数が \\(r=0.741828\\) のとき、決定係数を小数第2位まで求めよ。",
    answer: "\\(R^2\\approx0.55\\)",
    numericAnswer: 0.55,
    tolerance: 0.005,
    formula: "R^2=r^2",
    steps: [
      "相関係数を二乗する。",
      "\\(R^2=0.741828^2\\approx0.55031\\)",
      "小数第2位までで \\(R^2\\approx0.55\\) となる。",
    ],
    explanation: "この回帰直線は血圧の変動のおよそ \\(55\\%\\) を年齢との直線関係で説明する。",
  }),

  courseQuestion({
    id: "stats-ex2-sample-space",
    topic: "counting",
    genre: "標本空間",
    difficulty: 1,
    format: "choice",
    prompt: "ジョーカーを除くトランプから1枚引き、マークだけを観測する。標本空間として正しいものを選べ。",
    answer: "\\(\\Omega=\\{\\spadesuit,\\heartsuit,\\diamondsuit,\\clubsuit\\}\\)",
    options: [
      "\\(\\Omega=\\{\\spadesuit,\\heartsuit,\\diamondsuit,\\clubsuit\\}\\)",
      "\\(\\Omega=\\{\\spadesuit,\\heartsuit\\}\\)",
      "\\(\\Omega=\\{1,2,3,4\\}\\)",
      "\\(\\Omega=\\varnothing\\)",
    ],
    formula: "\\Omega=\\{\\text{起こり得るすべての標本点}\\}",
    steps: [
      "観測するのはカードの数字ではなくマークである。",
      "起こり得るマークをすべて列挙する。",
      "\\(\\Omega=\\{\\spadesuit,\\heartsuit,\\diamondsuit,\\clubsuit\\}\\) となる。",
    ],
    explanation: "標本空間には、その試行で起こり得る結果を漏れなく重複なく並べる。",
  }),
  courseQuestion({
    id: "stats-ex2-elementary-event",
    topic: "counting",
    genre: "根元事象",
    difficulty: 1,
    format: "choice",
    prompt: "同じ試行で、根元事象の例として正しいものを選べ。",
    answer: "\\(\\{\\spadesuit\\}\\)",
    options: ["\\(\\{\\spadesuit\\}\\)", "\\(\\{\\spadesuit,\\heartsuit\\}\\)", "\\(\\Omega\\)", "\\(\\varnothing\\)"],
    formula: "A=\\{\\omega\\}",
    steps: [
      "根元事象は標本点を一つだけ含む事象である。",
      "\\(\\{\\spadesuit\\}\\) は要素を一つだけ含む。",
    ],
    explanation: "二つ以上の標本点を含むものは複合事象になる。",
  }),
  courseQuestion({
    id: "stats-ex2-permutation",
    topic: "counting",
    genre: "順列",
    difficulty: 1,
    format: "number",
    prompt: "5人から3人を選び、順番を付けて並べる方法は何通りか。",
    answer: "\\({}_5P_3=60\\) 通り",
    numericAnswer: 60,
    formula: "{}_nP_r=\\frac{n!}{(n-r)!}",
    steps: ["順番を区別するので順列を使う。", "\\({}_5P_3=5\\times4\\times3=60\\)"],
    explanation: "同じ3人でも並ぶ順序が違えば別の結果として数える。",
  }),
  courseQuestion({
    id: "stats-ex2-combination",
    topic: "counting",
    genre: "組合せ",
    difficulty: 1,
    format: "number",
    prompt: "5人から順番を区別せずに3人を選ぶ方法は何通りか。",
    answer: "\\({}_5C_3=10\\) 通り",
    numericAnswer: 10,
    formula: "{}_nC_r=\\frac{n!}{r!(n-r)!}",
    steps: ["順番を区別しないので組合せを使う。", "\\({}_5C_3=\\frac{5!}{3!2!}=10\\)"],
    explanation: "順列 \\(60\\) 通りを選んだ3人の並べ方 \\(3!\\) で割っても求められる。",
  }),
  courseQuestion({
    id: "stats-ex2-card-spade",
    topic: "counting",
    genre: "確率",
    difficulty: 1,
    format: "number",
    prompt: "ジョーカーを除く52枚のトランプから1枚引く。スペードを引く確率を求めよ。",
    answer: "\\(\\frac{1}{4}\\)",
    numericAnswer: 1 / 4,
    formula: "P(A)=\\frac{|A|}{|\\Omega|}",
    steps: ["スペードは \\(13\\) 枚ある。", "\\(P(\\spadesuit)=\\frac{13}{52}=\\frac{1}{4}\\)"],
    explanation: "4種類のマークはそれぞれ同じ \\(13\\) 枚ずつ含まれる。",
  }),
  courseQuestion({
    id: "stats-ex2-card-face",
    topic: "counting",
    genre: "確率",
    difficulty: 1,
    format: "number",
    prompt: "ジョーカーを除く52枚のトランプから1枚引く。絵札を \\(J,Q,K\\) とすると、絵札を引く確率を求めよ。",
    answer: "\\(\\frac{3}{13}\\)",
    numericAnswer: 3 / 13,
    tolerance: 1e-9,
    formula: "P(A)=\\frac{|A|}{|\\Omega|}",
    steps: ["各マークに絵札が \\(3\\) 枚あるので、全部で \\(4\\times3=12\\) 枚。", "\\(\\frac{12}{52}=\\frac{3}{13}\\)"],
    explanation: "エースは絵札に含めず、\\(J,Q,K\\) のみを数える。",
  }),
  courseQuestion({
    id: "stats-ex2-card-spade-face",
    topic: "counting",
    genre: "積事象",
    difficulty: 1,
    format: "number",
    prompt: "ジョーカーを除く52枚のトランプから1枚引く。スペードの絵札を引く確率を求めよ。",
    answer: "\\(\\frac{3}{52}\\)",
    numericAnswer: 3 / 52,
    tolerance: 1e-9,
    formula: "P(A\\cap B)=\\frac{|A\\cap B|}{|\\Omega|}",
    steps: ["スペードの絵札は \\(J,Q,K\\) の \\(3\\) 枚。", "\\(P(\\spadesuit\\cap\\text{絵札})=\\frac{3}{52}\\)"],
    explanation: "「スペードかつ絵札」なので、二つの条件を同時に満たすカードだけを数える。",
  }),
  courseQuestion({
    id: "stats-ex2-card-union",
    topic: "counting",
    genre: "和事象",
    difficulty: 2,
    format: "number",
    prompt: "ジョーカーを除く52枚のトランプから1枚引く。スペードまたは絵札を引く確率を求めよ。",
    answer: "\\(\\frac{11}{26}\\)",
    numericAnswer: 11 / 26,
    tolerance: 1e-9,
    formula: "P(A\\cup B)=P(A)+P(B)-P(A\\cap B)",
    steps: [
      "スペードは \\(13\\) 枚、絵札は \\(12\\) 枚、両方を満たすカードは \\(3\\) 枚。",
      "重複する \\(3\\) 枚を一度引く。",
      "\\(\\frac{13+12-3}{52}=\\frac{22}{52}=\\frac{11}{26}\\)",
    ],
    explanation: "単純に足すとスペードの絵札を二重に数えるため、共通部分を引く。",
  }),
  courseQuestion({
    id: "stats-ex2-card-neither",
    topic: "counting",
    genre: "補事象",
    difficulty: 2,
    format: "number",
    prompt: "ジョーカーを除く52枚のトランプから1枚引く。スペードでも絵札でもないカードを引く確率を求めよ。",
    answer: "\\(\\frac{15}{26}\\)",
    numericAnswer: 15 / 26,
    tolerance: 1e-9,
    formula: "P((A\\cup B)^c)=1-P(A\\cup B)",
    steps: ["スペードまたは絵札である確率は \\(\\frac{11}{26}\\)。", "\\(1-\\frac{11}{26}=\\frac{15}{26}\\)"],
    explanation: "「どちらでもない」は「少なくともどちらかである」の補事象として求める。",
  }),
  courseQuestion({
    id: "stats-ex2-color-same-number",
    topic: "counting",
    genre: "組合せ確率",
    difficulty: 2,
    format: "number",
    prompt: "赤・青・黄・緑の各色に番号1～5が1枚ずつある計20枚から、3枚を同時に選ぶ。3枚がすべて同じ番号となる確率を求めよ。",
    answer: "\\(\\frac{1}{57}\\)",
    numericAnswer: 1 / 57,
    tolerance: 1e-9,
    formula: "P(A)=\\frac{5\\binom{4}{3}}{\\binom{20}{3}}",
    steps: [
      "全選び方は \\(\\binom{20}{3}=1140\\) 通り。",
      "番号を \\(5\\) 通りから選び、その番号を持つ4色から3色を選ぶ。",
      "\\(\\frac{5\\binom{4}{3}}{\\binom{20}{3}}=\\frac{20}{1140}=\\frac{1}{57}\\)",
    ],
    explanation: "同じ番号でもカード自体は色によって区別される。",
  }),
  courseQuestion({
    id: "stats-ex2-color-all-distinct",
    topic: "counting",
    genre: "組合せ確率",
    difficulty: 3,
    format: "number",
    prompt: "同じ20枚のカードから3枚を同時に選ぶ。3枚の色も番号もすべて異なる確率を求めよ。",
    answer: "\\(\\frac{4}{19}\\)",
    numericAnswer: 4 / 19,
    tolerance: 1e-9,
    formula: "P(A)=\\frac{\\binom{4}{3}\\binom{5}{3}3!}{\\binom{20}{3}}",
    steps: [
      "3色を \\(\\binom{4}{3}\\) 通り、3番号を \\(\\binom{5}{3}\\) 通りで選ぶ。",
      "選んだ3色と3番号の対応は \\(3!\\) 通り。",
      "\\(\\frac{\\binom{4}{3}\\binom{5}{3}3!}{\\binom{20}{3}}=\\frac{240}{1140}=\\frac{4}{19}\\)",
    ],
    explanation: "色と番号を選ぶだけでは対応の仕方を数えていないため、最後に \\(3!\\) を掛ける。",
  }),
  courseQuestion({
    id: "stats-ex2-color-one-red",
    topic: "counting",
    genre: "組合せ確率",
    difficulty: 2,
    format: "number",
    prompt: "同じ20枚のカードから3枚を同時に選ぶ。赤いカードがちょうど1枚含まれる確率を求めよ。",
    answer: "\\(\\frac{35}{76}\\)",
    numericAnswer: 35 / 76,
    tolerance: 1e-9,
    formula: "P(A)=\\frac{\\binom{5}{1}\\binom{15}{2}}{\\binom{20}{3}}",
    steps: [
      "赤5枚から1枚を選ぶ方法は \\(\\binom{5}{1}\\) 通り。",
      "赤以外15枚から2枚を選ぶ方法は \\(\\binom{15}{2}\\) 通り。",
      "\\(\\frac{\\binom{5}{1}\\binom{15}{2}}{\\binom{20}{3}}=\\frac{525}{1140}=\\frac{35}{76}\\)",
    ],
    explanation: "「ちょうど1枚」なので、残り2枚は必ず赤以外から選ぶ。",
  }),
  courseQuestion({
    id: "stats-ex2-bags-same-color",
    topic: "conditional",
    genre: "独立な試行",
    difficulty: 2,
    format: "number",
    prompt: "Aの袋には黒3個・白2個、Bの袋には黒2個・白3個がある。各人が自分の袋から1個ずつ引くとき、同じ色になる確率を求めよ。",
    answer: "\\(\\frac{12}{25}\\)",
    numericAnswer: 12 / 25,
    formula: "P(\\text{同色})=P(A_B)P(B_B)+P(A_W)P(B_W)",
    steps: [
      "両方黒の確率は \\(\\frac{3}{5}\\cdot\\frac{2}{5}=\\frac{6}{25}\\)。",
      "両方白の確率は \\(\\frac{2}{5}\\cdot\\frac{3}{5}=\\frac{6}{25}\\)。",
      "\\(\\frac{6}{25}+\\frac{6}{25}=\\frac{12}{25}\\)",
    ],
    explanation: "二つの袋からの取り出しは独立なので各経路では確率を掛け、排反な二経路は足す。",
  }),
  courseQuestion({
    id: "stats-ex2-bags-all-black",
    topic: "counting",
    genre: "組合せ確率",
    difficulty: 2,
    format: "number",
    prompt: "Aの袋には黒3個・白2個、Bの袋には黒2個・白3個がある。各人が自分の袋から同時に2個ずつ引くとき、4個すべてが黒である確率を求めよ。",
    answer: "\\(\\frac{3}{100}\\)",
    numericAnswer: 3 / 100,
    formula: "P=\\frac{\\binom{3}{2}}{\\binom{5}{2}}\\cdot\\frac{\\binom{2}{2}}{\\binom{5}{2}}",
    steps: [
      "Aが黒2個を引く確率は \\(\\frac{\\binom{3}{2}}{\\binom{5}{2}}=\\frac{3}{10}\\)。",
      "Bが黒2個を引く確率は \\(\\frac{\\binom{2}{2}}{\\binom{5}{2}}=\\frac{1}{10}\\)。",
      "\\(\\frac{3}{10}\\cdot\\frac{1}{10}=\\frac{3}{100}\\)",
    ],
    explanation: "各袋の中では復元しない2個同時抽出なので組合せを使い、二つの袋の結果は掛ける。",
  }),
  courseQuestion({
    id: "stats-ex2-bags-even-black",
    topic: "counting",
    genre: "場合分け",
    difficulty: 3,
    format: "number",
    prompt: "Aの袋には黒3個・白2個、Bの袋には黒2個・白3個がある。各人が自分の袋から同時に2個ずつ引く。取り出した黒玉の合計が偶数である確率を求めよ。",
    answer: "\\(\\frac{13}{25}\\)",
    numericAnswer: 13 / 25,
    formula: "P(\\text{偶数})=P(A_{\\mathrm{even}})P(B_{\\mathrm{even}})+P(A_{\\mathrm{odd}})P(B_{\\mathrm{odd}})",
    steps: [
      "Aの黒玉数が偶数となる確率は \\(\\frac{\\binom{2}{2}+\\binom{3}{2}}{\\binom{5}{2}}=\\frac{2}{5}\\)、奇数は \\(\\frac{3}{5}\\)。",
      "Bについても偶数は \\(\\frac{2}{5}\\)、奇数は \\(\\frac{3}{5}\\)。",
      "合計が偶数になるのは偶数＋偶数または奇数＋奇数。",
      "\\(\\left(\\frac{2}{5}\\right)^2+\\left(\\frac{3}{5}\\right)^2=\\frac{4}{25}+\\frac{9}{25}=\\frac{13}{25}\\)",
    ],
    explanation: "元資料で曖昧だった抽出個数を、この教材では各人2個ずつと明記している。",
  }),
  courseQuestion({
    id: "stats-ex2-lottery-at-least-one",
    topic: "counting",
    genre: "余事象",
    difficulty: 2,
    format: "number",
    prompt: "12本のくじに1等1本、2等4本、はずれ7本がある。同時に3本引くとき、当たりを少なくとも1本引く確率を求めよ。",
    answer: "\\(\\frac{37}{44}\\)",
    numericAnswer: 37 / 44,
    tolerance: 1e-9,
    formula: "P(\\text{少なくとも1本})=1-\\frac{\\binom{7}{3}}{\\binom{12}{3}}",
    steps: [
      "余事象は3本すべてがはずれであること。",
      "\\(1-\\frac{\\binom{7}{3}}{\\binom{12}{3}}=1-\\frac{35}{220}\\)",
      "\\(\\frac{185}{220}=\\frac{37}{44}\\)",
    ],
    explanation: "「少なくとも1本」は、当たりの本数ごとに分けるより余事象を使う方が短い。",
  }),
  courseQuestion({
    id: "stats-ex2-lottery-one-each",
    topic: "counting",
    genre: "組合せ確率",
    difficulty: 2,
    format: "number",
    prompt: "同じ12本のくじから3本を同時に引く。1等、2等、はずれをそれぞれ1本ずつ引く確率を求めよ。",
    answer: "\\(\\frac{7}{55}\\)",
    numericAnswer: 7 / 55,
    tolerance: 1e-9,
    formula: "P=\\frac{\\binom{1}{1}\\binom{4}{1}\\binom{7}{1}}{\\binom{12}{3}}",
    steps: [
      "有利な選び方は \\(\\binom{1}{1}\\binom{4}{1}\\binom{7}{1}=28\\) 通り。",
      "全選び方は \\(\\binom{12}{3}=220\\) 通り。",
      "\\(\\frac{28}{220}=\\frac{7}{55}\\)",
    ],
    explanation: "同時に引くので順番は区別せず、種類ごとの組合せを掛け合わせる。",
  }),
  courseQuestion({
    id: "stats-ex2-lottery-two-seconds",
    topic: "counting",
    genre: "場合分け",
    difficulty: 3,
    format: "number",
    prompt: "同じ12本のくじから3本を同時に引く。2等を2本以上引く確率を求めよ。",
    answer: "\\(\\frac{13}{55}\\)",
    numericAnswer: 13 / 55,
    tolerance: 1e-9,
    formula: "P=\\frac{\\binom{4}{2}\\binom{8}{1}+\\binom{4}{3}}{\\binom{12}{3}}",
    steps: [
      "2等がちょうど2本なら \\(\\binom{4}{2}\\binom{8}{1}=48\\) 通り。",
      "2等が3本なら \\(\\binom{4}{3}=4\\) 通り。",
      "\\(\\frac{48+4}{220}=\\frac{52}{220}=\\frac{13}{55}\\)",
    ],
    explanation: "「2本以上」にはちょうど2本と3本の二つの場合があり、互いに重ならないので足す。",
  }),
  courseQuestion({
    id: "stats-ex2-dice-ratio-one",
    topic: "counting",
    genre: "全列挙",
    difficulty: 1,
    format: "number",
    prompt: "1個の公平なさいころを2回投げ、順に出た目を \\(a,b\\)、\\(u=\\frac{a}{b}\\) とする。\\(u=1\\) となる確率を求めよ。",
    answer: "\\(\\frac{1}{6}\\)",
    numericAnswer: 1 / 6,
    tolerance: 1e-9,
    formula: "P(u=1)=P(a=b)",
    steps: ["全結果は \\(6\\times6=36\\) 通り。", "\\(a=b\\) は \\((1,1),\\ldots,(6,6)\\) の \\(6\\) 通り。", "\\(P(u=1)=\\frac{6}{36}=\\frac{1}{6}\\)"],
    explanation: "分母 \\(b\\) は常に正なので、\\(\\frac{a}{b}=1\\) は \\(a=b\\) と同値である。",
  }),
  courseQuestion({
    id: "stats-ex2-dice-ratio-greater",
    topic: "counting",
    genre: "全列挙",
    difficulty: 2,
    format: "number",
    prompt: "同じ試行で \\(u>1\\) となる確率を求めよ。",
    context: "1個の公平なさいころを2回投げ、順に出た目を \\(a,b\\)、\\(u=\\frac{a}{b}\\) とする。",
    answer: "\\(\\frac{5}{12}\\)",
    numericAnswer: 5 / 12,
    tolerance: 1e-9,
    formula: "P(u>1)=P(a>b)",
    steps: [
      "\\(u>1\\) は \\(a>b\\) と同値。",
      "等しい \\(6\\) 通りを除いた \\(30\\) 通りは、\\(a>b\\) と \\(a<b\\) に対称に分かれる。",
      "\\(\\frac{15}{36}=\\frac{5}{12}\\)",
    ],
    explanation: "順序対を入れ替えると \\(a>b\\) と \\(a<b\\) が一対一に対応する。",
  }),
  courseQuestion({
    id: "stats-ex2-dice-ratio-integer",
    topic: "counting",
    genre: "全列挙",
    difficulty: 3,
    format: "number",
    prompt: "同じ試行で \\(u\\) が整数となる確率を求めよ。",
    context: "1個の公平なさいころを2回投げ、順に出た目を \\(a,b\\)、\\(u=\\frac{a}{b}\\) とする。",
    answer: "\\(\\frac{7}{18}\\)",
    numericAnswer: 7 / 18,
    tolerance: 1e-9,
    formula: "u\\in\\mathbb{Z}\\iff b\\mid a",
    steps: [
      "\\(b=1,2,3,4,5,6\\) ごとに、\\(b\\) の倍数となる \\(a\\) を数える。",
      "有利な組数は順に \\(6,3,2,1,1,1\\) で、合計 \\(14\\) 通り。",
      "\\(\\frac{14}{36}=\\frac{7}{18}\\)",
    ],
    explanation: "\\(\\frac{a}{b}\\) が整数である条件は、\\(b\\) が \\(a\\) を割り切ることである。",
  }),
  courseQuestion({
    id: "stats-ex2-replacement-all-letters",
    topic: "counting",
    genre: "復元抽出",
    difficulty: 2,
    format: "number",
    prompt: "A、B、C、Dの4枚から1枚を引いて戻す試行を4回行う。4文字がすべて現れる確率を求めよ。",
    answer: "\\(\\frac{3}{32}\\)",
    numericAnswer: 3 / 32,
    formula: "P=\\frac{4!}{4^4}",
    steps: [
      "全結果は各回4通りなので \\(4^4=256\\) 通り。",
      "4文字がすべて現れるには各文字がちょうど1回ずつで、並びは \\(4!=24\\) 通り。",
      "\\(\\frac{24}{256}=\\frac{3}{32}\\)",
    ],
    explanation: "4回で4種類すべてを出すには重複できないため、4文字の順列を数えればよい。",
  }),
  courseQuestion({
    id: "stats-ex2-score-one",
    topic: "random-variable",
    genre: "二項型確率",
    difficulty: 2,
    format: "number",
    prompt: "A、B、C、Dの4枚から復元抽出を4回行う。Aをちょうど1回引いたとき得点を1点とする。1点となる確率を求めよ。",
    answer: "\\(\\frac{27}{64}\\)",
    numericAnswer: 27 / 64,
    formula: "P(X=1)=\\binom{4}{1}\\left(\\frac14\\right)\\left(\\frac34\\right)^3",
    steps: [
      "Aが出る回を \\(\\binom{4}{1}\\) 通りから選ぶ。",
      "その回にAが出る確率は \\(\\frac{1}{4}\\)、残り3回にA以外が出る確率は \\(\\left(\\frac{3}{4}\\right)^3\\)。",
      "\\(\\binom{4}{1}\\left(\\frac{1}{4}\\right)\\left(\\frac{3}{4}\\right)^3=\\frac{108}{256}=\\frac{27}{64}\\)",
    ],
    explanation: "復元抽出なので各回は独立で、Aが出る確率は毎回 \\(\\frac{1}{4}\\) で一定である。",
  }),
  courseQuestion({
    id: "stats-ex2-score-zero",
    topic: "random-variable",
    genre: "二項型確率",
    difficulty: 3,
    format: "number",
    prompt: "同じ試行で、Aを引いた回数が0回・3回・4回なら0点とする。0点となる確率を求めよ。",
    context: "A、B、C、Dの4枚から1枚を引いて戻す試行を4回行う。",
    answer: "\\(\\frac{47}{128}\\)",
    numericAnswer: 47 / 128,
    formula: "P(S=0)=P(X=0)+P(X=3)+P(X=4)",
    steps: [
      "Aが0回は \\(\\left(\\frac{3}{4}\\right)^4=\\frac{81}{256}\\)。",
      "Aが3回は \\(\\binom{4}{3}\\left(\\frac{1}{4}\\right)^3\\left(\\frac{3}{4}\\right)=\\frac{12}{256}\\)。",
      "Aが4回は \\(\\left(\\frac{1}{4}\\right)^4=\\frac{1}{256}\\)。",
      "\\(\\frac{81+12+1}{256}=\\frac{94}{256}=\\frac{47}{128}\\)",
    ],
    explanation: "得点0になる三つの場合は同時には起こらないので、それぞれの確率を足す。",
  }),
];
